### ISSUE TITLE
【调整】用户网站设置中 选项文字调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1000]
内置gitlab 调整为 官方git数据源
![image](https://user-images.githubusercontent.com/22001356/32944367-518271ea-cbca-11e7-8e11-188b908541ec.png)

**Comment by ZhangKaitlyn** [comment]
需要注册新用户才是 改了的 旧用户的数据需要修改数据库 @William0911

**Comment by Sandu1213** [comment]
@William0911 请将旧用户的的数据进行调整，调整完毕后再通知验证，谢谢

**Comment by William0911** [comment]
脚本已经做好了，请测试效果

**Comment by Sandu1213** [comment]
http://10.27.2.117:8099环境验证通过，待release环境再验证

**Comment by William0911** [comment]
商量了一下觉得改数据库有一定风险，由 @yuanoook 通过UI解决
