### ISSUE TITLE
【Bug】页面编辑器里进行插入图片操作，高概率出现上传失败，无法插入的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1012]
## The problem
页面编辑器里进行插入图片操作，高概率出现上传失败，无法插入的情况

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.75
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器->插入图片

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器，对网站内容进行插入图片操作，上传图片，观察结果

* Expected Result:
1.插入成功，图片显示正确
* Actual Result:
1.插入失败，图片显示有误
 

## Attachments (eg:logs/video/screenshot)
![insertpic](https://user-images.githubusercontent.com/21214285/33049792-a629f536-ce9c-11e7-94da-ea93eefc9ecc.gif)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.editor.stage.keepwork.com

**Comment by Sandu1213** [comment]
http://fix.editor.stage.keepwork.com 环境验证通过
