### ISSUE TITLE
浏览器中的标题和Icon

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#102]
![image](https://cloud.githubusercontent.com/assets/94537/24180391/a1a78e50-0eef-11e7-9f22-23593e116bed.png)

图片为某个我们的Icon

文字为当前`网页名-用户名／网站名`，也就是

![image](https://cloud.githubusercontent.com/assets/94537/24180441/e81aef08-0eef-11e7-92ff-4449ea8800e0.png)

**Comment by wxaxiaoyao** [comment]
已改
