### ISSUE TITLE
【Bug-画板】粘贴图片多次导致画布延长，再删除图片，仅剩一个画布时，建议画布可以自动居中显示

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1036]
## The problem
粘贴图片多次导致画布延长，再删除图片，仅剩一个画布时，建议画布可以自动居中显示

## Environment
* OS Info: Window10
* browser Info: chrome  62.0.3202.75
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器->mod ->画板

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器，选择画板模块，粘贴多次以后使画布进行延长
2.再将粘贴的图片进行删除，删除只剩一个的时候，观察画布是否会自动居中显示

* Expected Result:
1.画布会自动居中显示
* Actual Result:
1.画布不会居中显示，会出现大面积灰屏的情况
 

## Attachments (eg:logs/video/screenshot)

**Comment by onedou** [comment]
researching
