### ISSUE TITLE
【需求】当编辑的文件过多时，需要一个‘全部保存’的按钮，请设计

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1037]
### 背景：
当编辑的文件过多时，如果一个个去保存，用户体验极差，建议增加一个“全部保存”或者“一键保存所有”的按钮。
![image](https://user-images.githubusercontent.com/21214285/33163965-c9dd383c-d06b-11e7-8813-14ac124c1ee5.png)

**Comment by Tibet0312** [comment]
已有‘’保存全部‘’功能

![image](https://user-images.githubusercontent.com/25898720/33165417-b4c6898e-d071-11e7-84a7-9ce73fde3909.png)

**Comment by Sandu1213** [comment]
目前”保存全部“的功能实现不合理，还是分单个单个的保存的。会出现弹窗多次的情况，请优化。 @ZhangKaitlyn 
对于设计上的‘保存全部’功能，因为比较常用，个人建议加强一下设计或者能够明显的告知用户，不然这个功能太难找了，我估计80%的人都不知道呀😭。 @Tibet0312 @azothli

**Comment by azothli** [comment]
这两个按钮在已打开文件中有内容的时候，可以一直显示

**Comment by Sandu1213** [comment]
@ZhangKaitlyn 那晚点一起调整下，谢谢

**Comment by ZhangKaitlyn** [comment]
🆗

**Comment by ZhangKaitlyn** [comment]
测试地址： http://10.27.3.7:8099
