### ISSUE TITLE
手机绑定提示问题

### ISSUE THREAD

**Issue by yuanoook** [tatfook/wikicraft#1043]

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/33173216-511319bc-d08e-11e7-8d27-d1129cab9be5.png)

![6 pg6 2 85gt439 4by 74s](https://user-images.githubusercontent.com/28430070/33173207-4003cdce-d08e-11e7-936a-ac06e1dc5a99.png)
1.绑定按钮旁边，建议仅中国大陆手机

**Comment by azothli** [comment]
暂不需要
