### ISSUE TITLE
【Bug】从paracraft分享的网站，由于URL地址有误，点击打开失败

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1045]
## The problem
从paracraft分享的网站，由于URL地址有误，点击打开失败

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.75
* URL: [keepwork.com](http://keepwork.com) 
* Model:  网站管理->网站访问

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.将账号A的用户名改为中文名称
2.登录到paracraft上去创建世界，创建完成后进行分享
3.分享后，回到站点管理里对网站进行查看，观察站点信息是否正确
* Expected Result:
1.站点可以正常打开，信息显示正确
* Actual Result:
1.站点打开失败
 

## Attachments (eg:logs/video/screenshot)
![url 7](https://user-images.githubusercontent.com/21214285/33176993-01983b34-d09c-11e7-8288-749c418dbdda.png)

**Comment by onedou** [comment]
这个版本是最新的吗？

**Comment by onedou** [comment]
测试站 http://fix.world.list.link.stage.keepwork.com

**Comment by Sandu1213** [comment]
验证通过
![image](https://user-images.githubusercontent.com/21214285/33361647-04e8776e-d514-11e7-83eb-f5f407cd344c.png)
