### ISSUE TITLE
I18n 实现

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#1046]
1. 选择前端I18n技术方案
2. 提取页面代码中文内容，汇总整理，并生成zh-cn文件
3. 将文件交给产品，获取英文版本

**Comment by yuanoook** [comment]
1.翻译机制已经加上，使用的是前端方案。
2.尝试翻译了大部分内容。
3.可能还有小部分没有覆盖到，后面持续补充。
4.翻译是用金山wps批量翻译的，可能词义需要修正，后面持续跟踪。

**Comment by Sandu1213** [comment]
验证记录：
1.还存在中文的情况  ---Rango会先进行排查，稍后再关注
2.语义不合理的地方汇总
- 登录    -> Sign In /Log In
- 注册    -> Sign Up
- 退出登录   -> Logout 
- 忘记密码   ->Forgot Password
- 修改  -> Save Changes
- 我的历史  -> History
3.切换英文过长导致的样式问题汇总
4.其他
- 账号绑定 里不同的应用后面不用每个都binding

**Comment by Sandu1213** [comment]
与Rango讨论后，暂时先优先关注需要具体操作才会出来的弹窗，观察翻译是否到位。
1.修改个人资料后，修改成功后弹窗提醒
![image](https://user-images.githubusercontent.com/21214285/33653443-22387406-daa8-11e7-85f7-1d9910b3b89f.png)
2.修改密码后弹窗
![image](https://user-images.githubusercontent.com/21214285/33653553-6170ddfc-daa8-11e7-8491-1771f032bbc0.png)
![image](https://user-images.githubusercontent.com/21214285/33653562-691d4b58-daa8-11e7-9dbf-3be32bfd77cf.png)
![image](https://user-images.githubusercontent.com/21214285/33653613-91153526-daa8-11e7-90da-3e90199bb0a2.png)
3.搜索页面
![image](https://user-images.githubusercontent.com/21214285/33653710-e168bf66-daa8-11e7-901c-f2440562f722.png)

4.网站管理->权限管理页添加不存在的用户弹窗
![image](https://user-images.githubusercontent.com/21214285/33653766-004878ae-daa9-11e7-80bd-c1b0d04b1cc9.png)
5.网站管理->网站设置，直接修改站点设置成功弹窗
![image](https://user-images.githubusercontent.com/21214285/33653869-56cf1a98-daa9-11e7-9d8e-ab75755e1549.png)
6.网站删除弹窗
![image](https://user-images.githubusercontent.com/21214285/33653945-8fc11c70-daa9-11e7-8dba-8174d31a7942.png)
7.我的网盘相关弹窗
![image](https://user-images.githubusercontent.com/21214285/33653977-a7f2f976-daa9-11e7-9f6b-bdf7c5ca47d2.png)
![image](https://user-images.githubusercontent.com/21214285/33654039-e0a16d2a-daa9-11e7-8470-8dbd04812a54.png)
![image](https://user-images.githubusercontent.com/21214285/33654220-67e6642a-daaa-11e7-8f85-3d7ce0592523.png)

8.邀请好友，输入错误邮箱弹窗
![image](https://user-images.githubusercontent.com/21214285/33654093-089ec098-daaa-11e7-9f1b-73a73a96cf1b.png)

9.关注粉丝相关
![image](https://user-images.githubusercontent.com/21214285/33654381-dd863840-daaa-11e7-8990-7a690ebb1ff1.png)
![image](https://user-images.githubusercontent.com/21214285/33654400-ee39896c-daaa-11e7-8feb-1bfcb6315e2b.png)
![image](https://user-images.githubusercontent.com/21214285/33654417-03f982ca-daab-11e7-9fdb-1314d4e51d8a.png)

10.作品收藏与取消弹窗
![image](https://user-images.githubusercontent.com/21214285/33654451-1fa3d854-daab-11e7-9a4d-917e4e1e438e.png)
![image](https://user-images.githubusercontent.com/21214285/33654460-2afa945e-daab-11e7-94df-72bb3a307b6e.png)

11.网站分享弹窗
![image](https://user-images.githubusercontent.com/21214285/33654486-3f602ddc-daab-11e7-939a-4a1db657be17.png)

12.动态信息等
![image](https://user-images.githubusercontent.com/21214285/33654728-f7ddd0e4-daab-11e7-8ab3-5953ce2bbcd6.png)

**Comment by Sandu1213** [comment]
13.页面编辑器相关
![image](https://user-images.githubusercontent.com/21214285/33655170-4d40074a-daad-11e7-8576-036a2b8d21d5.png)
![image](https://user-images.githubusercontent.com/21214285/33655179-55d81212-daad-11e7-8484-e2b0b2bdcfb5.png)
![image](https://user-images.githubusercontent.com/21214285/33655213-6a2a8c40-daad-11e7-8cae-7645949bf6f5.png)
![image](https://user-images.githubusercontent.com/21214285/33655234-784e3cd6-daad-11e7-9322-eb3c0fb19c5a.png)
![image](https://user-images.githubusercontent.com/21214285/33655278-98c3e416-daad-11e7-9a83-8bc4e513ce4e.png)
![image](https://user-images.githubusercontent.com/21214285/33655337-ba06ecd6-daad-11e7-83d2-8e1fb0886999.png)
![image](https://user-images.githubusercontent.com/21214285/33655379-dacb2310-daad-11e7-93e0-de247a1d3ee5.png)
![image](https://user-images.githubusercontent.com/21214285/33655386-e4855f10-daad-11e7-85af-19b85e589ed5.png)
![image](https://user-images.githubusercontent.com/21214285/33655425-fd7f4c06-daad-11e7-9ce1-067ec51fd2ae.png)
