### ISSUE TITLE
【优化】编辑器 存盘提醒

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1052]
目前进行存盘的时候，不成功，提醒的效果很难被感觉到。
存盘不成功作为一个破坏性比较大的事件，需要更明确的提醒。

弹出提示框会比一闪而过的提醒更加恰当。
-----------------------------------------------
保存出了些意外，没有成功。
【重试保存】【一会再说】
-----------------------------------------------

**Comment by leopoldchen** [comment]
Issue moved to [tatfook/keepwork #210](https://github.com/tatfook/keepwork/issues/210) via [**ZenHub**](https://www.zenhub.com/)
