### ISSUE TITLE
【需求】屏蔽参与的网站项目

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1058]
主动退出，不再参与某个项目，需要提供对应的功能

**Comment by azothli** [comment]
逻辑上，当前用户没有拒绝被授权的机制，增加一个类似黑名单的机制，屏蔽某些网站的管理权限。

网站管理中，新增分页“参与的网站”
![image](https://user-images.githubusercontent.com/22001356/33297496-451a1f48-d41c-11e7-8e73-b95130a4fc90.png)

内容为参与网站的列表。
![image](https://user-images.githubusercontent.com/22001356/33297565-a89d878a-d41c-11e7-8b80-9a57efe9e8eb.png)
对比我的网站，调整操作，去除设置按钮，删除改为一个 代表屏蔽的按钮，屏蔽项目。
点击添加到屏蔽列表。不再作为“参与网站查看管理”。网站进入安静模式。
因为授权可能是来自账号，可能是来自组群，所以并没有真的删除、放弃权限，只是不看了。

下面增加表格，屏蔽的网站。
显示对应的信息，操作按钮 【查看】【取消屏蔽】

**Comment by azothli** [comment]
屏蔽
![image](https://user-images.githubusercontent.com/22001356/33297830-34476502-d41e-11e7-99df-f8bbaeafbfa0.png)

取消屏蔽
![image](https://user-images.githubusercontent.com/22001356/33297862-4effdcee-d41e-11e7-81b7-d0a3f3095b73.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/33542820-8bc604d2-d90f-11e7-9e0d-aabbc287c429.png)

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #191](https://github.com/tatfook/keepwork/issues/191) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ExerciseBook** [comment]
ignore the notifications
