### ISSUE TITLE
WIKI模版使用_theme文件的方式

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#106]
你实现时，渲染每个网页时，如果发现没有页面模板，就将_theme的内容放进去。 
生成网站时，也自动生成一个_theme
逍遥--吴香安(765485868) 3/21/2017 10:42:54 PM
可以直接放在站点表的一个子段里，在站点设置修改整体布局模板，后面我改下
LiXizhi(lixizhi@yeah.net) 3/21/2017 10:44:05 PM
ok  
LiXizhi(lixizhi@yeah.net) 3/21/2017 10:46:59 PM
using _theme file maybe better. But you can improve the performance by caching it in our db. 
so all data is backed up by git. 
LiXizhi(lixizhi@yeah.net) 3/21/2017 10:51:39 PM
 这个和Github pages 也类似。 所有的配置信息本身也是文件。 编译后变成数据库中的内容。 
例如CNAME 配置也是一个文件，但是为了性能， 我们在数据库里还有一个Cache
LiXizhi(lixizhi@yeah.net) 3/21/2017 10:53:25 PM
https://github.com/mono/website/blob/gh-pages/CNAME
LiXizhi(lixizhi@yeah.net) 3/21/2017 10:55:37 PM
we can install a hook when some internal file is modified and update/rebuild our db content for the website. 
LiXizhi(lixizhi@yeah.net) 3/21/2017 11:00:24 PM
using db is also fine.  we implement the function first.

**Comment by wxaxiaoyao** [comment]
已改

**Comment by wxaxiaoyao** [comment]
已改, _theme文件实现
