### ISSUE TITLE
【调整】手机微信登录的提示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1062]
腾讯做了限制（微信自身的功能）
如果扫描来自摄像头，可以登录
如果来自图片，直接跳开放平台
应该是为了加强账号安全的。

因此微信登录方式，增加提示：

“因微信登录自身的限制，该功能仅限使用设备扫描进入。我们推荐您用手机微信登录电脑浏览器中的Keepwork。”

![image](https://user-images.githubusercontent.com/22001356/33354138-51ea2f80-d4ec-11e7-8b2c-fa26f5b24e1b.png)

看下如何显示好这个效果。让用户比较清楚的了解到这个信息。

**Comment by azothli** [comment]
仅支持手机微信登录电脑浏览器中的Keepwork。

**Comment by wanglin727** [comment]
```//Base style for 图层 1
let style = UIView(frame: CGRect(x: 0, y: 0, width: 375, height: 667))
style.alpha = 0.68```

**Comment by wanglin727** [comment]
[keepwork-网站.zip](https://github.com/tatfook/wikicraft/files/1513224/keepwork-.zip)
