### ISSUE TITLE
【调整】网站收藏星标，调整成“大拇指”来表达点赞，喜欢的意思

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1065]
更符合当前的设计意图。
![image](https://user-images.githubusercontent.com/22001356/33367169-93d7d3ca-d528-11e7-8b98-3a39872cdb9d.png)

![image](https://user-images.githubusercontent.com/22001356/33367189-a24fcf98-d528-11e7-8fd3-332e0ebd8d85.png)
文字改成“喜欢”

**Comment by ZhangKaitlyn** [comment]
测试地址： http://fix1065.dev.keepwork.com/

**Comment by ExerciseBook** [comment]
我觉得 标星更git

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/33929233-b424e0a4-e023-11e7-88d9-bf080aedffb6.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/33932803-f16140b0-e02e-11e7-8153-097d2bc1e814.png)
![image](https://user-images.githubusercontent.com/28430070/33932820-fb2423ba-e02e-11e7-877e-3264063a9801.png)
修改图标，修改汉字

**Comment by ZhangKaitlyn** [comment]
测试环境： http://release1065.dev.keepwork.com/kaitlyn
