### ISSUE TITLE
【需求】国际化，内容翻译

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1067]
已经做了提取。
西峙安排时间翻译。

需要
poedit
 *.po file
的格式。
@yuanoook 转下。

**Comment by yuanoook** [comment]
[wikicraft.zip](https://github.com/tatfook/wikicraft/files/1520746/wikicraft.zip)

**Comment by yuanoook** [comment]
1.翻译机制已经加上，使用的是前端方案。
2.尝试翻译了大部分内容。
3.可能还有小部分没有覆盖到，后面持续补充。
4.翻译是用金山wps批量翻译的，可能词义需要修正，后面持续跟踪。
