### ISSUE TITLE
新建网站模版选择逻辑与美术

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#107]
![image](https://cloud.githubusercontent.com/assets/94537/24181521/5a207f68-0ef6-11e7-9b49-c0658a56876f.png)

选中的模版应该周围高亮， 点击图片任何位置都可以选择。 

1.【应用】按钮 的文字含义似乎有误解(和【下一步】有歧义)。 不应该是按钮。 应该为【已选中】的一个表示， 不是可点击按钮
2. 默认模版请用WIKI模版， 不是图书模版。 

@azothli

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24337894/d75e021c-12d3-11e7-8ab7-4bb6efd996f6.png)
已修改
