### ISSUE TITLE
【bug】新建网站后，使用全部保存功能，会出现文件内容被另外的文件进行覆盖的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1071]
## The problem
新建网站后，使用全部保存功能，会出现文件内容被另外的文件进行覆盖的情况

## Environment
OS Info: Window10
browser Info: chrome 
URL: [keepwork.com](https://keepwork.com)
Model: 页面编辑器 ->全部保存

## Step To Reproduce Issue [ Good To Have ]

**Pre-conditions:**
1.网络正常，可正常登陆
**Details:**
1.新建一个网站，选择空模版，新建网站成功后，在index 和_theme文件里分别添加不同的内容
2.选择全部保存按钮进行保存，保存成功后对网站内容进行查看
**Expected Result:**
1.网站内容信息显示正确
**Actual Result:**
1.网站内容信息显示有误，会出现_theme覆盖index内容或者index内容覆盖_theme内容的情况

**Comment by ZhangKaitlyn** [comment]
测试地址：http://10.27.3.7:8099/

**Comment by Sandu1213** [comment]
测试通过
