### ISSUE TITLE
【Bug】当编辑的文件既有有权限的文件又有无权限的临时文件时，进行全部保存，会导致全部保存失败，实现不合理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1083]
## The problem
当编辑的文件既有有权限的文件又有无权限的临时文件时，进行全部保存，会导致全部保存失败，实现不合理

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.94
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器->全部保存

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器页面，打开临时项目的文件进行编辑；
2.再打开自己创建的文件进行编辑；
3.点击"全部保存“按钮进行保存操作，观察保存结果

* Expected Result:
1.有权限的文件全部保存成功，无权限的文件保存失败并给出相应的提醒
* Actual Result:
1.文件都保存失败了
 

## Attachments (eg:logs/video/screenshot)

**Comment by ZhangKaitlyn** [comment]
测试环境： http://fix-695-1083.dev.keepwork.com/wiki/home
