### ISSUE TITLE
【Bug】对多个文件进行编辑操作，通过全部关闭按钮进行关闭，只需要弹窗提醒一次即可，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1084]
## The problem
对多个文件进行编辑操作，通过全部关闭按钮进行关闭，只需要弹窗提醒一次即可，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.94
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器->全部关闭

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，打开多个文件进行编辑操作，编辑完成后未保存时，点击”全部关闭“按钮，观察
结果

* Expected Result:
1.关闭失败，会弹窗提醒一次
* Actual Result:
1.关闭失败，但会弹窗多次
 

## Attachments (eg:logs/video/screenshot)

**Comment by leopoldchen** [comment]
Issue moved to [tatfook/keepwork #211](https://github.com/tatfook/keepwork/issues/211) via [**ZenHub**](https://www.zenhub.com/)
