### ISSUE TITLE
Tag系统

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#1093]
- [x] 查看已有逻辑
- [x] 将tag应用于页面，移除旧的网站tag（网站tag等同于index页面tag）
- [x] tag与markdown存储，tag信息应在markdown文件里也保存一份
- [ ] **elasticsearch中的tag信息存储与检索**

**Comment by leopoldchen** [comment]
个人首页允许加tag，这个tag为个人tag，如兴趣爱好等，与技能不同

**Comment by William0911** [comment]
除 “ elasticsearch中的tag信息存储与检索”   外其他需求已完成

**Comment by William0911** [comment]
网页相关的搜索已经做得差不多了，不知道站点和用户搜索应该做成什么样？ @azothli

**Comment by azothli** [comment]
用户搜索，是用来查找关键字相关的“用户”，需要匹配“账号名”，“昵称”，返回的格式可以使用个人首页中的用户展示方式

站点搜索，是用来查找关键字相关的“网站”，需要匹配“url”，“站点名称”，返回的格式可以使用个人首页中的站点展示方式

**Comment by William0911** [comment]
搜索用后端接口暂时已完成，与产品沟通结果：前端暂时不展示相关搜索内容

**Comment by William0911** [comment]
前端暂时不展示相关搜索内容，先关闭issue，要做的时候重开
