### ISSUE TITLE
个人Skill模块

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#1094]
- [x] 个人skill的增删改查，提供对应API
- [ ] 全局skill信息的查看检索（后续dashboard应该需要使用）
- [x] 根据创建的skill，推荐相关的页面。（搜索相似tag的page）
- [x] like列表，暂时先存于markdown文件中
- [x] 作品列表，也暂存于markdown文件中，单个技能只能最多绑定6个作品

**Comment by William0911** [comment]
除 “全局skill信息的查看检索” 外其他需求已完成

**Comment by William0911** [comment]
后端接口暂时已完成，与产品沟通结果：前端暂时不展示相关搜索内容

**Comment by William0911** [comment]
前端暂时不展示相关搜索内容，先关闭issue，要做的时候重开
