### ISSUE TITLE
【需求】【adi】代码编辑区调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1102]
对应预览区的选择，在代码区标记处对应的代码片段。
识别光标所在的位置对应着什么mod，然后在代码区标记处对应的代码片段。

**Comment by ZhangKaitlyn** [comment]
测试地址： http://10.27.3.7:8099/wiki/wikieditor#/kaitlyn/adi/index

**Comment by Sandu1213** [comment]
该功能已实现，但存在多个mod的时候，概率性会失效，待找到复现条件

**Comment by Sandu1213** [comment]
1.删除mod后页面显示不合理
![image](https://user-images.githubusercontent.com/21214285/34404769-87b7f89e-ebea-11e7-8222-3051bb27c9a1.png)
2.添加标题栏后无法进行编辑
![image](https://user-images.githubusercontent.com/21214285/34404822-d7c2c936-ebea-11e7-9e6f-47fed6428128.png)
3.mod组合编辑里的设置打开位置不可用
![image](https://user-images.githubusercontent.com/21214285/34405022-f410bb06-ebeb-11e7-9831-c64417776d87.png)
