### ISSUE TITLE
【需求】【adi】预览区域功能调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1103]
mod前后增加+号按钮来打开mod窗口，直接在该位置添加新的mod
mod，有选中状态，左侧浮动窗口：属性、样式、配置。右侧，复制、删除。

**Comment by ZhangKaitlyn** [comment]
测试地址： http://10.27.3.7:8099/wiki/wikieditor#/kaitlyn/adi/index

**Comment by Sandu1213** [comment]
@azothli  宇哥，mod窗口的‘配置’和‘复制’功能没有看到对应的设计？这个版本暂时不需要么？
另外，mod '+'的样式很丑，建议有一个更好的方案。
![image](https://user-images.githubusercontent.com/21214285/34244619-167d7750-e661-11e7-90d0-af45c129191d.png)

**Comment by Sandu1213** [comment]
目前左侧：‘’属性‘’、‘’样式‘’；右侧：‘’删除‘’
