### ISSUE TITLE
【需求】【adi】新增区域：属性窗

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1104]
在编辑区下面，显示mod的属性、样式、配置、系统操作等。
代码区、预览区，有mod被选中的时候，这里切换到对应mod的属性窗口。

知识引擎的相关内容以后可以在这里显示。

**Comment by ZhangKaitlyn** [comment]
测试地址： http://localhost:8099/wiki/wikieditor#/kaitlyn/adi/index

**Comment by Sandu1213** [comment]
mod的属性，样式已经看到。 配置和操作系统相关不需要
