### ISSUE TITLE
默认数据源名修改

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#1108]
之前默认数据源名为 内置gitlab，需要修改为 官方git数据源。旧用户的数据前端无法修改

**Comment by William0911** [comment]
脚本写好了，但在 #1000 有人在处理了

**Comment by Sandu1213** [comment]
该issue可以关闭了， #1000 上已经进行处理好了。

**Comment by Sandu1213** [comment]
该问题关闭，由 #1131 跟进
