### ISSUE TITLE
【Bug】默认首页的设置建议调整为可选择的形式

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1111]
## The problem
默认首页的设置建议调整为可选择的形式

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.94
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  网站管理->网站设置

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入网站管理->网站设置，对网站的默认首页进行修改设置
* Expected Result:
1.首页可以从已有的网页里进行选择
* Actual Result:
1.目前是手动输入的形式，后续会进行整体调整，该Issue暂用于记录。待后续再调整
 

## Attachments (eg:logs/video/screenshot)
![5](https://user-images.githubusercontent.com/21214285/33587722-5caa9be0-d9aa-11e7-8d00-52b3a4b498a4.png)

**Comment by azothli** [comment]
暂时搁置
