### ISSUE TITLE
【调整】编辑按钮可用性

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#113]
![image](https://cloud.githubusercontent.com/assets/22001356/24243672/dcc80174-0ff6-11e7-8572-1f460906cce7.png)
LiXizhi<lixizhi@yeah.net>  18:30:00
这里是否可以做成， 3个SVG Icon半透明， 按照百分比显示
Liyu(310984)  18:30:07
现在的编辑按钮太小不可点，再mouseover的时候u，做一个遮罩，然后浮现出大个的按钮吧
LiXizhi<lixizhi@yeah.net>  18:30:43
矢量图的那种。

**Comment by wxaxiaoyao** [comment]
已将此功能去掉， 模块视图编辑(和进入视图编辑)由模块编写者自行提供， 如：绘图模块，点击任意进入编辑
