### ISSUE TITLE
【Bug-大文件】上传大文件，关闭窗口强制退出时，大文件实际还在后台进行传输，需要调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1134]
## The problem
上传大文件，关闭窗口强制退出时，大文件实际还在后台进行传输，需要调整

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.94
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器->大文件窗口，选择大于10MB的文件进行上传，上传后立即关闭整个大文件窗口
2.关闭成功后，观察网络后台的情况

* Expected Result:
1.大文件终止传输，页面显示正确
* Actual Result:
1.大文件还在后台进行传输，需要调整

**Comment by ZhangKaitlyn** [comment]
测试地址： http://bigfile.dev.keepwork.com/wiki/wikieditor#/kaitlyn/bigfile/index

**Comment by Sandu1213** [comment]
bigfile环境测试通过
