### ISSUE TITLE
【Bug】页面编辑器里添加粘有图片的画板后，发现预览模式显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1163]
## The problem
页面编辑器里添加粘有图片的画板后，发现预览模式显示不合理，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.84
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择画板进行创作
2.粘贴2副图片后，观察预览区的显示情况

* Expected Result:
1.预览区信息显示正确
* Actual Result:
1.预览区信息显示不合理，请优化
 

## Attachments (eg:logs/video/screenshot)
![8](https://user-images.githubusercontent.com/21214285/33993030-d5c92142-e10f-11e7-8903-bc6cd19a7946.png)

**Comment by onedou** [comment]
这个是否是浏览器的问题？做一个限制

**Comment by onedou** [comment]
建议不显示这个alert，或者优化逻辑 @wxaxiaoyao
