### ISSUE TITLE
【Bug】账号登陆成功后需要根据情况对页面进行刷新操作

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1168]
## The problem
账号登陆成功后需要根据情况对页面进行刷新操作

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.84
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  账号登陆

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.查看有编辑权限的私有网站，未登录时进行查看，登陆成功后再进行查看；
2.查看比赛或者组织网站，未登录时进行查看，登陆成功后再进行查看

* Expected Result:  
1.登陆成功后，页面会自动刷新，浏览成功；
2.登陆成功后，页面会自动刷新，可以申请加入组织或者提交作品。
* Actual Result:
1.登陆成功后的页面与未登录时的页面显示一样，需要增加自动刷新功能
2.同上

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1168.stage.keepwork.com/
