### ISSUE TITLE
【调整】菜单栏调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#117]
![image](https://cloud.githubusercontent.com/assets/22001356/24278441/cdf1ead8-107e-11e7-9e34-b663414068a6.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24282635/bf2cd996-109b-11e7-8858-ba4bb7565b65.png)
yi已调整
