### ISSUE TITLE
ADI编辑器改版 > MOD 图形图像

### ISSUE THREAD

**Issue by yuanoook** [tatfook/wikicraft#1171]
http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9Amod%EF%BC%9A%E5%9B%BE%E5%BD%A2%E5%9B%BE%E5%83%8F

**Comment by Sandu1213** [comment]
待张郭璐提供入口后再进行测试。
