### ISSUE TITLE
mod：标题

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1172]
![image](https://user-images.githubusercontent.com/3422640/34096886-f7c4097e-e411-11e7-99cc-dbf380a6bb27.png)
![image](https://user-images.githubusercontent.com/3422640/34096890-fa247ffa-e411-11e7-9b2b-c494c3686db0.png)

**Comment by onedou** [comment]
测试地址 http://title_mod.dev.keepwork.com/

**Comment by Sandu1213** [comment]
- 开关控制无效 
![image](https://user-images.githubusercontent.com/21214285/34282667-485c7cf2-e702-11e7-9862-ec125a0e43aa.png)

- 存在链接也无法点击
![image](https://user-images.githubusercontent.com/21214285/34282713-93b9a760-e702-11e7-981b-215474ecbafd.png)

**Comment by onedou** [comment]
https://github.com/tatfook/wikicraft/commit/beb1f38a3131115307444e2d88b41f69a72f5d56

测试地址：http://title_mod.dev.keepwork.com
这个是text类型，文字是否需要链接，请问是否确定了？

**Comment by Sandu1213** [comment]
1.预览区看不到任何东西
![image](https://user-images.githubusercontent.com/21214285/34405570-12973656-ebef-11e7-84fe-70a77da05630.png)
2.文字需要链接

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/34703665-22639b26-f52f-11e7-9555-79748611d932.png)

**Comment by Sandu1213** [comment]
验证通过
