### ISSUE TITLE
mod:图文混排

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1173]
已做好逻辑，等待设计图

**Comment by onedou** [comment]
http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9A%E5%9B%BE%E6%96%87%E6%B7%B7%E6%8E%92

**Comment by onedou** [comment]
测试地址：http://picture-text.dev.keepwork.com

     ```@adi/js/pictureText
     ```

**Comment by Sandu1213** [comment]
![qq 20171228143553](https://user-images.githubusercontent.com/21214285/34402808-251226e8-ebdf-11e7-8d83-a8a3cdd8c320.png)
![8](https://user-images.githubusercontent.com/21214285/34402836-57c765b2-ebdf-11e7-9f7d-d4a3da200269.png)

**Comment by Sandu1213** [comment]
不应该有这么多的弹窗
![image](https://user-images.githubusercontent.com/21214285/34403303-748ef31a-ebe2-11e7-966c-291ce02f098c.png)
![image](https://user-images.githubusercontent.com/21214285/34403437-3584ec3c-ebe3-11e7-9dac-23b251c71a70.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34658426-0434b75e-f46a-11e7-84b2-e7d728b3ad73.png)

@yq33z3069

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34712814-2601f068-f55f-11e7-9b58-5cd804e0e222.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34804200-40efa98e-f6b2-11e7-81a7-ca91e6d84c2c.png)

**Comment by onedou** [comment]
overflow y srcoll
