### ISSUE TITLE
mod：导航菜单

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1174]
![image](https://user-images.githubusercontent.com/3422640/34097041-91e7b5e6-e412-11e7-8b41-31661f6910bd.png)

**Comment by onedou** [comment]
是否有菜单类型？ @yuanoook

**Comment by onedou** [comment]
http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9A%E8%8F%9C%E5%8D%95

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34146159-d17eee60-e4d3-11e7-8e68-2d2615df3d09.png)

测试地址 http://menu-mod.dev.keepwork.com/wiki/wikieditor

**Comment by onedou** [comment]
@Sandu1213

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34197240-8408537e-e5a0-11e7-8188-1a0bcc954812.png)

**Comment by onedou** [comment]
2.子菜单看不到的问题。

父容器设置了overflow: auto，导致一些列表被遮挡

建议：
1.对父容器进行min-height的css设置
2.取消overflow: auto css设置

@ZhangKaitlyn

**Comment by onedou** [comment]
测试地址 http://menu-mod.dev.keepwork.com/wiki/wikieditor

![image](https://user-images.githubusercontent.com/3422640/34336386-b1cda788-e991-11e7-8d80-0aa9b11dab53.png)

**Comment by duting1993** [comment]
测试地址：menu-mod.dev.keepwork.com

**Comment by onedou** [comment]
测试指令

    ```@adi/js/menu
    ```

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34405836-73b209c4-ebf0-11e7-8977-005cc24b57bf.png)

**Comment by onedou** [comment]
js 中的默认值不能显示

**Comment by Sandu1213** [comment]
bug: #1242  #1267 #1263 #1266 
待修改完毕后再验证

**Comment by Sandu1213** [comment]
待menu相关bug解决了请再移交测试，谢谢

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34761150-89116c92-f61d-11e7-8ddf-69769c9cd719.png)
