### ISSUE TITLE
页面属性制作

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1175]
![image](https://user-images.githubusercontent.com/3422640/34097222-50c5ba9e-e413-11e7-9eef-f8d964532f96.png)
![image](https://user-images.githubusercontent.com/3422640/34097229-55d0c6a0-e413-11e7-836c-723bb3140179.png)
![image](https://user-images.githubusercontent.com/3422640/34097231-58ac525e-e413-11e7-9ca5-c82b70826059.png)

**Comment by onedou** [comment]
参考 http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9A%E5%9F%BA%E7%A1%80%E5%8D%95%E5%85%83

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.adi.stage.keepwork.com，功能bug @wxaxiaoyao ,界面展示bug @zhangKaitlyn

**Comment by Sandu1213** [comment]
与 #939 相关联，暂时只能看到3个属性。建议该功能放到下一个版本里。
![image](https://user-images.githubusercontent.com/21214285/34753471-17ae5a76-f5f3-11e7-9fb1-43762a93e43d.png)

**Comment by Sandu1213** [comment]
与产品沟通过了，目前不按该方案实现了，该issue可关闭。
