### ISSUE TITLE
mod：Paracraft作品

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1178]
http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9Aparacraft

**Comment by onedou** [comment]
需传递token到paracraft

**Comment by onedou** [comment]
设计图好了吗？

**Comment by onedou** [comment]
使用旧的板式即可

**Comment by Sandu1213** [comment]
logo无法设置，待调整后再验证
