### ISSUE TITLE
mod11：NPL CAD模型

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#1179]
http://keepwork.com/keepwork/pwiki/pm/ADI%E7%BC%96%E8%BE%91%E5%99%A8%E6%94%B9%E7%89%88/mod%EF%BC%9Anplcad

**Comment by azothli** [comment]
在线显示NPL CAD生成的3D模型

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #494](https://github.com/tatfook/keepwork/issues/494) via [**ZenHub**](https://www.zenhub.com/)
