### ISSUE TITLE
独立域名的显示逻辑不对

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#118]
![image](https://cloud.githubusercontent.com/assets/94537/24278460/f15dc50a-107e-11e7-9223-72a9d515bd43.png)

@azothli 

可以暂时去掉这个栏目， 未来是CName转发。 

另外， 美术上，我建立这里采用多行显示的方式， 参考github.

![image](https://cloud.githubusercontent.com/assets/94537/24278539/5e596cf4-107f-11e7-8a3f-d683c6dfd2ba.png)

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/24278649/fe873abc-107f-11e7-8d43-321c32fd49f6.png)
 直接改成CNAME吧

**Comment by wxaxiaoyao** [comment]
暂时隐藏该字段

**Comment by azothli** [comment]
4月cname功能上线要重新做调整，这个别close，我放4月
