### ISSUE TITLE
【需求】adi编辑区，下面属性窗，显示规则调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1191]
新增下拉选单，控制adi属性区显示
![image](https://user-images.githubusercontent.com/22001356/34337260-f79b7f9a-e998-11e7-827b-ab8c02d24c5b.png)
一直打开：显示完整模式
一直关闭：显示tab部分
智能模式：在选中mod的时候，显示完整模式，其余时间显示tab部分。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35023568-36e76814-fb76-11e7-97da-90eaf22d27e0.png)

**Comment by wanglin727** [comment]
设计已完成   转开发

**Comment by Sandu1213** [comment]
目前已增加Agent功能。
