### ISSUE TITLE
【需求】编辑器，对文件的编辑权限、属性进行更加直观的显示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1192]
可以考虑对adi属性窗的tab条做着色
只读    灰色
编辑公有    蓝色
编辑私有     橘黄

参考 vs的效果
![image](https://user-images.githubusercontent.com/22001356/34337578-74de4576-e99b-11e7-956f-c1b041f261d3.png)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/34661355-0fdb7da8-f484-11e7-993a-dc085df3179a.png)

**Comment by wanglin727** [comment]
设计稿完成  待开发
