### ISSUE TITLE
【需求】编辑器预览窗 支持 对框架的布局进行显示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1194]
对于有复杂结构的框架布局，现在是不进行任何显示，造成用户感受不直观。
我么人需要在预览中，对框架边界做虚线显示，方便用户理解。

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/37022027-9caf9034-215c-11e8-9164-2134b0480db8.png)
