### ISSUE TITLE
【Bug-手机版】手机上无法对编辑的文件进行切换操作，请优先处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1206]
## The problem
手机上无法对编辑的文件进行切换操作，请优先处理

## Environment

* OS Info: Iphone 10.3.3
* browser Info: chrome   63.0.3239.108
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器，选中文件对文件进行编辑
2.编辑完了切换到另外一个文件进行编辑

* Expected Result:
1.可以正常切换到其他的文件
* Actual Result:
1.切换失败，请排查
 

## Attachments (eg:logs/video/screenshot)

**Comment by ZhangKaitlyn** [comment]
Issue moved to [tatfook/keepwork #2434](https://github.com/tatfook/keepwork/issues/2434) via [**ZenHub**](https://www.zenhub.com/)
