### ISSUE TITLE
【需求】mod：宽屏图像

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1210]

**Comment by onedou** [comment]
设计需求

**Comment by azothli** [comment]
@wanglin727

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/34660925-01ef6162-f481-11e7-876e-4be0d37f4cf0.png)

**Comment by Sandu1213** [comment]
宽屏图片在新页面打开，展示不对，需要平铺展示，具体按照产品的定义来。

**Comment by Sandu1213** [comment]
![img](https://user-images.githubusercontent.com/21214285/34811095-1a1a05de-f6da-11e7-988f-d19750a5ab4e.png)
![img123](https://user-images.githubusercontent.com/21214285/34811102-20b41664-f6da-11e7-96b5-74a20a2f6931.png)
