### ISSUE TITLE
【调整】top条布局与对齐方式

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#123]
![image](https://cloud.githubusercontent.com/assets/22001356/24280783/66582242-108e-11e7-8af9-2ae4f7752ad8.png)

**Comment by Tibet0312** [comment]
![juvy p81_z 81y_7ef81ib0](https://cloud.githubusercontent.com/assets/25898720/24289023/7beb8406-10ba-11e7-90d4-95d81d13201b.png)


已调整

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24337864/94dd3b7e-12d3-11e7-889e-085bb0d32b33.png)
已调整
