### ISSUE TITLE
【Bug-ADI】属性设置里的开关会产生错误的代码块，请优先处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1234]
## The problem
属性设置里的开关会产生错误的代码块，请优先处理

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://feature.adi.stage.keepwork.com](http://feature.adi.stage.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问feature.adi.stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择图文混排的mod进行设置
2.不断调整图片开关，观察代码区和显示效果

* Expected Result:
1.代码显示正确，只影响是否显示的属性，图片显示正确
* Actual Result:
1.会自动多增加代码，且切换时会出现图片不显示的问题

**Comment by Sandu1213** [comment]
![picturetext](https://user-images.githubusercontent.com/21214285/34660593-7b06c62e-f47e-11e7-8974-cc76b5ed3cdb.gif)

**Comment by wxaxiaoyao** [comment]
已改 @Sandu1213
