### ISSUE TITLE
【Bug-ADI】对图文混排里的富文本进行编辑时，会出现换行内容不能显示且多次保存后会重复追加的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1235]
## The problem
对图文混排里的富文本进行编辑时，会出现换行内容不能显示且多次保存后会重复追加的情况

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://feature.adi.stage.keepwork.com](http://feature.adi.stage.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问feature.adi.stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择图文混排的mod进行设置
2.选中文字说明里的富文本进行编辑，输入多行内容，观察代码区保存结果和预览区效果
3.多次保存，观察显示情况

* Expected Result:
1.代码显示正确，预览效果合理
* Actual Result:
1.会重复追加已输入的内容，且出现已换行的内容不能显示的问题

**Comment by Sandu1213** [comment]
![mulitetext](https://user-images.githubusercontent.com/21214285/34660731-99b6e88c-f47f-11e7-929a-207978f60643.gif)

**Comment by wxaxiaoyao** [comment]
已修复 @Sandu1213

**Comment by Sandu1213** [comment]
最新的环境无法验证，添加图文混排，预览区无法显示去，请优先处理，处理后再进行回归 @wxaxiaoyao

**Comment by Sandu1213** [comment]
换行问题依然存在

**Comment by Sandu1213** [comment]
换行内容可以显示，但显示的样式还是不对，请再调整

**Comment by Sandu1213** [comment]
图文混排的mod里，输入多行会出现显示不全的问题

**Comment by Sandu1213** [comment]
验证通过
