### ISSUE TITLE
【bug-adi】图文混排模块文字说明，显示问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1243]
操作步骤：
1.添加模块图文混排
2.样式中文字说明显示问题 ，如图1
3.点开文本，显示一些& nbsp;& nbsp;& nbsp;& nbsp;等，如图2
![image](https://user-images.githubusercontent.com/28430070/34662291-831410ae-f48a-11e7-8a29-54e80b9d82b8.png)
![image](https://user-images.githubusercontent.com/28430070/34662351-edb7e674-f48a-11e7-9b80-f1a3c2ab8b99.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://10.27.3.7:8099
