### ISSUE TITLE
【bug-adi】添加模块文本，保存，打开该网站，点击文字，会出现加号+

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1268]
操作步骤：
1.编辑器添加模板文本，保存
2.点击该网站链接
3.点击文字
实际结果：
会出现+号，如图2
![image](https://user-images.githubusercontent.com/28430070/34708827-83910eea-f54f-11e7-9312-bbb02a31796e.png)

![image](https://user-images.githubusercontent.com/28430070/34708792-637cc2a2-f54f-11e7-974b-177d729dc518.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.view.addicon.stage.keepwork.com
