### ISSUE TITLE
【Bug-ADI】对属性栏里的值进行开关设置时，mod添加按钮应该居中不变，目前是不断变动

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1269]
## The problem
对属性栏里的值进行开关设置时，mod添加按钮应该居中不变，目前是不断变动

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://feature.adi.stage.keepwork.com](http://feature.adi.stage.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问feature.adi.stage.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择任一个mod进行添加（例如：图文混排）
2.添加后，到属性栏对选中的属性进行开关设置，切换开关，观察添加mod按钮的变化

* Expected Result:
1.mod添加按钮居中不变
* Actual Result:
1.mod添加按钮会左右移动
 

## Attachments (eg:logs/video/screenshot)
![addbtnlocated.gif](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e5e0e415-2163-49de-88a8-e9bfa6e4d90c)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.view.addicon.stage.keepwork.com

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34758661-a1b92bc8-f612-11e7-9835-45e4f5dc4ebe.png)
