### ISSUE TITLE
【Bug-ADI】添加多个title mod,操作属性开关，会出现属性栏整体被关闭的的情况，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1281]
## The problem
添加多个title mod,操作属性开关，会出现属性栏整体被关闭的的情况，请排查

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择标题的mod进行设置
2.添加多个mod，选中其中一个进行操作，关闭属性值时，观察代码区和预览区的变化效果

* Expected Result:
1.代码区与预览区的效果变化正确
* Actual Result:
1.属性栏直接消失了，实现不合理，请排查
 

## Attachments (eg:logs/video/screenshot)
![improtant.gif](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/0f183e58-9604-40ab-acbf-3ca39629cd3a)

**Comment by ZhangKaitlyn** [comment]
测试环境: http://fix.show.type.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix.show环境验证通过。
