### ISSUE TITLE
【Bug-ADI】设置链接打开位置的窗口，字体颜色需要调整，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1286]
## The problem
设置链接打开位置的窗口，字体颜色需要调整，请优化

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择title或者图文混排的mod
2.对有链接的属性进行设置，观察链接打开窗口的显示情况

* Expected Result:
1.字体显示明显，很方便用户操作
* Actual Result:
1.字体显示偏暗，不方便操作

**Comment by Sandu1213** [comment]
![newwindow](https://user-images.githubusercontent.com/21214285/34714653-12d58c38-f565-11e7-8be5-15fb427d815d.png)

**Comment by ZhangKaitlyn** [comment]
测试环境：http://fix.adi.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix环境验证通过
