### ISSUE TITLE
Ctrl+Z在切换网页后出错

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#130]
![image](https://cloud.githubusercontent.com/assets/94537/24328453/cef1411e-121c-11e7-847d-03c60b14ea78.png)

Ctrl+Z在切换网页后，会将之前网页的内容导入。 

文本编辑器的状态需要reset., 或记录多个State。 
- 如果是reset则应该在切换页面时提示用户保存。  （这个是最直接简单的方案）
- 如果是多个Editing context, 则需要做context switch. (这个是最高级的方案)

**Comment by wxaxiaoyao** [comment]
多文件多文档实现，每个文件有自己的context
