### ISSUE TITLE
【优化】绘图mod

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#131]
非登录状态下，点击绘图，会直接进入编辑状态，存盘按钮也是激活的。
可是点击后没任何反应。
此处可考虑：
1.非作者不能打开编辑（权限控制）
2.允许编辑的话，提示另存（提示用户会保存在自己的网站、绘画中，未登陆先提示登陆）

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/24339548/f7a0d5e4-12de-11e7-905e-eb371fd258a6.png)

**Comment by leopoldchen** [comment]
#680 这两个issue应该是相关的，我们会采用新的绘图插件，旧的应该会直接废弃
