### ISSUE TITLE
【Bug-ADI】使用文本或者图文混排mod的富文本编辑器后，再去添加新的mod，无法在预览区看到，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1313]
## The problem
使用文本或者图文混排mod的富文本编辑器后，再去添加新的mod，无法在预览区看到，请排查

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择文本或者图文混排mod，对文本内容进行编辑
2.编辑完成后，再去添加新的mod，观察添加后的效果

* Expected Result:
1.添加成功，mod可以正常展示使用
* Actual Result:
1.添加的mod在预览区无法查看，console报错
 

## Attachments (eg:logs/video/screenshot)

  ![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/3fb74c4c-264a-49b8-9e70-f797b65f07bc)

**Comment by ZhangKaitlyn** [comment]
测试环境：http://fix.multitext.noview.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix环境验证通过
