### ISSUE TITLE
【Bug-ADI】文本mod里文字说明的链接不可用，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1316]
## The problem
文本mod里文字说明的链接不可用，请排查

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择文本mod，对文本内容进行编辑
2.编辑完成后，配置对应的链接，保存成功后，在新的页面进行访问，观察链接是否可以正常打开

* Expected Result:
1.添加成功，链接在合适的窗口打开正确
* Actual Result:
1.添加成功，标题链接正常，文字说明的链接不能进行跳转
 

## Attachments (eg:logs/video/screenshot)

![textUrl.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/2f2dd0f5-cb4d-46c6-a3ba-696058fc0e70)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34761184-ab34e452-f61d-11e7-9af7-fe5887d2090b.png)

**Comment by onedou** [comment]
程序员测试没有问题，请测试

**Comment by Sandu1213** [comment]
测试通过
