### ISSUE TITLE
【Bug-ADI】文本和图文混排mod里的多行输入需要支持markdown语法

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1317]
## The problem
文本和图文混排mod里的多行输入需要支持markdown语法

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择文本或者图文混排mod，对文本内容进行编辑
2.输入markdown语法的文字，观察保存结果

* Expected Result:
1.输入成功，保存成功，展示合理
* Actual Result:
1.保存失败，直接恢复成默认值了
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/38f139e9-c5d4-4f79-bd9f-34ccbb54a99d)

**Comment by Sandu1213** [comment]
经验证，目前还是不支持markdown，请开发再确认。

**Comment by Sandu1213** [comment]
o(╯□╰)o， 还是不行，确定支持**markdown**语法了？

**Comment by onedou** [comment]
好像支持啊，除了```

**Comment by Sandu1213** [comment]
目前支持markdown语法了，但仅限于 **粗体** (\*\*x**), *斜体*（\*X\*）,引用（\>）;
其他的不支持。（如：链接，有序列表，无序列表，---，代码块等）
