### ISSUE TITLE
【优化】优化登陆体验

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#132]
![image](https://cloud.githubusercontent.com/assets/22001356/24341301/58ddb26c-12eb-11e7-8188-a1d801ef8305.png)
在注册框
输入账号后，自动对比是否有该账号。
如果有的话，自动的将下面的 【注册】按钮调整为【登陆】
同时灰掉个人网站名

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24441536/8979c6a2-148c-11e7-83fa-b48bebce7ff4.png)
已优化
