### ISSUE TITLE
【调整】编辑器url短路径调整为长路径

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#134]
编辑器url短路径调整为长路径

**Comment by wxaxiaoyao** [comment]
图片改用完整url，  好处 1 实现简单不易出错，短路径实现复杂且极易出错  2 切数据源图片扔可用(短路径在切换数据源后，图片基本是不可用的，因短路径时需动态解析数据源相关信息，更改后之前数据源信息不可获取故不可用)
