### ISSUE TITLE
【bug】动态、历史等显示的内容头像，应该是对方的头像

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#135]
动态、历史等显示的内容头像，应该是对方的头像

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24853670/6b641e3e-1e0e-11e7-998d-ce44c103fc3a.png)
![image](https://cloud.githubusercontent.com/assets/18642919/24853681/73ccc0a8-1e0e-11e7-9379-e1c60736a8fe.png)
已改
