### ISSUE TITLE
【Bug-ADI】添加layout mod 后，对属性值进行修改，无法进行修改，请排查 （非必现）

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1352]
## The problem
添加layout mod 后，对属性值进行修改，无法进行修改，请排查

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择layout mod
2.添加后，选择style3或者style4，对属性值进行设置，观察设置结果

* Expected Result:
1.设置成功，样式显示正确
* Actual Result:
1.设置失败，无法进行输入
 

## Attachments (eg:logs/video/screenshot)
![layoutitems.gif](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/40cc6c07-34e2-4ce9-a292-65f1485ec927)

**Comment by yuanoook** [comment]
数据同步问题，现在编辑页面，更新的时候会狂闪，需要把底层逻辑重写，到时候一起处理。

**Comment by yuanoook** [comment]
前面更新数据同步问题，这个应该已经好了，你看一下
