### ISSUE TITLE
【需求】多行文本编辑器是否需要支持全部的markdown语法

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1360]
# Description
记录  #1317 遗留的问题  （如果需要，请排计划优化；如果不需要，该issue可以直接关闭）

![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/63a5e7e2-2676-4e3d-9373-d7d072a43ebc)

**Comment by Sandu1213** [comment]
还需要支持的markdown语法有：
- 删除线   ~~删除线~~  
- 分割线 
---
- 有序列表
1.AAA
2.BBB

- 无序列表
+ List
  - item
- 选择框
- [ ] 未选中
- [x] 选中

- 表格
| 日期| 工作内容 | 
| -- | -- | 
|2.9 |1.xxx|

- 图标
![image](http://keepwork.com/wiki/assets/imgs/icon/logo.svg)

**Comment by leopoldchen** [comment]
后续应该会添加一个新的component来解决markdown输入框问题，该component可以被整合到各种mod中。 此处的markdown语法支持肯定有限制，比如不支持MOD扩展等。具体需要等产品这边决定。
@azothli
