### ISSUE TITLE
【bug】编辑器 ctrl+z的问题

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#138]
编辑器 ctrl+z的问题，浏览器的后退正常，ctrlz不正常

**Comment by wxaxiaoyao** [comment]
浏览器回退跟刷新是一样的效果， 重新载入后编辑context会丢失，且context无法本地保存没法改。。。

**Comment by wxaxiaoyao** [comment]
此问题无解， 回退和刷新不能维护之前的编辑历史。也没必要实现此功能，毕竟是在线编辑，而且还是用编辑库实现。
