### ISSUE TITLE
【bug】无法上传大文件

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1383]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/ea6b73cd-c6eb-46fc-8f06-953012ee278c)
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/d205981d-398e-4560-86b2-d8f97ad740d3)

**Comment by Sandu1213** [comment]
目前keepwork可以正常上传
