### ISSUE TITLE
【Bug-ADI】paracraft mod选择样式1的时候，所有属性都关闭了，还是无法隐藏mod，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1389]
## The problem
paracraft mod选择样式1的时候，所有属性都关闭了，还是无法隐藏mod，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.108
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择 paracraft mod
2.选中默认样式，然后将属性都关闭，观察mod是否可以正常隐藏

* Expected Result:
1.mod可以正常隐藏
* Actual Result:
1.mod无法完全隐藏
 

## Attachments (eg:logs/video/screenshot)
![paracraft_item2.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/55cd26f4-60bf-4318-b5c9-f360a79f12f6)

**Comment by onedou** [comment]
http://release.keepwork.com

**Comment by Sandu1213** [comment]
release环境验证通过
