### ISSUE TITLE
【调整】mod：图文混排 调整为 图文拼接

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1396]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/457ebc5e-41db-4fa5-8bb3-c1e55ae3f3e5)

**Comment by Sandu1213** [comment]
release环境验证不过，请调整
![image](https://user-images.githubusercontent.com/21214285/34968574-e91f08ac-faa4-11e7-808d-ed0a0fc4530c.png)

**Comment by Sandu1213** [comment]
@azothli 宇哥，这个描述能否调整下？一眼看过去，不是很明白。（可调整为：”常用的图文拼接样式“，如何？）
![image](https://user-images.githubusercontent.com/21214285/34968624-37e8029a-faa5-11e7-9937-e7a1780a0424.png)

**Comment by Sandu1213** [comment]
big,你调整模块添加那里了么？我这边看到的效果还是不对的。

**Comment by azothli** [comment]
常用的图文拼接样式。

好的，这个更清楚。

**Comment by Sandu1213** [comment]
@onedou  Big，请调整下，谢谢，具体如下：
1, 模块里的“图文混排”改为“图文拼接”；
2.描述语调整，调整为：“常用的图文拼接样式”。

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/35073648-e90649d0-fc24-11e7-9cff-f67910cb0de3.png)

**Comment by onedou** [comment]
已改，只是数据库修改，请直接在keepwork.com查看

**Comment by Sandu1213** [comment]
keepwork 上验证通过
