### ISSUE TITLE
mod15： 图片轮播

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1401]
15 图片轮播
	添加多个图片的交替显示。
	img_loop

这个mod由5个图片模块组成（用户可以设置，可以关闭）
系统按照我们图片轮播的机制展示其中的内容（原来的轮播模块）
@wanglin727

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35031984-2cb4808c-fba0-11e7-87a0-dd7a4733807b.png)
   


设计图已完成     转开发

**Comment by Sandu1213** [comment]
@big  请补充入口，谢谢

**Comment by Sandu1213** [comment]
问题1：隐藏相关图片，隐藏不生效
![image](https://user-images.githubusercontent.com/21214285/35261640-24e9f0de-004c-11e8-9d2f-77c4a01375e6.png)

问题2：添加2个轮播图后，对其中一个进行修改，隐藏3幅图片，会发现右侧预览区的“+”按钮位置不对，请调整
![loop](https://user-images.githubusercontent.com/21214285/35261967-7ae0df10-004d-11e8-833b-0dc9df94d3f4.gif)

**Comment by Sandu1213** [comment]
问题3：目前的轮播，轮播间隔都是3秒，固定死了，无处设置，是否放开可以在属性栏配置（分为1s/3s/5s这种）
@azothli 宇哥，这个请回复下

**Comment by onedou** [comment]
已改3s

**Comment by Sandu1213** [comment]
问题1：模块介绍说明不对
![image](https://user-images.githubusercontent.com/21214285/35318813-fbf3f158-0117-11e8-8564-dde6f07a1061.png)

问题2：图片没有按照对应的等比进行缩放，失真较高，显示不合理
![image](https://user-images.githubusercontent.com/21214285/35318839-1bd6da58-0118-11e8-82a2-7e6c7f5f7153.png)

问题3：样式效果与设计稿不一致
![image](https://user-images.githubusercontent.com/21214285/35318886-63992d78-0118-11e8-9dad-48525e89e10b.png)

**Comment by Sandu1213** [comment]
补充：之前提到的“+”位置不对的问题依然存在
![addbtn](https://user-images.githubusercontent.com/21214285/35319026-00e2e92a-0119-11e8-9688-992e76b7394e.gif)
