### ISSUE TITLE
mod16 ：图文叠加

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1402]
16 图文叠加
	常用的图文混合介绍方式。
	mix_layer

![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/529ccf93-6700-4329-a2b8-6dc4e83232b8)

@wanglin727

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35039809-f4e4742c-fbb9-11e7-87c0-63569e2410bf.png)

设计已完成    转开发

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/35260936-e57c8d60-0048-11e8-9c7a-fde04a728b20.png)
空白处过大

**Comment by Sandu1213** [comment]
问题1：关闭图片后，应该是关闭了背景图片，默认显示白色即可，文字还是应该正常显示的（目前关闭后整个mod都关闭了）
![image](https://user-images.githubusercontent.com/21214285/35320316-4f083196-011e-11e8-8b32-694dc596b92c.png)

问题2：样式5的效果与样式8的效果一样了，是需要文字居中的。请调整（样式8 是文字居下）

**Comment by Sandu1213** [comment]
1.样式问题：
![image](https://user-images.githubusercontent.com/21214285/35365885-bae8e5de-01b1-11e8-8dc4-6eef2f6a47fc.png)
![image](https://user-images.githubusercontent.com/21214285/35365920-d18edd20-01b1-11e8-969a-999501a338f0.png)
![image](https://user-images.githubusercontent.com/21214285/35365950-ed100f10-01b1-11e8-9c33-f6cbc3101ca7.png)

2.操作体验问题:
操作：添加了3个图文叠加，选中最后一个进行操作，每次修改标题或者正文内容或者开关时，右侧的预览区，总是会从新定位到第一个图文，建议优化

**Comment by Sandu1213** [comment]
图文叠加样式问题调整好了请告知一下

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/35394212-0fb89eae-0222-11e8-842c-033e5330bdf4.png)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/35394222-1e23c216-0222-11e8-92e6-9de88b8afc1a.png)
