### ISSUE TITLE
【需求】mod 图文拼接样式        上文下图    上图下文 2款

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1403]
已有左右布局，添加上下布局
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/139629a5-57f7-4fc5-b011-11d3a7be3519)

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35087281-a5438578-fc6a-11e7-8dc7-942ec5cb8d42.png)


设计已完成     转开发

**Comment by Sandu1213** [comment]
问题1：属性栏的左右按钮无法进行切换
![image](https://user-images.githubusercontent.com/21214285/35256659-d6a3c81c-002f-11e8-8545-b95e56972555.png)

问题2：样式显示不合理
![image](https://user-images.githubusercontent.com/21214285/35256794-8933902a-0030-11e8-9f41-21ae47a030e8.png)

问题3：
![image](https://user-images.githubusercontent.com/21214285/35256935-6d3a0f60-0031-11e8-9e46-da74d3b83b7d.png)
