### ISSUE TITLE
个人成长：网站设置调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1405]
网站设置调整
	站点设置中，去除tag的设定功能
		转到页面的tag编辑器中
	新增 网站的“关注者” tab
		数据现在是混在个人粉丝里面

**Comment by azothli** [comment]
在粉丝中，现在只是显示了站点的关注者，没有显示用户的关注者，需要加上
@ZhangKaitlyn

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1405.stage.keepwork.com
