### ISSUE TITLE
【调整】：全站调整  top栏调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1407]
![image](https://user-images.githubusercontent.com/22001356/34931581-75b6ab26-fa0a-11e7-8d7b-7b5b7f98ebc9.png)

![image](https://user-images.githubusercontent.com/22001356/34931572-68731044-fa0a-11e7-8082-bb77081cf04a.png)

http://keepwork.com/keepwork/pwiki/pm/user_home/desgin

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/34935025-6746bc0e-fa17-11e7-8af7-fce1cd9a7dca.png)

**Comment by Sandu1213** [comment]
功能已实现，小问题以issue单的形式跟进
