### ISSUE TITLE
系统数据：tag 与 技能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1410]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ef7a2ba7-56b0-429f-be81-3ea6d7eb5171)

**Comment by leopoldchen** [comment]
Issue moved to [tatfook/keepwork #203](https://github.com/tatfook/keepwork/issues/203) via [**ZenHub**](https://www.zenhub.com/)
