### ISSUE TITLE
mod：编号21 	文本与绘图板 	text_board

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1420]
![image](https://user-images.githubusercontent.com/22001356/35023368-4a3db554-fb75-11e7-906d-1413d38785b9.png)

编号21
	文本与绘图板
		绘图板
		文本
	text_board
	样式
		样式1
			左文，右图
		样式2
			右文，左图
		样式3
			上文，下图
		样式4
			下文，上图

**Comment by azothli** [comment]
说明
	带文字说明的绘图板

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35837749-d77790ea-0b22-11e8-9226-e0ddc895e016.png)


设计图已完成  待开发

**Comment by duting1993** [comment]
stage已验证

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #558](https://github.com/tatfook/keepwork/issues/558) via [**ZenHub**](https://www.zenhub.com/)
