### ISSUE TITLE
【需求】点击编辑，尝试编辑别人的页面

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#144]
在编辑器中打开对应页面，treeview中增加一个临时的文件，加一个锁头的小图标，代表只读。
只能看看。

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/24442202/99dd9a7a-148f-11e7-9a28-fa83e755412d.png)

**Comment by wxaxiaoyao** [comment]
已做编辑他人页面演示， 具体样式待设计， UI，前端完善， 此bug先关了
