### ISSUE TITLE
【需求】mod列表支持顺序自定义

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1442]
mod列表中当前是按照mod id进行排序
例如：
分类1：1,2,3,4
需要增加可以调整顺序的方法，可以实现
分类1：1,2,4,3
注意，需要支持一个mod在不同分类中的不同顺序
例如：
分类1：1,2,4,3
分类2：2,1,3

**Comment by yuanoook** [comment]
需要对数据库中的 wiki_module 数据进行调整，调整规则如下
-1 增加 sortIndex 字段，表示在全部、收藏 下面的排序，默认值是模块的标签
-2 调整 classifyName 字段，子分类添加 !n 排序权重标识，可选，表示分类里面的排序标准

``` javascript
{
     "sortIndex": 1,  //default == _id
     "classifyName": "一级类目>子分类!14:其他类目>子分类" //!后面的14表示在类目下的排序
}
```

例子
``` json
{
        "sortIndex": 60,
        "classifyName": "一级>二!105:二级>一!119"
}
```

**Comment by Sandu1213** [comment]
测试环境是？

**Comment by yuanoook** [comment]
@azothli 
这是现在 release 的 wiki_module 数据，现在需要配置分类和排序。如果只需要排序，设置 sortIndex 就可以了。

[wiki_module.zip](https://github.com/tatfook/wikicraft/files/1701531/wiki_module.zip)

**Comment by Sandu1213** [comment]
待调整后再验证

**Comment by yuanoook** [comment]
调整后的数据，Rlease 环境 tabledb 等李志强修复后同步到数据库。

[wiki_module_classify_sort_release.zip](https://github.com/tatfook/wikicraft/files/1705994/wiki_module_classify_sort_release.zip)

**Comment by Sandu1213** [comment]
release环境测试通过，测试需要通过修改数据库index值的方式来验证。
