### ISSUE TITLE
支付页面在 IE 11 显示不全

### ISSUE THREAD

**Issue by xiaop1ng** [tatfook/wikicraft#1468]
![7qoc eo ey uc25sv fljml](https://user-images.githubusercontent.com/13251164/35219621-6101da4e-ffae-11e7-981f-55ecd6b66fe9.png)

支付页面在 IE 11 上信息显示不全 @onedou

**Comment by Sandu1213** [comment]
浏览器：IE （ver: 11.192.16299.0）
release环境验证通过
![image](https://user-images.githubusercontent.com/21214285/35491222-11c29c16-04e0-11e8-97a5-65c819a36b4c.png)
