### ISSUE TITLE
【需求设计】手机端模块显示问题

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1485]
左图右文字的如何显示
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/07c519f3-46ce-46a9-ac2c-ab866c608fae)
导航菜单过多时如何显示
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/b1df8960-5508-479b-9484-b00451ea9a41)
宽屏时手机显示
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/c22c5575-85a2-4e19-aa6d-ee54455c90db)

**Comment by Sandu1213** [comment]
#1486

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/35603954-de07b036-067a-11e8-8fc3-647de1ba4cce.png)



设计稿已完成
