### ISSUE TITLE
【Bug-ADI】ADI mod在手机端问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1486]
## The problem
ADI mod在手机端问题汇总

## Environment
* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.在手机上查看ADI 相关的mod，观察显示效果

* Expected Result:
1.页面信息显示正确
* Actual Result:
1.页面显示不合理
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/8023b594-23ea-4fa2-8366-c96ddfd20880)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/d0a7a277-e601-42f9-bf26-8c3e8b3a8c7f)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/c742c4fb-d2ee-4a71-bd0a-48fa603e7e59)

**Comment by azothli** [comment]
每款mod针对手机显示，给出自适应规则

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/36664288-265fb35c-1b1f-11e8-91bd-387ee2e67c49.png)

设计稿已完成   转开发
