### ISSUE TITLE
数据源连接按钮应该一直存在

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#150]
问题1： 工具栏中： 数据源连接按钮应该一直存在。即时没有绑定Github。并且那个按钮上的文字， 改为git,不是github.

当我取消绑定Github数据源后，保存页面修改， 数据并没有存到新的内置数据源上。 

暂时先按照： 如果开启了github显示ｇｉｔｈｕｂ，　如果没有开启，　显示我们自己的ｇｉｔｌａｂ对应的页面

４月改成每个网站都可独立配置数据源，并且只能有１个。

**Comment by wxaxiaoyao** [comment]
每个站点一个数据源， 点击跳转到对应数据源页面
