### ISSUE TITLE
【需求】网站图标

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#152]
设置中添加网站图标的设定（类似用户头像）
个人网站，默认用个人头像做图标
其他网站不设定的情况下,用网站缩略图是否可行？
用户可以在设置中进行修改。

**Comment by wxaxiaoyao** [comment]
用网站缩略图实现难度太大，建议去掉，  难度1 生成缩略图咱无合适库可用， 难度2：由于页面是md需动态生成html和相关数据获取，然后将其转化成图片， 性能开销太大。基本不靠谱。。。
