### ISSUE TITLE
【调整】优化头像上传功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#153]
不要上传原始分辨率的图片
将用户上传的图片缩放到一个合适的大小（300X300）？
然后允许用户选择图片区域。
体验参考qq的头像上传功能。
![image](https://cloud.githubusercontent.com/assets/22001356/24464216/c00a68f8-14db-11e7-935c-7b1b45ac6791.png)

**Comment by azothli** [comment]
看看是插件实现还是我们自己开发。

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/24484138/3b2a9d16-152f-11e7-92cd-2131bc190b93.png)

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/24484279/f4be58f8-152f-11e7-8a28-b7f140053989.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24538668/3abfe572-161d-11e7-87c1-d3bafda6e528.png)
目前已经有了
