### ISSUE TITLE
【bug-个人成长】添加认证，删除

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1572]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/2b91030f-56f6-405e-ad35-b2524fa46c1e)
操作步骤：1.添加认证，添加成功。2.点击向上按钮、向上按钮。3.删除第一个
显示结果：如图2
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/6a274476-543c-4a5e-8e6c-8ce266493913)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by duting1993** [comment]
测试通过
