### ISSUE TITLE
【bug-个人成长】查看他人网站，无法点击

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1575]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/8732434c-2c2c-4a6c-bf5b-cc6630a879e5)
操作步骤：1.查看别人主页。2.查看别人创建的网站。3.点击网站名字
结果：无法点击

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by duting1993** [comment]
测试通过
