### ISSUE TITLE
【bug-个人成长】添加多个作品后，切换table，我的作品消失不见，或只出现一个

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1577]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/201af36d-eb07-446e-81bf-3a5d55fd5388)
操作步骤：1.添加多个作品。2.切换table。 3.切换到个人信息
显示结果：1.添加后的作品消失或只展示一个作品

**Comment by ZhangKaitlyn** [comment]
测试地址： http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by duting1993** [comment]
测试通过
