### ISSUE TITLE
【Bug-个人成长系统】个人经历里的时间输入，建议调整为选择日期的形式

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1580]
## The problem
个人经历里的时间输入，建议调整为选择日期的形式

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，对个人经历进行设置，对日期进行输入

* Expected Result:
1.期望日期是选择的形式
* Actual Result:
1.日期可以自主输入，输入格式没有要求
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/1682004c-9688-4d6f-b715-04ccd507e298)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1580.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix环境验证通过
