### ISSUE TITLE
【bug-个人成长】添加时间限制时间类型

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#1582]
![image.png](https://images.zenhubusercontent.com/59df34bab0222d5de47b5b60/b8546dca-2453-4db1-ae49-668ed1967a34)
操作步骤：1.点击添加经历 。填写完成，保存成功
显示结果：时间没有限制

**Comment by Sandu1213** [comment]
http://fix.1580.stage.keepwork.com/   ，时间已经调整为控件选择的方式，该问题不存在了。

**Comment by ZhangKaitlyn** [comment]
和issue #1580重复
