### ISSUE TITLE
【Bug-个人成长系统】网站添加tag的功能需要调整，当tag过长时，需要考虑显示问题

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1583]
## The problem
网站添加tag的功能需要调整，当tag过长时，需要考虑显示问题

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，对网站页面进行查看，当存在过长的tag页网站时，显示是否正确

* Expected Result:
1.显示正确
* Actual Result:
1.显示不合理
 

## Attachments (eg:logs/video/screenshot)
![tag_length.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/36161b2d-61b2-4766-9536-72bfdb1efce8)

**Comment by ZhangKaitlyn** [comment]
测试地址:http://fix.1583.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix环境已经验证，验证通过，目前后端限制tag最多输入5个，超过5个不能存入。当tag名字过长后，会以省略号的形式来显示。
![image](https://user-images.githubusercontent.com/21214285/36016379-b3d6e7f2-0dad-11e8-9183-2e603d353b54.png)
