### ISSUE TITLE
【Bug-个人成长系统】添加个人作品后，去修改作品的排序，修改完成后，会发现作品栏消失了，请 调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1587]
## The problem
添加个人作品后，去修改作品的排序，修改完成后，会发现作品不见了

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，添加多个个人作品，然后去进行排序操作
2.排序完成后，退出编辑模式，观察排序结果

* Expected Result:
1.页面显示合理，作品排序正确
* Actual Result:
1.页面显示不合理，作品消失不见了

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by duting1993** [comment]
测试通过
