### ISSUE TITLE
【Bug-个人成长系统】个人首页的排序功能，当使用首位向上排序或者末位向下排序时，会出现排序错乱的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1590]
## The problem
个人首页的排序功能，当使用首位向上排序或者末位向下排序时，会出现排序错乱的情况

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，分别对个人作品、个人技能、个人经历、个人认证进行排序操作
2.使用首位向上排序及末位向下排序，观察排序结果

* Expected Result:
1.排序正确，页面显示正确
* Actual Result:
1.顺序出现错乱，多了空白项

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
feature环境验证通过，
