### ISSUE TITLE
【Bug-个人成长系统】次要技能项无法进行点赞操作

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1591]
## The problem
次要技能项无法进行点赞操作

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，对次要技能进行点赞操作，观察点赞结果

* Expected Result:
1.点赞成功，图标变成橙色
* Actual Result:
1.点击后无响应

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1591.1621.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
fix环境验证通过。（技能必须全部新建才行，旧的技能由于gitlab的数据冲突，可能会出现点赞失败的情况）
