### ISSUE TITLE
【Bug-个人成长系统】认证无法进行添加，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1594]
## The problem
认证无法进行添加，请排查
## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，对已有的认证信息进行排序，修改等操作，
2.未退出编辑模式时切换到网站页面，切换回来，观察认证信息显示是否正确
3.再次新增认证，观察新增是否成功

* Expected Result:
1.切换回来后，原有认证信息显示正确；新增新的认证可以成功
* Actual Result:
1.切换后，原有认证信息无法显示，新增认证也新增失败
 

## Attachments (eg:logs/video/screenshot)
![addcerification.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/201ab8ff-55bd-49ad-bc3a-b30a4c9965c9)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by duting1993** [comment]
验证通过
