### ISSUE TITLE
【Bug-个人成长系统】以访客的形式查看其他用户个人页面，页面显示不合理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1598]
## The problem
以访客的形式查看其他用户个人页面，页面显示不合理

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.未登录访问用户star2018, 页面地址如（http://release.keepwork.com/star2018 )
2.登录用户dukes,访问用户star2018，观察页面显示

* Expected Result:
1.显示符合要求
* Actual Result:
1.显示不是很合理
 

## Attachments (eg:logs/video/screenshot)
![guest](https://user-images.githubusercontent.com/21214285/35612037-3c962ebc-06a2-11e8-9307-c775721871fd.png)

**Comment by Sandu1213** [comment]
切换个人/网站/社交时，页面也显示不对，请一同调整

**Comment by ZhangKaitlyn** [comment]
还有置顶、取消置顶按钮也需要隐藏

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
feature环境验证通过，请合入release环境再验证
