### ISSUE TITLE
【调整】登录、注册调整，第三方登录功能添加

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#160]
【调整】登录、注册调整，第三方登录功能添加
添加 qq、微信、新浪、百度等账号的支持

**Comment by ZhangKaitlyn** [comment]
第三方登录需要申请接入，比如QQ登录 http://wiki.connect.qq.com/%E6%88%90%E4%B8%BA%E5%BC%80%E5%8F%91%E8%80%85
![image](https://cloud.githubusercontent.com/assets/18642919/25032651/81e6b8a4-2108-11e7-9e32-8eb34963ee3f.png)
