### ISSUE TITLE
【Bug-个人成长系统】关注作者列表，作者信息需要横着排列，且“已关注”按钮需要支持切换是否关注的功能

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1600]
## The problem
关注作者时，作者信息需要横着排列，且“已关注”按钮需要支持切换是否关注的功能

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.请见截图

* Expected Result:
1.显示符合要求
* Actual Result:
1.显示不是很合理
 

## Attachments (eg:logs/video/screenshot)
![sortbyline.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/2fcaa08e-4b0e-40e3-9165-e566572af72c)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/35657716-e027b6a4-0738-11e8-93cc-d4fd12b53ded.png)

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/35679995-eb8cdff0-0793-11e8-9deb-54568139bd46.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.concernlist.overflow.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
fix环境验证通过。
![image](https://user-images.githubusercontent.com/21214285/35790726-ceee5b9c-0a7e-11e8-8a3e-beec27b0c909.png)

**Comment by Sandu1213** [comment]
release环境验证通过
