### ISSUE TITLE
【Bug-个人成长系统】用户关注的页面无法在社交关注的网站里进行显示，请排查

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1601]
## The problem
用户关注的页面无法在社交关注的网站里进行显示，请排查

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.用户关注他人的网站后，回到自己的首页，观察关注的网站信息是否正确显示

* Expected Result:
1.关注的网站信息显示正确
* Actual Result:
1.关注的网站信息显示不对

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1601.stage.keepwork.com/kaitlyn
