### ISSUE TITLE
【bug-个人成长】内容为空时显示处理

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#1609]
![image.png](https://images.zenhubusercontent.com/59df33a4b0222d5de47b5b3c/1a52f5d4-ae0e-4807-a673-5f444612e815)

**Comment by ZhangKaitlyn** [comment]
测试环境：http://feature.user.system.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
作品内容为空时，页面显示正确。 feature环境验证通过
