### ISSUE TITLE
【Bug-个人成长系统】浏览作品的数量没有统计到，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1620]
## The problem
浏览作品的数量没有统计到，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入自己的个人首页面，对自己的作品进行查看，切换回来后刷新页面观察浏览数量是否统计正确
2.进入他人的个人首页面，对他人的作品进行浏览查看，然后刷新他人的个人首页，观察浏览量统计情况

* Expected Result:
1.浏览量统计正确
* Actual Result:
1.浏览量统计不合理
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/e28c161f-1b7b-4065-b3c5-9c3b7231e69e)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1620.stage.keepwork.com

**Comment by Sandu1213** [comment]
fix环境验证通过
