### ISSUE TITLE
【Bug-个人成长系统】技能页的点赞功能，使用说明信息提示反了，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1621]
## The problem
技能页的点赞功能，使用说明信息提示反了，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入个人首页页面，鼠标移动到技能页的点赞按钮上，观察提示语说明情况

* Expected Result:
1.显示正确
* Actual Result:
1.显示不合理
 

## Attachments (eg:logs/video/screenshot)
![skill_intro.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/83f1193f-dbb8-4e69-844d-2404c72cf147)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1591.1621.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
fix环境，验证通过

**Comment by Sandu1213** [comment]
release环境验证通过
