### ISSUE TITLE
【Bug-个人成长系统】个人首页的tag页，页首上的url 链接显示规则不是很合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1626]
## The problem
个人首页的tag页，页首上的url 链接显示规则不是很合理，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.对个人首页的tag栏进行操作，点击链接进行浏览，当切换选择其他页面时，希望切换符合预期

* Expected Result:
1.选择是一级一级向下的
* Actual Result:
1.选择后直接默认index页面了
 

## Attachments (eg:logs/video/screenshot)
![tag_line.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/4b850446-48fe-4002-9f03-d4e98e3b4b51)

**Comment by Sandu1213** [comment]
@William0911 如果网站存在文件夹，则访问文件夹下面的页面会访问失败，url地址栏缺少了文件夹的，需要补全。

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1626.stage.keepwork.com/

**Comment by Sandu1213** [comment]
fix环境验证通过，目前会把文件夹信息带出来

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/35963165-d81ad890-0cee-11e8-91a9-9ea65392a8a1.png)

**Comment by Sandu1213** [comment]
http://fix.1626.stage.keepwork.com/dukes/testurl/fold/ADKEF1
环境验证通过
