### ISSUE TITLE
【调整】注册UI调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#163]
![image](https://cloud.githubusercontent.com/assets/22001356/25122581/01e04852-2458-11e7-8389-7722ae5fbcde.png)
这里做一下自动变化，上面输入什么，下面就变化成什么
字可以是红色的，会比较显眼

![image](https://cloud.githubusercontent.com/assets/22001356/25122736/8bc18e96-2458-11e7-92e0-44ca530edd58.png)
新窗口打开

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/25123773/2b8bd7f8-245c-11e7-9697-21cc0862b06f.png)
![image](https://cloud.githubusercontent.com/assets/18642919/25123789/3670bb16-245c-11e7-917b-1f32b862ef14.png)
已调整
