### ISSUE TITLE
【Bug-ADI】添加menu mod 后，选择右对齐方式，发现菜单顺序显示不合理，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1633]
## The problem
添加menu mod 后，选择右对齐方式，发现菜单顺序显示不合理，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，选择menu mod进行操作
2.设置样式为右对齐，观察页面显示是否合理

* Expected Result:
1.页面显示合理
* Actual Result:
1.menu 顺序显示不合理
 

## Attachments (eg:logs/video/screenshot)
![image.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b35416e0-2220-41a8-bfdd-902758a3af2e)

**Comment by onedou** [comment]
已解决，请测试

**Comment by Sandu1213** [comment]
keepwork环境上已经修改，该问题关闭

**Comment by Sandu1213** [comment]
keepwork环境上又有问题了，请排查

**Comment by onedou** [comment]
新版keepwork 暂不支持右对齐
