### ISSUE TITLE
【Bug-个人成长系统】用户访问他人首页，对他人的技能进行点赞操作，发现点赞失败，请排查修改

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1638]
## The problem
用户访问他人首页，对他人的技能进行点赞操作，发现点赞失败，请排查修改

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://release.keepwork.com](http://release.keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.用户登录成功后，先查看自己的个人主页，再去访问其他用户的首页（如已关注的用户）
2.对别人的技能感兴趣后，进行点赞操作，观察结果

* Expected Result:
1.点赞成功，显示正确
* Actual Result:
1.点赞失败，请排查
 

## Attachments (eg:logs/video/screenshot)
![like_action.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/82f1725e-1744-4504-b424-97201653a194)

**Comment by William0911** [comment]
这些技能是什么时候创建的？看了一下貌似是数据库里没有这些skills的数据。有可能这个profile的md是之前开发的时候创建的，导致markdown里有这些记录而生产环境的数据库里没有。

**Comment by Sandu1213** [comment]
这些技能都是西峙昨天晚上体验的时候创建的，profile.md 创建成功后才能正常显示个人主页页面，所以应该是profile 之后的。

**Comment by William0911** [comment]
该bug产生是因为release环境和生产环境一部分账户共用了gitlab账户，在release环境下进行过操作，数据写入了release的数据库，而生产环境的数据库中没有这部分数据。等生产环境与测试环境分离后应该不会出现这个问题，线上用户没有在release环境操作过的也不会出现此问题。

**Comment by Sandu1213** [comment]
目前release环境验证通过，先通过，后续如果再有发现再跟进
