### ISSUE TITLE
【Bug-个人成长系统】退出个人成长系统后，还可以对作品、经历、技能等进行修改。实现不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1644]
## The problem
退出个人成长系统后，还可以对作品、经历、技能等进行修改。实现不对，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://keepwork.com](http://keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.用户进入个人首页进行查看操作后，退出登录
2.再次去操作个人主页的作品，技能等，进行编辑，新增或者删除操作，观察结果

* Expected Result:
1.无入口可以操作，必须登录后才能操作
* Actual Result:
1.可以正常操作，实现有误
 

## Attachments (eg:logs/video/screenshot)
![logout.png](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/36106d82-2433-40a9-a222-307ec72d46f2)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1644.stage.keepwork.com

**Comment by Sandu1213** [comment]
请再调整下

**Comment by Sandu1213** [comment]
还有多页面切换操作的情况，请处理
