### ISSUE TITLE
实现@video模块

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#165]
实现@video 命令
支持常用视频格式的iframe 方式内嵌。
注意手机上可自适应大小

**Comment by wxaxiaoyao** [comment]
[video](http://static.video.qq.com/TPout.swf?vid=l01276tvc8i) 转模块命令
```@wiki/js/video
{
    "videoUrl":"https://imgcache.qq.com/tencentvideo_v1/playerv3/TPout.swf?max_age=86400&v=20161117&vid=s0386xlr78b&auto=0"
}
```
sed -i 's/\[[^\|]\+\](\([^)]*\.swf[^)]*\))/```@wiki\/js\/video\n{\n\t"videoUrl":"\1"\n}\n```/g' filename
-i 直接修改文件 不加控制台输出
