### ISSUE TITLE
【Bug-ADI】title属性清空后，再次打开开关设置，输入新数据，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1660]
## The problem
title属性清空后，再次打开开关设置，输入新数据，请调整

## Environment

* OS Info: Window10
* browser Info: chrome   63.0.3239.132
* URL: [http://keepwork.com](http://keepwork.com) 
* Model:  页面编辑器-ADI

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器里，添加title mod
2.添加成功后，先清空标题的内容，然后关闭开关，再次打开开关，再进行设置
3.观察设置后的内容信息是否正确

* Expected Result:
1.设置内容成功，内容信息显示正确
* Actual Result:
1.设置失败
 

## Attachments (eg:logs/video/screenshot)
![20180208.gif](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/b16e2891-1f1e-41ed-8dfb-5d962e31a043)

**Comment by onedou** [comment]
新版ADI暂无这种情况
