### ISSUE TITLE
【Bug-移动端】个人成长系统在手机上显示不合理，请处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1671]
## The problem
个人成长系统在手机上显示不合理，请处理

## Environment

* OS Info: iphone SE [IOS10.3.2]  
* browser Info: chrome   63.0.3239.132
* URL: [http://keepwork.com](http://keepwork.com) 
* Model:  首页-个人成长系统

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.用户手机访问keepwork.com，进行操作，观察操作是否成功

* Expected Result:
1.页面显示合理且操作很方便
* Actual Result:
1.页面显示不合理
 

## Attachments (eg:logs/video/screenshot)
![1.jpg](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/58ba5711-688f-4fe6-96bc-3c273e221d5e)
![2.jpg](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/ade332a6-cb41-4c94-ac1c-41f57782701f)
![3.jpg](https://images.zenhubusercontent.com/59df34e3b0222d5de47b5b70/12192360-47e7-4aee-8845-936518c45982)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.1671.stage.keepwork.com/kaitlyn

**Comment by Sandu1213** [comment]
验证完成，目前隐藏了雷达图，次要技能与主要技能的分布显示不是很好。其他都正常，待产品Review后再确定是否合入。
