### ISSUE TITLE
【需求】登录检查、提示调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1677]
使用手机号登录keepwork，验证是否有用户名，没有则提醒创建。

**Comment by wanglin727** [comment]
设计已完成  dai待开发

**Comment by wanglin727** [comment]
![image](https://user-images.githubusercontent.com/33826048/37010236-961875e2-2125-11e8-804e-687918eea73c.png)

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #190](https://github.com/tatfook/keepwork/issues/190) via [**ZenHub**](https://www.zenhub.com/)
