### ISSUE TITLE
【需求】追加用户“收藏”

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#169]
显示用户的收藏内容，不需要权限，就可以看
![image](https://cloud.githubusercontent.com/assets/22001356/25321478/85d5b862-28e1-11e7-9d4e-b050ad86bfb8.png)

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25329534/acd6ebca-290e-11e7-866e-560645124f76.png)
