### ISSUE TITLE
【调整】作品、网站、收藏之间的关系调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#170]
以后提到作品，就是指一个具体的网页，而不是网站。
![image](https://cloud.githubusercontent.com/assets/22001356/25321425/2338c03c-28e1-11e7-9829-e7e8daa62ec5.png)
改成网站

![image](https://cloud.githubusercontent.com/assets/22001356/25321443/2e88d260-28e1-11e7-9124-01244c1550dc.png)
 改成网站

![image](https://cloud.githubusercontent.com/assets/22001356/25321502/aba832a4-28e1-11e7-9efd-ff85d0a2518e.png)
相关的“收藏”改成“关注”

点关注，都是“关注”网站。
![image](https://cloud.githubusercontent.com/assets/22001356/25321664/f3de5c46-28e2-11e7-9b64-d4470ad3483f.png)
在用户的关注列表中，需要添加一个勾选，勾选后，不提示更新动态。

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25370676/e37164b6-29be-11e7-8e80-ea4446053d26.png)
