### ISSUE TITLE
dashboard - 大文件管理

### ISSUE THREAD

**Issue by William0911** [tatfook/wikicraft#1747]
1.文件审核
2.文件查找
具体请查看设计稿

**Comment by William0911** [comment]
测试环境： http://fix.check.files.stage.keepwork.com/wiki/js/mod/admin/js/index

**Comment by Sandu1213** [comment]
已经验证，目前只有数据重复的问题待处理，其他都验证通过。

**Comment by Sandu1213** [comment]
验证通过，已上线。该Issue关闭
