### ISSUE TITLE
【Bug-多地登录】登录态检查有误，用户A在机器A上登录后，再切换到机器B上，修改密码后再次使用机器A进行操作，应该提示需要重新登录

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#1748]
# The Problem:
登录态检查有误，用户A在机器A上登录后，再切换到机器B上，修改密码后再次使用机器A进行操作，应该提示需要重新登录

# Environment:
* Devices info: PC
* OS system: windows
* Browser : chrome  65.0.3325.181
* Model:  登录

# Reproduces:
* Pre-conditions:
  1.网络正常，有2台以上设备
  2.已注册过Keepwork账号
* Details:
  1.账号A在机器A上进行登录操作，操作完成后未退出，即切换登录到机器B上
  2.再机器B上进行修改密码的操作，修改密码完成以后，再切换到机器A上进行操作
  3.进行充值VIP或者删除网站等操作，观察操作是否成功
* Actual Result:
  1.可以操作成功
* Expected Result:
  1.操作失败，用户需要重新进行登录后才能再进行操作

# Attachments (eg: Video/png/log)
  无

**Comment by ExerciseBook** [comment]
更换密码后删掉现有的这个账号的session就可以简单解决问题？

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #2787](https://github.com/tatfook/keepwork/issues/2787) via [**ZenHub**](https://www.zenhub.com/)
