### ISSUE TITLE
【海外版】登录注册调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#1765]
![image.png](https://images.zenhubusercontent.com/59db3be5b0222d5de47ad514/ea542cb8-342c-4ea7-bb30-3d38bf2697b6)

手机验证调整为输入email不验证

**Comment by ouyc** [comment]
Issue moved to [tatfook/keepwork #379](https://github.com/tatfook/keepwork/issues/379) via [**ZenHub**](https://www.zenhub.com/)
