### ISSUE TITLE
数据源逻辑优化

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#182]
与目前的默认存储逻辑是兼容的。 但是要支持单网站数据源以及路径可单独设置。

这个调整比较大， 希望看看何时可以完成。 因为5月开始有用户数据上来了。 最好可以动态做这次升级， 不影响外网用户。 因为本质上git数据源中的内容并没有更改， 只是keepwork的数据源逻辑有改动。 

具体文档请见：
https://github.com/tatfook/wikicraft/wiki/DataSource

**Comment by azothli** [comment]
这个现在应该是完成了吧
