### ISSUE TITLE
Markdown数据访问逻辑优化

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#184]
旧的访问流程中，客户端访问一个Markdown时， 往往会造成很多404Error例如 _Footer, _Sidebar, _Header等等。 

新的数据访问流程如下：分成2步
- 首先先获取文件树Object：此时包含了网站当前目录下的所有页面文件列表， 并用JS封装和缓存一下。 
    -  此时很多模板就可以根据文件树中的内容，决定是否有_Footer, _Sidebar, ... 以及文件后缀（是否是*.md, 只有md才认为是页面，一些本地页面搜索等）
- 根据文件树中的实际文件名，下载访问对应的文件

> 文件树的封装同样可以用在WikiEditor左侧的导航中

**Comment by wxaxiaoyao** [comment]
已有比较完善的缓存机制
