### ISSUE TITLE
大文件审核新接口替换 - Dashboard

### ISSUE THREAD

**Issue by William0911** [tatfook/wikicraft#1854]
在dashboard中替换大文件审核老接口为新的storage服务的接口
确保更换接口后大文件审核功能仍可用

**Comment by William0911** [comment]
测试地址： http://10.27.2.117:8099/wiki/js/mod/admin/js/index
管理员账号： william       密码:  123456

**Comment by Sandu1213** [comment]
release环境验证通过

**Comment by Sandu1213** [comment]
已更新到线上环境，该问题关闭
