### ISSUE TITLE
image 链接 大小应该做成最大不超过屏幕大小。目前会超出

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#187]
Video, image 都不应该超出Theme的大小。 
用markdown 生成的` <img class="md_img"/>`  最好带一个class, 方便我们用Theme来控制

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/25601993/ccaf7042-2f22-11e7-93c4-7e8107f66a21.png)

word press 上是这样的
它默认是750*422

**Comment by azothli** [comment]
可以考虑嵌入媒体宽度与页宽的比例关系
因为页宽是会变化的
嵌入媒体需要 对齐规则（左右中）、与页宽的比例关系（%）
这样在屏幕变化的时候，就不会显示错误了。

**Comment by azothli** [comment]
if 图片宽度<480
 图片宽度为原宽度
else
 图片宽度=页面显示框架宽度（最大1180，如果在低分辨率下，就是当时的实际宽度）

**Comment by azothli** [comment]
默认对齐方式是左对齐
