### ISSUE TITLE
【调整】keepwork.com/user 3个大按钮布局调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#191]
keepwork.com/user 3个大按钮布局调整
![image](https://cloud.githubusercontent.com/assets/22001356/25657219/5ffe0e1e-302f-11e7-9852-037f3778d136.png)

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25695894/7f2ffeba-30e7-11e7-91db-3cae58e80e3e.png)
