### ISSUE TITLE
【需求】下划线功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#198]
常用功能，用热键ctrl+u
增加一个按钮
现在被取消选择占用，ctrl+u 调整为下划线

![image](https://cloud.githubusercontent.com/assets/22001356/25696977/d0752b2a-30eb-11e7-91d0-9b917f3421b5.png)

**Comment by wxaxiaoyao** [comment]
扩展语法问题： [[链接]]  ++下划线++   这种语法支持不是很难， 但逆转换回去(html=>md)基本很难实现，逆转换功能很弱，这种语法在视图编辑(直接页面编辑非源文件)是无法启作用 [[]] 会变成 ()[] ， ++++应该会直接丢失。

**Comment by wxaxiaoyao** [comment]
@Tibet0312 test

**Comment by Tibet0312** [comment]
@wxaxiaoyao 0321

**Comment by wxaxiaoyao** [comment]
已作隐藏
