### ISSUE TITLE
【bug】活动次数日期没有显示全部

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#203]
活动次数日期没有显示全部，如图
![image](https://cloud.githubusercontent.com/assets/28430070/25786670/a36a230a-33cb-11e7-819e-eaab8b88c613.png)

**Comment by azothli** [comment]
调整星期的美术显示效果，当前的方式不好理解。
考虑用一个什么方式表示时间区间

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25881536/11c2a8f4-3570-11e7-8c78-8a2fc8e57780.png)


只显示星期日、星期六，中间用竖线替代
