### ISSUE TITLE
【需求】地址、信箱、链接，应该以哪种方式显示出来

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#204]
地址、信箱、链接，应该以哪种方式显示出来
![image](https://cloud.githubusercontent.com/assets/28430070/25786689/dbd993d8-33cb-11e7-879f-e6641732f2ad.png)

**Comment by azothli** [comment]
url的图标 要有灰色的版本

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25840865/2bc4967c-34d0-11e7-8279-d429f66db8f7.png)
 
超出长度隐藏，hover显示全部

**Comment by azothli** [comment]
这个方案不好，关键信息没显示
可以试试   ......后面的部分
后面的内容才是关键的
