### ISSUE TITLE
【bug】无法跳转新的页面

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#206]
关于我们、联系方式，合作伙伴/Paracraft 更新信息，问题反馈，无法跳转新的页面

**Comment by duting1993** [comment]
![image](https://cloud.githubusercontent.com/assets/28430070/25786893/95de9e02-33ce-11e7-8d9a-74acb3f2ff33.png)

**Comment by azothli** [comment]
关于我们 取消
联系方式 打开页面，现在内容为“如有任何问题，请发送邮件到admin@keepwork.com”
合作伙伴/paracraft   改为 Paracraft，新窗口打开http://www.paracraft.cn/?lang=zh
