### ISSUE TITLE
【需求】问题反馈应该跳转到哪个页面

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#207]
![image](https://cloud.githubusercontent.com/assets/28430070/25786881/7454ca54-33ce-11e7-9ea7-9e4c5c5818e2.png)

**Comment by azothli** [comment]
参考投诉ui，做一份 问题反馈的界面
当前是连接到github，以后要有ui连接到我们的运维

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25839834/f61eec4c-34cb-11e7-9f79-b614c014af35.png)
@duting1993
