### ISSUE TITLE
[调整]注册/显示文字

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#21]
![image](https://cloud.githubusercontent.com/assets/22001356/22773729/9d6b945c-eede-11e6-949c-abeb3191ec31.png)
注册邮箱->E-mail（登陆账号）

![image](https://cloud.githubusercontent.com/assets/22001356/22773825/317948c4-eedf-11e6-8d47-afb67a4ce67a.png)
用户名下面增加提示，个人网址：http://paracraft.wiki/***
给用户实时的提示。

**Comment by wxaxiaoyao** [comment]
已改
