### ISSUE TITLE
【bug】登陆主页之后，左侧头像右下方，“投诉”无法点击

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#210]
![image](https://cloud.githubusercontent.com/assets/28430070/25792950/488b320e-33fc-11e7-8c05-ae9a01abee5f.png)

**Comment by azothli** [comment]
本按钮取消，统一放在页底条中

**Comment by azothli** [comment]
完成

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25839482/6de4459e-34ca-11e7-9a86-6e8df6aae3ff.png)

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25839668/394bb190-34cb-11e7-9cbc-50c51b2c5acc.png)
