### ISSUE TITLE
【bug】活动次数，下边查看数据统计方法，跳转到了我的主页面

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#211]
![image](https://cloud.githubusercontent.com/assets/28430070/25792984/76ab8030-33fc-11e7-9d52-57477fa2e78b.png)

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25981397/7e3dc444-3707-11e7-97cf-81dc56b4b787.png)

**Comment by azothli** [comment]
做一个mouseover的简单说明
