### ISSUE TITLE
【bug】热门作品的收藏图标，显示的是实心五角星

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#214]
![image](https://cloud.githubusercontent.com/assets/28430070/25793085/02ca1df6-33fd-11e7-8b3a-16ca56b7ee59.png)

**Comment by yuanoook** [comment]
空心实心标识当前用户对页面对收藏状态，需要补充后端接口数据

**Comment by duting1993** [comment]
热门功能已取消
