### ISSUE TITLE
[调整]注册/添加可用性提示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#22]
![image](https://cloud.githubusercontent.com/assets/22001356/22774274/646b07ac-eee1-11e6-962e-79b885482184.png)
用户输入邮箱后，焦点转移的时候进行数据比对，验证输入项是否可用（符合规则，未被使用）
给出对应的提示。

**Comment by wxaxiaoyao** [comment]
目测，图标需美术图。。。

**Comment by caoyongfeng0214** [comment]
直接用 bootstrap的样式解决。

**Comment by caoyongfeng0214** [comment]
参考：
http://v3.bootcss.com/css/#forms-control-validation

**Comment by ZhangKaitlyn** [comment]
已修改
![image](https://cloud.githubusercontent.com/assets/18642919/23250565/ab7ff70c-f9e4-11e6-8d3d-3b0d69617407.png)
![image](https://cloud.githubusercontent.com/assets/18642919/23250588/c57225c2-f9e4-11e6-8a2d-9d1b0b0b85f3.png)
