### ISSUE TITLE
【bug】点击头像设置中心，VIP，我的VIP，显示问题，新用户不是VIP，充值缴费才能成为VIP

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#225]
![image](https://cloud.githubusercontent.com/assets/28430070/25793389/cc319af6-33fe-11e7-8671-bb74a54c8d15.png)

**Comment by azothli** [comment]
尚未实装，现在显示的是假数据

**Comment by azothli** [comment]
vip上线之前，先做一下隐藏吧
