### ISSUE TITLE
【bug】点击头像设置中心，VIP，我的VIP，追加续费，VIP购买付费无法选择，无法微信支付，手机支付，银行卡支付，没有二维码，如图2，且没有返回按钮，若点击网页上返回按钮，则返回到图2 页面

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#226]
【bug】点击头像设置中心，VIP，我的VIP，追加续费，VIP购买付费无法选择，无法微信支付，手机支付，银行卡支付，没有二维码，如图2，且没有返回按钮，若点击网页上返回按钮，则返回到图2 页面
图一
![image](https://cloud.githubusercontent.com/assets/28430070/25793411/eb47f71e-33fe-11e7-85bd-e41852fd41ef.png)
图二
![image](https://cloud.githubusercontent.com/assets/28430070/25793419/f1405634-33fe-11e7-9c69-b0018ec5fe90.png)

**Comment by azothli** [comment]
尚未开发
