### ISSUE TITLE
[调整]top条调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#23]
![image](https://cloud.githubusercontent.com/assets/22001356/22775146/428deb5a-eee5-11e6-9897-45d78947dec4.png)
非登录状态，不显示个人主页

![image](https://cloud.githubusercontent.com/assets/22001356/22775263/d666782e-eee5-11e6-80ac-216750f93e5c.png)
位置移动，登陆后，显示在top条

**Comment by wxaxiaoyao** [comment]
问题重复，已修改。
