### ISSUE TITLE
【bug】个人主页，点击页面编辑器，点击热键按钮，弹出图二对话框，没有取消按钮

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#232]
图一![image](https://cloud.githubusercontent.com/assets/28430070/25796762/7a721506-340d-11e7-9373-a14da9a51687.png)
图二
![image](https://cloud.githubusercontent.com/assets/28430070/25796773/81280234-340d-11e7-93c0-4adb53b3c3bd.png)

**Comment by azothli** [comment]
添加按钮

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25838949/175c278e-34c8-11e7-801a-a93b103a3ff0.png)
@duting1993
