### ISSUE TITLE
【bug】个人主页，点击页面编辑器，点击模块按钮，无法添加模板，且添加之后，出现退出弹框现象，点击弹框以外的区域，出现退出弹框

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#234]
![image](https://cloud.githubusercontent.com/assets/28430070/25797017/31d88996-340e-11e7-9d51-bb937b91873f.png)

**Comment by azothli** [comment]
点击周围黑色区域，关掉弹窗是正常的。
其他添加不正常的现象，程序处理。
