### ISSUE TITLE
【bug】点击网站无法展开，只有点击+，网站才能展开

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#246]
![default](https://cloud.githubusercontent.com/assets/28430070/25837500/d4352a20-34c0-11e7-90b4-760ffe8ea53d.png)

![default](https://cloud.githubusercontent.com/assets/28430070/25837530/eec9168a-34c0-11e7-92dc-d95ad938c452.png)

**Comment by azothli** [comment]
这里可以优化下，如果点击的内容是文件夹，可以展开
