### ISSUE TITLE
[调整]网页编辑按钮相应

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#25]
![image](https://cloud.githubusercontent.com/assets/22001356/22776531/f9adef24-eeea-11e6-8c01-40996e68c655.png)

现在点击后打开了一个空白的页面
应该打开编辑器，然后打开之前要编辑的页面。

**Comment by LiXizhi** [comment]
这里我觉得不应该做到模板中， 应该是上面Header中加入编辑。 
@azothli

**Comment by azothli** [comment]
是的，这个应该在top条中

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/22959253/d09cf56a-f36f-11e6-84be-03a25360b91a.png)

**Comment by wxaxiaoyao** [comment]
![image](https://cloud.githubusercontent.com/assets/11922085/23061052/46b2c140-f53b-11e6-847f-e4dc4f6244e5.png)
已移至top， 若当前页为用户页，点击编辑会跳转编辑页并打开当前页，当前页不为用户页则默认打开个人网站首页
