### ISSUE TITLE
[需求]编辑器，添加新建目录的功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#26]
![image](https://cloud.githubusercontent.com/assets/22001356/22923090/11d9f68a-f2db-11e6-992a-882818727da2.png)
增加一个新建目录的按钮，使用体验与新建页面类似。

**Comment by wxaxiaoyao** [comment]
文件名以路径形式填写即可创建目录。
![image](https://cloud.githubusercontent.com/assets/11922085/23060862/7e2da0dc-f53a-11e6-9670-6ec782e60dab.png)
![image](https://cloud.githubusercontent.com/assets/11922085/23060878/93aa41cc-f53a-11e6-98ed-d47c85b26efb.png)

**Comment by wxaxiaoyao** [comment]
![image](https://cloud.githubusercontent.com/assets/11922085/23061012/1716cb84-f53b-11e6-9c60-c97b322dd73b.png)
![image](https://cloud.githubusercontent.com/assets/11922085/23061021/24131c5c-f53b-11e6-9680-d03acbf1e7cd.png)
