### ISSUE TITLE
【bug】创建网站域名长度没有限制

### ISSUE THREAD

**Issue by RyanGIggs** [tatfook/wikicraft#264]
应该增加一个字数限制，目前过界了

![qq 20170509173843](https://cloud.githubusercontent.com/assets/16772836/25844891/875b9932-34de-11e7-8625-cdfced35961e.png)

**Comment by azothli** [comment]
长度1~30   
小写数字a~z 数字0~9

**Comment by duting1993** [comment]
![image](https://cloud.githubusercontent.com/assets/28430070/26021780/5c149bb6-37c7-11e7-8283-6e1a21e1a123.png)
可以输入三十个字以上，且能保存成功，返回我的个人主页时，出现此现象
