### ISSUE TITLE
[调整]编辑器，页低栏位置

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#27]
![image](https://cloud.githubusercontent.com/assets/22001356/22925280/0ba74602-f2e3-11e6-9941-2515d0894c5a.png)
没有添加内容的状态下，编辑器也要拉伸到一页的高度，可以将页底的版权信息顶到看到的页面外。

**Comment by wxaxiaoyao** [comment]
已修改
![image](https://cloud.githubusercontent.com/assets/11922085/23056559/f32a4aac-f526-11e6-87dc-8e208af9138e.png)
