### ISSUE TITLE
【bug】用户名可以很长，并且能注册成功

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#273]
![default](https://cloud.githubusercontent.com/assets/28430070/25887573/425cef4a-3595-11e7-9938-fb02fc741024.png)

![default](https://cloud.githubusercontent.com/assets/28430070/25887508/0a7161e2-3595-11e7-881f-a34eeee16495.png)

**Comment by azothli** [comment]
4~30位 a~z 0~9
不可纯数字
