### ISSUE TITLE
【重要需求】全站支持可输入内容关键字过滤功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#276]
包括并不仅限于
注册账号
网站名称
网站介绍
网站录入文本
回复
....................

在设定的功能中，要提示不可用（例如：该网站名称不可用）
在内容展示中（页面内容，提示性文字），要进行替换显示。
例如：”她*****了”，用*来替换不可描述的内容。

全部黑名单关键字，读自配置文件。方便后期维护。

**Comment by ZhangKaitlyn** [comment]
### 注册 
![image](https://user-images.githubusercontent.com/18642919/31651361-fcd6bbe0-b34d-11e7-972a-86b01ee1ec9a.png)
### 新建网站
![image](https://user-images.githubusercontent.com/18642919/31651386-13fb5100-b34e-11e7-8f88-0e47c28468b8.png)
### 网站编辑
![image](https://user-images.githubusercontent.com/18642919/31651400-2687c196-b34e-11e7-9a48-9e468fecdee3.png)
### 用户信息设置
![image](https://user-images.githubusercontent.com/18642919/31651425-35233d66-b34e-11e7-8985-8305da2735f7.png)
### 编辑器
![image](https://user-images.githubusercontent.com/18642919/31651458-4d46d614-b34e-11e7-953d-17d250f21a4b.png)
### 评论模块
![image](https://user-images.githubusercontent.com/18642919/31651498-76925caa-b34e-11e7-8aed-681ffb51185e.png)

**Comment by Sandu1213** [comment]
已经在tmp环境上进行验证，验证通过，待合入正式环境后再验证一遍即可。
**潜在的风险是：**
目前关键字库可能不全，存在部分遗漏的情况，待后续发现后再逐步完善关键字库。

**Comment by azothli** [comment]
关键字目前国家无统一标准，都是各自维护。
