### ISSUE TITLE
[视觉优化]文件按钮

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#28]
![image](https://cloud.githubusercontent.com/assets/22001356/22925617/5c5e6aa2-f2e4-11e6-8ee8-2e934945e75f.png)
文件按钮与相连的两个按钮的意义不同，要有视觉区分，现在会错觉为tab

**Comment by wxaxiaoyao** [comment]
建议保留此样式，上面四个按钮分别对应编辑页面主体从左到右的四个部分，单独出来一个按钮也感觉挺奇怪的。

**Comment by wxaxiaoyao** [comment]
见上述comment， 这个bug。。。 也关了吧。 若文件按钮还是要和代码按钮隔开，发个QQ消息过来，我加个间距。
