### ISSUE TITLE
【bug】收藏按钮

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#285]
![image](https://cloud.githubusercontent.com/assets/28430070/26051454/cbfa4844-3994-11e7-8a69-2e7e5f5adf5b.png)
若搜藏，点击刷新，或者下次打开时，此时应该是实心

**Comment by ZhangKaitlyn** [comment]
需要根据用户名和站点名判断是否收藏了的接口 @wxaxiaoyao

**Comment by LiXizhi** [comment]
@duting1993 @Sandu1213

**Comment by Sandu1213** [comment]
问题依然存在，请调整，详情请见截图：
![collect](https://user-images.githubusercontent.com/21214285/33253960-52480cac-d381-11e7-9da7-7764e7d9e43c.gif)
