### ISSUE TITLE
upload images

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#3]
![image](https://cloud.githubusercontent.com/assets/94537/18659390/d114a652-7f3c-11e6-8b1a-0f88de7bf6ec.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18659961/7f12b214-7f40-11e6-9495-c02d97a8e86f.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18660002/ba54fb66-7f40-11e6-9720-28392da5008a.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18697531/a2cdd56c-7ff4-11e6-9ede-76d5bc05854b.png)

**Comment by azothli** [comment]
![workslist](https://cloud.githubusercontent.com/assets/22001356/19915327/79fbdb2a-a0ec-11e6-81d9-13645d667408.png)

**Comment by wxaxiaoyao** [comment]
此题是否是github上传图片问题，若是则已修改。
