### ISSUE TITLE
【bug】个人主页点击退出，重新登录，会出现以前账号

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#307]
![image](https://cloud.githubusercontent.com/assets/28430070/26519013/8dad6c26-42ed-11e7-914c-08bb29b4ef19.png)
![image](https://cloud.githubusercontent.com/assets/28430070/26519031/e5c07944-42ed-11e7-984d-f75b0ff7fffa.png)
![image](https://cloud.githubusercontent.com/assets/28430070/26519040/faea3224-42ed-11e7-8b28-c679c5abccf1.png)

**Comment by ZhangKaitlyn** [comment]
这个不是bug，浏览器自己填充，而且登录时浏览器自己填充账户信息没问题吧
这个出现的账户名和密码应该是浏览器根据你填充的次数选择填充的
