### ISSUE TITLE
[bug]热键显示缺少背景

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#31]
![image](https://cloud.githubusercontent.com/assets/22001356/22925753/dc8598a4-f2e4-11e6-9ca2-5144a52f2c8a.png)
右侧内容排版不一致

**Comment by wxaxiaoyao** [comment]
已修改
![image](https://cloud.githubusercontent.com/assets/11922085/23056428/4c31932c-f526-11e6-8353-6d53959c9852.png)
