### ISSUE TITLE
[bug]知识库 按钮无响应

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#32]
![image](https://cloud.githubusercontent.com/assets/22001356/22925843/2dce6ea2-f2e5-11e6-8fc9-56fb37bc8470.png)

点击无反应

**Comment by wxaxiaoyao** [comment]
![image](https://cloud.githubusercontent.com/assets/11922085/23201188/686b0014-f913-11e6-83ee-5396c715a710.png)
此页后续扩展成使用帮助页， 暂只有一篇简单markdown使用介绍
