### ISSUE TITLE
【bug】左右留白有些太大了， 默认模版又完全没有边距

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#325]
手机版，左右留白太大
![image](https://cloud.githubusercontent.com/assets/28430070/26664759/8a8f2782-46c6-11e7-9906-ddbfd801f37d.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/26672541/1fffc4f0-46ec-11e7-89c4-046a407d9538.png)

默认模版又完全没有边距

**Comment by LiXizhi** [comment]
http://keepwork.com/lixizhi/note/MovieInAI?branch=master

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/26673584/fda4771c-46ef-11e7-959b-0e4184c668eb.png)
@LiXizhi
