### ISSUE TITLE
【bug】paracraft创建网站的默认图标调整为一个新的设计

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#327]
![image](https://cloud.githubusercontent.com/assets/28430070/26667510/29e80054-46d8-11e7-81d2-738275a342b6.png)

**Comment by azothli** [comment]
这里应该不是那个图，因为结构是
pc作品网站包含很多 pc作品网页（这个是客户端上传过来的）
此处是网站的图标，我们可以固定一款
表示是PC作品集的意思就可以了

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/26869609-92349958-4b9f-11e7-9ad8-e54f2693c3da.png)
