### ISSUE TITLE
[调整]存盘提示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#33]
![image](https://cloud.githubusercontent.com/assets/22001356/22925866/4a2b9c5a-f2e5-11e6-9005-5a3395fd00a8.png)
成功等内容不需要弹出确认窗口
可以在工具栏上直接显示文字状态，提示存储成功或不成功等信息，减少用户点击次数。

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/22926080/223fbd7e-f2e6-11e6-8bb3-c1dfd87482f1.png)

**Comment by azothli** [comment]
文字仅供示例

**Comment by wxaxiaoyao** [comment]
![image](https://cloud.githubusercontent.com/assets/11922085/23060542/2054e890-f539-11e6-80b0-00bd4c5f2c78.png)
已修改成如上图样式，网站提示通知均用此自动滑下信息，2秒后自动滑上隐藏

**Comment by wxaxiaoyao** [comment]
修改见上述评论， 若提示不友好，待ui重新改版加后再考虑搭配修改提示，暂时关闭（bug显示太多不便查看其它bug）
