### ISSUE TITLE
【调整】编辑器调整，文件夹后面留个小间隙

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#335]
![image](https://cloud.githubusercontent.com/assets/22001356/26710221/e96c26be-478a-11e7-91a5-4c6d0a221798.png)
文件夹后面留一个小间隙，现在容易忽略掉

**Comment by Tibet0312** [comment]
10px

![image](https://cloud.githubusercontent.com/assets/25898720/26713497/96a5d4a6-479f-11e7-810e-f27aa9c2e1cb.png)
