### ISSUE TITLE
【调整】编辑器  treeview部分调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#336]
![image](https://cloud.githubusercontent.com/assets/22001356/26711038/5286f520-4790-11e7-93da-33c1a36b81c3.png)
文件夹 改成 浏览   配个白色线的地球经纬就好
然后要添加一个新的目录  已打开  （如果没有打开的网页就不显示这个目录）
放已经打开的文件在里面，方便查找
增加 关闭 按钮，解除一个文件的编辑状态（如果有*，状态有变化，提示保存或者放弃）
增加刷新按钮（忽略本地变化，有*需要提醒确认，强制提取服务器数据）

网站的关闭全部=关闭网站全部已打开文件

**Comment by azothli** [comment]
能秒改的先改

**Comment by Tibet0312** [comment]
效果图：

![image](https://cloud.githubusercontent.com/assets/25898720/26816655/53504280-4ac5-11e7-9e8e-d88b5a63631b.png)

![image](https://cloud.githubusercontent.com/assets/25898720/26816703/9bbbdd9a-4ac5-11e7-94ac-c54d0a7406cf.png)

![image](https://cloud.githubusercontent.com/assets/25898720/26816728/bdeedb42-4ac5-11e7-9032-83adad16c8af.png)

![image](https://cloud.githubusercontent.com/assets/25898720/26816747/e616c1b6-4ac5-11e7-84d8-1b16c443df7a.png)

![image](https://cloud.githubusercontent.com/assets/25898720/26816849/5c810dd4-4ac6-11e7-9d83-bd302127e7c0.png)
