### ISSUE TITLE
【调整】预览比例控制，重新设计一下

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#337]
现在没有锁定比例，便来变去会不确定效果

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/26722492/cacc55de-47c2-11e7-8286-ca7ce29f5b54.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/26965569-f0a5614a-4d28-11e7-8e68-f52390c7c764.png)

我看了一下。 这里代码略作调整即可。 改成
SetPreviewSize(actualSize, scale).

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/26966028-06ed45d8-4d2b-11e7-9ec7-91b60c897069.png)

我希望， 类似Chrome

第一个值，尽量是不小于1020的预览窗口的大小。 
这样可以让第二个值尽量接近100%
做到接近1:1的预览效果，尤其在大显示器上。

**Comment by LiXizhi** [comment]
我刚刚看了bootstrap3的代码。 好多地方用了@media   不过好像目前最大是1200. 我们按照最小1200来设计也行， 这样就不用改css了。 



- 如果预览窗口>1200, 则为预览窗口的大小。
- 如果预览窗口<1200,则为min(1200, 整个窗口的大小)

**Comment by ZhangKaitlyn** [comment]
![adp e 0z6bzqt 5twqw1zrf](https://user-images.githubusercontent.com/18642919/26970952-d40a11f6-4d3d-11e7-92be-d0c428eb2735.png)
