### ISSUE TITLE
[bug]网站设置  基本设置 logo设置

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#34]
浏览设置logo没有对文件的类型进行限制，要限制为可支持的图片。
选择后要加载预览效果
![image](https://cloud.githubusercontent.com/assets/22001356/22964579/577276cc-f394-11e6-9ed6-60e9f35314cd.png)

**Comment by wxaxiaoyao** [comment]
这个输入框已经对文件类型做了过滤，默认只选择图片， 但弹出的对话框系统默认会添加所有文件选项，这个选项去掉有待研究(已问下曹老师，需百度答案)。 感觉这个也没太大必要吧。好像所有网站都会这样。。。

**Comment by wxaxiaoyao** [comment]
此问题应为正常现象，QQ空间发说说，选择图片也是这样。。。

**Comment by wxaxiaoyao** [comment]
见上述评论， 应不是问题。。。
