### ISSUE TITLE
编辑器新建一个页面时，保存后点击在gitlab查看，显示404页面

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#340]

**Comment by onedou** [comment]
![image](https://cloud.githubusercontent.com/assets/3422640/26751244/5bea1a16-4867-11e7-9272-962d7d65ace7.png)
![image](https://cloud.githubusercontent.com/assets/3422640/26751245/6ed4f22c-4867-11e7-9914-0cd32be0a782.png)
![image](https://cloud.githubusercontent.com/assets/3422640/26751246/72ab91c6-4867-11e7-8b8a-3f854e723e27.png)

**Comment by LiXizhi** [comment]
Change to `master/` instead of commitid
