### ISSUE TITLE
【bug】点击作者，跳转到个人首页，查看更多，新窗口打开展示更多

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#348]
![image](https://cloud.githubusercontent.com/assets/28430070/26812548/f0fa087e-4aaa-11e7-8019-89ee5c5c560e.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/26819918/8e05fc90-4ad3-11e7-8941-d2a43b6582d0.png)
