### ISSUE TITLE
[调整]网站设置  基本设置

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#35]
![image](https://cloud.githubusercontent.com/assets/22001356/22964591/64a1e45e-f394-11e6-81de-09ec06170959.png)
按钮文字调整为“保存修改”
执行后要给出“保存成功”的提示。
![image](https://cloud.githubusercontent.com/assets/22001356/22964627/91dd8126-f394-11e6-90a6-2996a18fa62a.png)

**Comment by wxaxiaoyao** [comment]
已修改
