### ISSUE TITLE
【bug】微信登录支持

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#353]
微信的开发者账号大家急匆匆的与总部协调办下来了，不能开发没有后文了。
这个账号我办下来交给程序很久了，现在告诉我没开发。
请抓紧！！！！

**Comment by azothli** [comment]
如果还需要申请什么，处理什么，请明确告知。

**Comment by wxaxiaoyao** [comment]
已调通， 自测可以， 下次更新keepwok需验证，没有问题可关闭
