### ISSUE TITLE
[bug]网站设置 高级、成员、作品缺失对应内容

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#36]
![image](https://cloud.githubusercontent.com/assets/22001356/22964667/c3892b44-f394-11e6-97e0-42adc75a4f64.png)

**Comment by wxaxiaoyao** [comment]
暂时没有高级设置已隐藏， 成员管理，作品管理内容未缺失，应是不会使用没有给站点添加成员和作品，导致无数据显示被认为缺失

**Comment by wxaxiaoyao** [comment]
已改版，问题失效
