### ISSUE TITLE
私有项目查看不要再浏览器中显示出Token

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#361]
https://stackoverflow.com/questions/3951768/window-open-and-pass-parameters-by-post-method

![image](https://user-images.githubusercontent.com/94537/27212952-4ae705c4-5296-11e7-8ef8-55d2bc752fc7.png)
能否对于private_token 用ｐｏｓｔ。这样Ｔｏｋｅｎ不会出现在浏览器ＵＲＬ中。万一用户不小心给复制粘贴了。　

http://git.keepwork.com/gitlab_rls_lixizhi/keepworkdiary/blob/master/lixizhi/diary/index.md?private_token=XXXXXX

另外就是看看能不能避免浏览器中显示出这个token。　用Ｐｏｓｔ的方式。

**Comment by wxaxiaoyao** [comment]
git文档不支持post打开curl -X POST --data '{"private_token":"71Zk5yetZErcJjwjD3nk"}' http://git.keepwork.com/gitlab_www_xiaoyao/keepworktest/blob/master/xiaoyao/test/index.md

**Comment by LiXizhi** [comment]
ok  只能这样了。
