### ISSUE TITLE
向服务器上传任意文件

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#371]
![image](https://user-images.githubusercontent.com/94537/27422913-759ef31e-5762-11e7-8084-c0f3d4418a47.png)

需要加一个向服务器上传任意文件的地方。可以做到上面这个弹出的下面。

文件名使用和用户本地选择的文件一样，如果服务器上 有，则直接覆盖。
URL不用master 而是默认用commitid + filename （这样可以有效的CDN加速， 所有同名旧连接也不会失效，如果高级用户希望使用master版本可以自己手工改）

![image](https://user-images.githubusercontent.com/94537/27423250-9391c44a-5763-11e7-9cbf-2f7faab0c5f7.png)
可以参考这个

**Comment by LiXizhi** [comment]
@azothli 先设计下UI

**Comment by azothli** [comment]
支持文件还有常用的rar吧
不支持可执行文件，避免服务器安全问题

**Comment by wxaxiaoyao** [comment]
文件上传存于username_files目录, 图片上传存于username_images目录， 后续不再使用images目录，数据依旧有效， 当然用户名为images会存在冲突，  文件上传上述格式基本都支持， txt文件格式暂不支持(gitlab对此文件有特殊处理)

**Comment by LiXizhi** [comment]
为何要放在username_images目录呢?

**Comment by LiXizhi** [comment]
可以上传PPT文件， 但是下载后文件大小和上传的不一样。 

![image](https://user-images.githubusercontent.com/94537/27760183-d0bbcd2c-5e73-11e7-82f4-447b2a30bda9.png)

不知道为何GITHUB默认不支持PPT，只是PPTX

@wxaxiaoyao

**Comment by duting1993** [comment]
除了图片，能上传成功，且能展示，svg，上传之后，预览图片展示不出来，其他文件，能长传成功，能下载，但是不能打开。文本上传之后，打开会是乱码

**Comment by duting1993** [comment]
![image](https://user-images.githubusercontent.com/28430070/27899855-8783cc10-625e-11e7-8e93-ac86f56ce059.png)
svg能上传成功，预览图片展示不出来
TXT，能长传成功，下载后打开时乱码
