### ISSUE TITLE
【bug】注册名字过长时，点击头像，名字超出

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#373]
![image](https://user-images.githubusercontent.com/28430070/27425988-c3c9b5e2-576c-11e7-900c-c27f83322a9b.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/27470072-b9f15602-5824-11e7-9840-b173bbe76924.png)
