### ISSUE TITLE
【bug】第一次点击预览，如图一，且能申请加入成功，第二次点击预览，如图二，与图一显示不一样

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#374]
![image](https://user-images.githubusercontent.com/28430070/27463142-494baa1e-57f8-11e7-9903-2ca05a7a278c.png)

![image](https://user-images.githubusercontent.com/28430070/27463114-16919174-57f8-11e7-8815-fe30c9d3024e.png)

**Comment by azothli** [comment]
没懂，是不是已经申请了，在等待批准
