### ISSUE TITLE
哈奇内部的登陆，支付与注册UI调整

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#377]
- [ ] 首页Logo替换为  `Texture/Aries/Login/haqilogo_32bits.png`  
![image](https://user-images.githubusercontent.com/94537/28451940-d2ac2906-6e22-11e7-9869-7535cd69e1e8.png)
- [ ] 官网链接替换为 `http://keepwork.com/official/haqi`
- [ ] 密码找回替换为 `http://keepwork.com/wiki/find_pwd`

**Comment by LiXizhi** [comment]
- [ ] 首页Logo替换为  `Texture/Aries/Login/haqilogo_32bits.png`  
![image](https://user-images.githubusercontent.com/94537/28451940-d2ac2906-6e22-11e7-9869-7535cd69e1e8.png)
- [ ] 官网链接替换为 `http:/keepwork.com/haqi/web`
- [ ] 密码找回替换为 `http://keepwork.com/wiki/find_pwd`

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/28452802-ea15b2f2-6e26-11e7-8d8e-ad080d0bb1ae.png)

**Comment by azothli** [comment]
登录器进入后就是这个界面

![image](https://user-images.githubusercontent.com/22001356/28453069-1598ae10-6e28-11e7-8c02-95bc9aa100c6.png)

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/28454403-baa0968e-6e2d-11e7-97b6-612a1114ad46.png)

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/28459121-cb5b5c46-6e3e-11e7-9163-3bf5400a6502.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28707565-7339b02c-73ab-11e7-8219-7baa519d23a7.png)

![image](https://user-images.githubusercontent.com/25898720/28707593-88bbbfda-73ab-11e7-922a-72230c44a68d.png)

![image](https://user-images.githubusercontent.com/25898720/28711605-b8ad52c6-73ba-11e7-8c4f-39f75b57535c.png)


![image](https://user-images.githubusercontent.com/25898720/28711162-3f3ed9b0-73b9-11e7-961b-872fc487ad5e.png)

![image](https://user-images.githubusercontent.com/25898720/28711527-7227b260-73ba-11e7-92ae-42e0c3e249c7.png)

![image](https://user-images.githubusercontent.com/25898720/28711535-7a920cfc-73ba-11e7-8e3a-b5e087f14c26.png)
