### ISSUE TITLE
KeepWork支付UI设计+前端实现

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#380]

**Comment by onedou** [comment]
@Tibet0312 设计页面是否完成？

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/27823132-a1a8141e-60da-11e7-9318-53bdf2256d7b.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/27851849-35357794-618f-11e7-9647-277b4a8941ed.png)

**Comment by LiXizhi** [comment]
@azothli  @yuki1206  帮我问下哈奇的用户群， 支付一般用什么。 
我们只申请了支付宝和微信是不是就够了。 不需要搞充值卡什么的吧。

**Comment by LiXizhi** [comment]
@azothli 充值成功后， 我觉得可以对我们的其它产品有个关联广告， 例如大赛， Paracraft， 等等。 最好是一个固定的内联页面。可以考虑用`@include` 命令实现。

**Comment by yuki1206** [comment]
实体卡的渠道和占有量已经萎缩，这两种是主流的充值方法，前期足够了，否则小学生也打不了王者荣耀

**Comment by yuki1206** [comment]
可能还需要qq钱包支付，小朋友用得较多。如果要让所有信用卡接入，可以再接个paypal
