### ISSUE TITLE
哈奇后台Server用Keep Work oauth+绑定旧 的米米号，并支持keepwork新用户注册并生成内部数字账号。

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#381]

**Comment by LiXizhi** [comment]
关于一个账号只能绑定一次的逻辑， 我们用下面的方式解决。 
- 新建一个不可删除（cansell=false）价格为0的物品A，表示这个账号是否已经被绑定。 
- KeepWork客户端登录后，检测物品A， 如果A不存在，则购买一个物品A，并设置ClientData为用户keepwork username。
- Server端在绑定用户账号时，检测物品A是否存在， 存在则返回false + ClientData告诉用户次账号已经属于ClientData了。 

## 处理转移NID所有权（TODO 暂不支持）
- 官方：只需要通过后台删除物品A， 则这个账号可以重新绑定。 
- 用户买卖账号： 通过某个付费规则，删除物品A。 再让其它用户去绑定即可。

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/29606557-39381f46-8821-11e7-8944-5adede72575f.png)
