### ISSUE TITLE
【bug】授权管理，我并没有授权，我用分组该账号访问此用户，无法访问

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#385]
![image](https://user-images.githubusercontent.com/28430070/27535219-7f853c3e-5a9c-11e7-9f41-cb55ef0e7742.png)

![image](https://user-images.githubusercontent.com/28430070/27535179-4a126dba-5a9c-11e7-894d-bb7ff1cf1e1c.png)

**Comment by azothli** [comment]
请详细描述

**Comment by LiXizhi** [comment]
@duting1993
