### ISSUE TITLE
重启文档与日志维护脚本

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#386]
将服务器的GIT更新和打包测试等命令更新到：
-
 https://github.com/tatfook/wikicraft/wiki/DeployGuide#%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1%E5%99%A8

## 优化`./start.sh`
- 将上次的XXX_log.txt 移动到 `log/xxx_log_datetime.log`, 每次重启新开一个XXX_log.txt
   - datetime精确到分钟， 方便我们查看Crash Dump 搜索信息等。 
- `log/xxx_log_datetime.ltxt` 中的`<Runtime` grep & append到`log/XXX_error.log`

**Comment by wxaxiaoyao** [comment]
已改
