### ISSUE TITLE
【调整】第三方账户登陆时， 可以新建用户， 此时可以输入已经存在的用户，密码。 

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#389]
【调整】第三方账户登陆时， 可以新建用户， 此时可以输入已经存在的用户，密码。 
提示用户该账号已经注册，可以登录后在设置中心-》账号安全-》账号绑定 中进行设定。

**Comment by wxaxiaoyao** [comment]
这个应该是对吧,  之前是设计成: 不存在的用户用第三方登录后跳到类似注册的账号信息完善页面完成账号注册跟绑定.  这种方式已经写了是可以维持现状的.
