### ISSUE TITLE
【bug】在编辑WIKI时， 不停的有这个请求，每次按回车都有

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#390]
![image](https://user-images.githubusercontent.com/28430070/27716551-bcaff400-5d71-11e7-9945-e9a4d6e499de.png)
![image](https://user-images.githubusercontent.com/28430070/27716557-cafe0d6c-5d71-11e7-9514-04bcc8636ee4.png)

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/27730655-9c01fdca-5dbc-11e7-86e6-d926349204a3.png)

wikiBlockController.js 模块响应编辑器的回车导致不停发请求.   @ZhangKaitlyn 想下有没有更好认识,做不到可以选择性屏蔽解决
