### ISSUE TITLE
私有项目图片的URL要从Markdown中去掉token

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#394]
目前私有网站上传图片时， markdown中的URL中是有`*.png?privatetoken=xxx`的。 这个有什么办法可以不将token写在Markdown中。 而使用当前访问者自己的Token(因为这个Token是可能被Reset的，所以不应该出现在URL中)。

- 1期：数据源中的URL改为`xxxx?privatetoken=visitortoken`, 然后修改MarkdownRenderer, 将所有包含`privatetoken=visitortoken`的URL， 自动替换为privatetoken=[replace with visitors token]。 这样保证不需要Token的link不会被加入private token. 防止用户在
- 2期：项目上传时可以让用户指定保存在某个网站的数据源中， 并且在Browser中记录上次的选择，例如：
     - 数据保存到：
         - [x] 当前网站(XXX网站名)
         - [ ] XXX网站名(公有)
         - [ ] YYY网站名(私有)

@wxaxiaoyao 思考下，上面的方案是否可以？

**Comment by LiXizhi** [comment]
@wxaxiaoyao 
@azothli 

我给出了一个方案。 可以先实现1期，2期李宇需要设计下

**Comment by wxaxiaoyao** [comment]
基于上述方法，已对图片，文件上传做了处理
