### ISSUE TITLE
编辑UI加入站点管理

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#395]
TreeView有几个问题
1. 目前还没有区分私有，公有的Icon
2. 在编辑UI中也可以直接打开网站的设置页面

![image](https://user-images.githubusercontent.com/94537/27759259-6bba7870-5e5e-11e7-985f-273e52aac844.png)
- 这个关闭全部，在打开中已经基本有了， 可以去掉（保留也行）
- 最后可以加个设置按钮， 点击跳到这个网站的设置页面
- 新建目录功能，可以和新建页面合并。例如新建页面时如果输入 `subfolder/test`, 则自动创建subfolder目录。 github就是这样的。 而且GIT内部应该默认也是这样的。 git是不存在目录的。 当目录没有文件时，目录自动消失。

![image](https://user-images.githubusercontent.com/94537/27759276-2d6eaa68-5e5f-11e7-8912-d2638a1b368a.png)
这个-+参考下win10 的目录，是否可以不要这么明显。 
![image](https://user-images.githubusercontent.com/94537/27759279-651faf66-5e5f-11e7-9a59-6831d072f617.png)
这个美术定即可，也可以不改。

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28000151-80d4c4dc-6556-11e7-889d-8cfa6e1e96ec.png)

**Comment by LiXizhi** [comment]
@duting1993   
![image](https://user-images.githubusercontent.com/94537/28097728-88e518fe-66e4-11e7-925e-d4e205d5adb8.png)

鼠标放上去的提示不对

@ZhangKaitlyn

**Comment by ZhangKaitlyn** [comment]
改好了 @LiXizhi

**Comment by LiXizhi** [comment]
@duting1993  从这里点击编辑， 无法查看，或创建分租. @wxaxiaoyao 

![](https://user-images.githubusercontent.com/94537/28097728-88e518fe-66e4-11e7-925e-d4e205d5adb8.png)
