### ISSUE TITLE
编辑其中来回切换页面， 经常前一个页面的内容会出现在后一个页面中

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#398]
编辑其中来回切换不同的页面， 经常前一个页面的内容会出现在后一个页面中。
- 异步调用时要注意，当前页面名，不要将异步返回写入非当前页面中

**Comment by wxaxiaoyao** [comment]
已修改， 复现较难， 无法验证正确性， 应该没有问题。
