### ISSUE TITLE
连接最好显示完整

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#40]
![image](https://cloud.githubusercontent.com/assets/94537/23069769/a8b0d9fe-f563-11e6-95a1-b841b588998c.png)

最好自动变长

**Comment by wxaxiaoyao** [comment]
暂时显示框加长处理， 自动变长可后续优化。ps：这边关闭的bug若感觉没改好，可重新打开或再提，就不一一交流确认啦。
