### ISSUE TITLE
增加命令: @include{MyHeader1}可引用其它markdown文件

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#402]
可以做成一个异步模块
```
    ```@include
    pagename
    ```
```

引用模块另外一个Markdown文件。 比如周报换一个Header头，和整个网站不一样

**Comment by wxaxiaoyao** [comment]
![wvr2sktd85m asxhmi0z7](https://user-images.githubusercontent.com/11922085/27904229-942d7604-626e-11e7-8487-4ab77e91ac3d.png)

被引入页面修改不会实时呈现在引入页面，需要手动刷新。

**Comment by LiXizhi** [comment]
include 的语法如果能简单点，就更好了。 方便我直接敲代码。 

```
     ```@include 
      xxx/yyy 
      ```
```

- 如果没有slash 可以直接默认加wiki/js/
- 里面的内容可以不用json, 直接plain text

**Comment by wxaxiaoyao** [comment]
可以简写@include   可以直接plain text（url）    url为keepwork用户页地址， 暂不支持跨域
