### ISSUE TITLE
【需求】将我们已经做好的模板中的模块添加到我们的模块库

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#407]
分类添加一个排版
然后我们这么多没添加的都填过来。
现在太多美容没有添加到模块了

填过来的内容，替换美术图片与描述文字
@Tibet0312 提供缩略图

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28000834-fab72124-655a-11e7-95a4-0180b1fb6364.png)
