### ISSUE TITLE
哈奇服务器迁移

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#411]
<log_server host="http://tmlog.paraengine.com"/>
<file_server host="http://tmland.paraengine.com"/>
- [ ]  DNS 都指向121.14.117.236
- [ ]  内网CI， CDN的更新源站指向新的服务器.
- [ ]  family land 内容测试

暂定2017.8.1 全天停服

**Comment by HYang21** [comment]
Is everything okay?

**Comment by LiXizhi** [comment]
it is ok. pending for some other tasks in WIP.

**Comment by duting1993** [comment]
@azothli
