### ISSUE TITLE
【请勿关闭】Keepwork开放平台注册，有需求请留言

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#415]
开发文档(API)： http://keepwork.com/official/open

请需要接入平台的组织按照以下格式留言：
- 申请人/申请组织：
- 申请人邮箱：用于我们发送Client id/client secret
- AppName：用于显示
- callback url：回调地址
- App描述：如果有演示请提供链接

**Comment by xiaop1ng** [comment]
申请人：简超平
申请人邮箱：784516419@qq.com

**Comment by LiXizhi** [comment]
App描述：如果有演示请提供链接  @xiaop1ng 

@azothli 关注并回复

**Comment by elvinzeng** [comment]
# 申请应用程序clientId和clientSecret
***Company:*** 爱致科技 
***Site:*** 共享制造平台
***Url:*** http://3dprint.idreamtech.com.cn

**Comment by chenliu098** [comment]
申请clinetid 和clientSecret
Company: 上海配天智慧云
email: leo.chen@peitian.com

**Comment by Romeoooo** [comment]
申请clinetid 和clientSecret
Company: 成都配天智能技术有限公司
email: peng.zhang@peitian.com

**Comment by wxaxiaoyao** [comment]
需填写产品名称  公司名称  邮箱

**Comment by Romeoooo** [comment]
产品名称：Adas
公司名称：成都配天智能技术有限公司

2017-07-31 8:43 GMT+08:00 wxa <notifications@github.com>:

**Comment by Romeoooo** [comment]
@wxaxiaoyao

**Comment by WXDYGR** [comment]
申请clinetid 和clientSecret
Company: 深圳市得道健康管理有限公司
email: jianhao.liu@ewqk.com

**Comment by onedou** [comment]
此issue已过时，将关闭
