### ISSUE TITLE
@app 命令iframe嵌入oAuth APP

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#416]
Facebook这个是怎么做到的？我们也这样做即可。 只要登录了， 里面的Iframe直接也登陆了。 
也许还真的需要做一个@app 命令
```
@app 
url="http://www.paracraft.cn/"
oauthcallback="/callback"
```

爱致科技的同学研究下， 我们这里可以配合开发。 
里面是zynga.com的URL
我并没有点任何按钮， 直接iframe里面的zynga.com就登录了。 

![image](https://user-images.githubusercontent.com/94537/27823396-897c9c2e-60db-11e7-9e81-2803e32e936d.png)

![image](https://user-images.githubusercontent.com/94537/27823415-9660eb8e-60db-11e7-9bf8-e5a8c044206a.png)

**Comment by elvinzeng** [comment]
@App命令是指什么？是keepwork的编辑器上插入这个标记你们就会执行特定的动作吗？那解释命令是在客户端做的还是打算在keepwork的服务端做？

**Comment by LiXizhi** [comment]
这个keepwork网站的Mod命令。 是服务器端写， 用户可以使用的。
