### ISSUE TITLE
git.keepwork.com支持用keepwork.com第三方登录。

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#418]
https://docs.gitlab.com/ce/api/users.html#user-modification

- extern_uid - External UID
- provider - External provider name

管理员是可以修改用户的第三方登录ID的。 所以keepwork.com可以在绑定内部数据源时，将自己作为第三方，加入到此`gitlab_rls_XXX`外部登录上。 这样我们就可以在
git.keepwork.com/users/sign_in 页面上加入一个keepwork.com的第三方登录按钮。 

![image](https://user-images.githubusercontent.com/94537/27826813-23b05014-60e7-11e7-8f8f-dd9986f4cbec.png)

gitlab doc is here:
- https://docs.gitlab.com/ce/integration/omniauth.html

**Comment by LiXizhi** [comment]
@Xuntian  @wxaxiaoyao  这个可行么？
目前集团大多数公司都选择了gitlab作为Issue Board管理，但是用户系统和keepwork.com又不统一非常不方便。有了这个就不需要用户一定是用tatfook.com的邮箱重新注册了。 keepwork.com一个账号就可以登录gitlab了。 

gitlab 9.3 官方已经开始支持中文， 估计再等1个月， 就可以全面中文了。

**Comment by LiXizhi** [comment]
我找到了一个不需要二次开发的解决方案：
- gitlab配置中开启github登陆（但是禁用注册）
- KeepWork中绑定github登录时，也将github uid 存到gitlab上。 这样gitlab就可以直接用github登录了。


https://docs.gitlab.com/ce/api/users.html#user-modification
- extern_uid - External UID
- provider - External provider name

@wxaxiaoyao @Xuntian

**Comment by LiXizhi** [comment]
这样KeepWork.com用户也可以直接使用gitlab的所有功能了。 最重要的是Issue Boards. 用于大富的项目管理

**Comment by LiXizhi** [comment]
Liyu(310984)  1:03:11 AM
不过现在gitlab是一个封闭的小环境，因为只能用pe tafook的注册
这样就等于是开放环境了？ 还是指提供给部分keepwork用户使用

LiXizhi(lixizhi@yeah.net)  1:14:00 AM
这样做是可以通过KeepWork的代码控制谁可以访问gitlab环境。 而不是用Email域名控制了

**Comment by azothli** [comment]
不过现在gitlab是一个封闭的小环境，因为只能用pe tafook的注册
未来gitlab的Issue Boards是准备发放使用， 还是只提供给部分keepwork用户使用（公司内部）
或者是可控范围（额外附加vip用户）

**Comment by LiXizhi** [comment]
这样做是可以通过KeepWork的代码控制谁可以访问gitlab环境。 而不是用Email域名控制了

**Comment by azothli** [comment]
那也就是说，后续有什么使用，是通过我们的一个专门的管理接口来处理。
这里是一个Issue Boards的白名单，名单内的才允许

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/27839681-b4b00b48-6125-11e7-94a6-183743ec55c1.png)

这里我已经加好了。目前git.keepwork.com已经可以用github登陆。只要在keepwork上开启下绑定即可
