### ISSUE TITLE
修改的网页，应该自动保存到缓存

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#42]
网页只要修改了， 应该随时保存到本地缓存
并在用户切换页面时提示用户是否保存。 
否则很容易忘记修改。 

参考VS Code，   修改中的页面可以文件名后面显示*

filename *

**Comment by wxaxiaoyao** [comment]
目前页面渲染是在停止编辑后1s开始渲染(防止用户编辑速度较快，一直编辑一直渲染影响性能和体验)， 现在此同时提交修改到服务器，以实现自动保存。 因为编辑后1s自动保存，所以无需加*表是未保存状态。以按此方式实现。
