### ISSUE TITLE
【bug】keepwork.com作品集，作品长廊，每页展示的数目不一样。

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#422]
![image](https://user-images.githubusercontent.com/28430070/27851662-5cca8886-618e-11e7-9c54-121390127f7c.png)
![image](https://user-images.githubusercontent.com/28430070/27851697-8632db10-618e-11e7-9d10-3d5491e4161a.png)

**Comment by ZhangKaitlyn** [comment]
返回的作品列表要过滤 新手教程 @wxaxiaoyao
