### ISSUE TITLE
【bug】更新后，第一次输入网址，dev，keepwork，test，回车，之后，没有用户，却是登陆状态，需退出之后，才有登陆按钮，注册按钮

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#423]
![image](https://user-images.githubusercontent.com/28430070/27852435-b718129c-6191-11e7-953d-1193803c0f00.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/27869996-36fb1634-61d4-11e7-9bbc-ff0d9ca8a597.png)
Token变化了,导致认证失败了， 此时Client应该立即重新认证。 
这个问题最好明天早上能修复下，然后尽快发布Fix。 不然已经登录的用户会不清楚怎么办。 
我将我一个浏览器留着等这个问题的修复。
