### ISSUE TITLE
【bug】大赛，上传作品，最新上传， 只显示了3个

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#432]
![image](https://user-images.githubusercontent.com/28430070/27907386-07e1890e-627a-11e7-8db6-a2b4ba6f8d02.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/28008448-2818ebaa-658a-11e7-8d83-846aac40354e.png)
在大赛作品展示部分增加 pageSize 配置
