### ISSUE TITLE
【需求 】定义一下视频的快捷键

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#434]
![image](https://user-images.githubusercontent.com/28430070/28000931-881cd4fa-655b-11e7-924e-48582b29223a.png)

**Comment by azothli** [comment]
alt+v 吧

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28297919-036fe37a-6ba3-11e7-90d6-68b96a678c29.png)

**Comment by azothli** [comment]
@ZhangKaitlyn  功能是否实现？

**Comment by duting1993** [comment]
该功能未实现
