### ISSUE TITLE
【bug】设置中心-我的状态，组织、关注、作品，里 显示的内容不对

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#435]
![image](https://user-images.githubusercontent.com/28430070/28001118-c9e1424e-655c-11e7-9a24-39941749b747.png)

![image](https://user-images.githubusercontent.com/28430070/28001217-9348ed58-655d-11e7-8d31-1af79234084a.png)
![image](https://user-images.githubusercontent.com/28430070/28001236-b3b45c44-655d-11e7-9c5d-d6452140ac41.png)

**Comment by LiXizhi** [comment]
@duting1993 @Sandu1213

**Comment by Sandu1213** [comment]
![question](https://user-images.githubusercontent.com/21214285/33254237-afac826e-d382-11e7-99cd-be27cf343ac9.png)
