### ISSUE TITLE
【bug、需求】大赛，组织里，查看更多，目前，无法点击

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#439]
![image](https://user-images.githubusercontent.com/28430070/28048989-f2298822-6626-11e7-8fb4-51adc68e89c2.png)
组织大赛里要包括查看更多的页面

**Comment by ZhangKaitlyn** [comment]
- 若是之前建的大赛或组织网站，需要新建一个 _more页面，内容放
```@wiki/js/workslist
{
"moduleKind":"game",
"pageSize":"8"
}
```
![image](https://user-images.githubusercontent.com/18642919/28109850-153f0484-6723-11e7-871a-8158bbdc1586.png)
- 今天的代码更新发布后新建的网站，新建过程中选择大赛模板或者组织模板会自动创建_more页面
