### ISSUE TITLE
【需求】新增模块 对应 增加命令: @include{MyHeader1}可引用其它markdown文件 

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#448]
模块名：
引用markdown

**Comment by wxaxiaoyao** [comment]
https://github.com/tatfook/wikicraft/issues/402
已经有了

**Comment by azothli** [comment]
功能有了，这个是要模块~

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/28452077-88179a78-6e23-11e7-9b50-84c5c8263417.png)
![image](https://user-images.githubusercontent.com/18642919/28452084-92665942-6e23-11e7-9b36-d687e3d06afc.png)
