### ISSUE TITLE
【需求】paracraft.cn的帮助内容转到keepwork

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#449]
official下创建paracraft的专用网站，放这个里面。
http://keepwork.com/official/paracraft   现在已经被作品网站占用了，在里面做，index替换掉

**Comment by azothli** [comment]
西峙说可以弄个工具自动转一下，雯文在手动检查+优化

**Comment by LiXizhi** [comment]
@DreamAndDead

**Comment by DreamAndDead** [comment]
https://github.com/LiXizhi/ParaCraft/wiki

http://wikicraft.cn/Paracraft/VideoTutorials

**Comment by DreamAndDead** [comment]
将wiki中的pages转到了 keepwork offical 下
- 替换 [[ ]] github独有的标签
- 替换video为模块

可以帮看下有没有需要修改的地方
@zhsbwzy 

vt_block_memory.md 和 vt_teleport_stone.md 需要注意

**Comment by DreamAndDead** [comment]
发现一些问题   部分链接使用 http://wikicraft.cn/Paracraft/ 绝对地址，需要改为相对地址

**Comment by DreamAndDead** [comment]
已经修改

@zhsbwzy 可以再确认一下没有任何链接会链接到 wikicraft.cn 上去
