### ISSUE TITLE
官网入口+产品特性+帮助

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#451]
KeepWork的官网首页增加
- KeepWork/Paracraft/NPL的产品特性
- Keepwork/paracraft 帮助网站

参考： https://unity3d.com/unity  features page

**Comment by LiXizhi** [comment]
http://keepwork.com/intro/keepwork

@Tibet0312 @ZhangKaitlyn

**Comment by LiXizhi** [comment]
ＯＫ　统计那个位置，是其它内容
还有 这里图片的替换
有几个问题：


1. 增加功能介绍
2. 最主要的是右侧的滚动条逻辑和习惯不一致， 最好能去掉滚动条
3. 手机版

![image](https://user-images.githubusercontent.com/94537/29025633-5434aebe-7baa-11e7-95b2-62c26dfab3b7.png)

有一个特殊的分辨率显示不正常

![image](https://user-images.githubusercontent.com/94537/29025627-48b3fb62-7baa-11e7-8f9d-cd414dc99123.png)
还存在

图片背景沾满左侧， h1文字，最好能和下面的h2对齐. 
![image](https://user-images.githubusercontent.com/94537/29025611-2b4dce54-7baa-11e7-87b7-57e5630c8289.png)

@ZhangKaitlyn   尽量都可以修复

**Comment by LiXizhi** [comment]
1.  导航栏中的帮助页面建立一个独立的网站，内部人员可随时编辑。
![image](https://user-images.githubusercontent.com/94537/29238958-da55f918-7f73-11e7-9735-1da1c55ee082.png)
 @azothli 
2.  登录后个广告页面去掉。 
![image](https://user-images.githubusercontent.com/94537/29238966-13180c8c-7f74-11e7-98c9-4a597d127bc3.png)
改成和首页一样。 但是由于已经登录，将登陆框改为观看新手教学视频。内容如下：
```
   - 第一次使用KeepWork? 观看教学视频
     - 视频1: KeepWork是什么？
     - 视频2: 如何用KeepWork写网站？
```

3. 
![image](https://user-images.githubusercontent.com/94537/29238995-b7681a20-7f74-11e7-9dc9-1e47b62714c2.png)  这里的LOGO改为按钮，取消下拉框 （待定：讨论是否OK？因为MOD已经在应用中心中有了，这里没有必要了）
   - 如果没有登录， 直接去首页
   - 如果已登录， 直接去用户中心（不然每次点2次去用户中心不方便）。 
   - 导航栏对于登录用户增加:`功能`按钮：   ![image](https://user-images.githubusercontent.com/94537/29239010-1e2a4224-7f75-11e7-9190-0469b1c216be.png)  让登录用户也能看到产品特性和视频教程。

**Comment by LiXizhi** [comment]
大家对首页有什么意见都可以发表。

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29350846-b8bd009a-8292-11e7-9bf2-e41cb0dcd496.png)

点击观看视频页面：

![image](https://user-images.githubusercontent.com/25898720/29350861-cb0e5848-8292-11e7-9ec6-df96526305fd.png)
