### ISSUE TITLE
【需求】开启qq聊天mod

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#453]
考虑加一个在线QQ客服的Mod。 解决各种客服的问题。 
http://www.cnblogs.com/hafiz/p/5811205.html

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28299425-ba79a4b8-6bab-11e7-8dc6-ae65eb051607.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/28348395-650d7fda-6c6f-11e7-8a75-98ba775c2ac0.png)
会固定在右下角
模块代码：
 ```@wiki/js/chat
 {
 "moduleKind":"qqChat",
 "message":"客服中心",
 "qq":"825973524"
 }
 ```
