### ISSUE TITLE
页面下方加入Powered by NPL

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#455]
![image](https://user-images.githubusercontent.com/94537/28216207-59d6e460-68e3-11e7-9067-e190d35c4092.png)

网站右下角的更新时间会被人误解为网页的更新时间。

将更新时间这里改为：[_Powered By NPL_](https://github.com/LiXizhi/NPLRuntime/wiki/)

然后鼠标放上去时显示：`网站更新于: 2017XXXXX`  目前的更新时间。

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28257539-3ad91f98-6afe-11e7-8cb0-9ebb093363ce.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/28399909-959395ee-6d42-11e7-8336-3129241af13d.png)

点击后， 没有跳转 https://github.com/LiXizhi/NPLRuntime/wiki/

@ZhangKaitlyn

**Comment by ZhangKaitlyn** [comment]
dev上更改完成
