### ISSUE TITLE
打开LFS in git.keepwork.com

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#456]
https://docs.gitlab.com/ee/workflow/lfs/lfs_administration.html

@wxaxiaoyao  支持下大文件，上海团队下周需要。

**Comment by wxaxiaoyao** [comment]
和上海团推沟通过没有问题， 这个lfs好像是处理G级别的上传， 它们的问题应该不是这个， 可能是张磊那次上传不了大点文件的问题， 应该是http缓存的设置太小的问题， 上次有调大。 这个暂时就不开启，
