### ISSUE TITLE
entitysign字体大小+3d显示位置参数能否开放？

### ISSUE THREAD

**Issue by yjstcb** [tatfook/wikicraft#459]
@LiXizhi 
《纸》项目中我们想修改告示牌的模型，但是遇到了字体显示的问题（由于模型较大，字体嵌入到了模型里了），能否将entitysign的字体相关的参数开放修改？

**Comment by LiXizhi** [comment]
放入 paracraft 的issue 看板吧。 这里是keepwork团队的。
