### ISSUE TITLE
【需求】手机绑定功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#461]

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/28348490-daae0c8c-6c6f-11e7-9dd0-856c21994ae0.png)
绑定后按钮变成【解除绑定】
需要验证原邮箱或者手机，才能解除
然后可以用新的进行绑定。

**Comment by LiXizhi** [comment]
管理员可以不用验证，其它需要验证才能解除。 我建议这个Issue拆分成多个Issue。 
@azothli @wxaxiaoyao 
解除绑定单独Issue
