### ISSUE TITLE
h1+image 支持文字在图片上，能做到么？

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#464]
# 这里是h1  后面加了图片 ![image](https://user-images.githubusercontent.com/94537/28424797-21389320-6da1-11e7-99f5-14b94b42a67f.png)

```
# 这里是h1  后面加了图片 ![image](https://user-images.githubusercontent.com/94537/28424797-21389320-6da1-11e7-99f5-14b94b42a67f.png)
```

能否显示成图片占满，然后上面写文字。 文字在左下方。

**Comment by ZhangKaitlyn** [comment]
@LiXizhi @azothli 这样效果是否可以？
![image](https://user-images.githubusercontent.com/18642919/28506372-7213155e-705d-11e7-9a7b-459b26da6118.png)
[效果](https://codepen.io/ZhangKaitlyn/pen/ZyPQKv)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/28512208-7d24357e-7083-11e7-97f0-43fce99fbab2.png)

**Comment by LiXizhi** [comment]
OK good. but the way to enable it may conflict with other theme class?

**Comment by ZhangKaitlyn** [comment]
类名目前没有被占用，那我加下 wiki 前缀防止被占用？改成wiki-bg-title?
