### ISSUE TITLE
[调整]完善top功能栏

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#47]
当前版本与原型偏差较大，收藏、历史、分享等功能缺失
![image](https://cloud.githubusercontent.com/assets/22001356/23149339/3742a0d4-f826-11e6-91c3-c9ae20001e0c.png)

**Comment by caoyongfeng0214** [comment]
分享需用公司资料去注册。请李宇去将常见的几个平台都注册一下吧。如：微信、朋友圈、新浪微博
