### ISSUE TITLE
【bug】修改图片无法保存，提示信息如图二

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#470]
![image](https://user-images.githubusercontent.com/28430070/28452679-5e66d628-6e26-11e7-87fc-12f635d26d40.png)
![image](https://user-images.githubusercontent.com/28430070/28452686-6c4b09ee-6e26-11e7-8e2e-35b53dd084a0.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/28514375-5b07a2c4-708c-11e7-9f50-cf929ce2c77c.png)
![image](https://user-images.githubusercontent.com/18642919/28514274-04ee843e-708c-11e7-91e4-f9e80e57412b.png)
![image](https://user-images.githubusercontent.com/18642919/28514342-3d3bd83c-708c-11e7-9075-f14bb77d317d.png)
