### ISSUE TITLE
文档上传Mod

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#485]
上传任意文档(doc, ppt, pdf)，并自动转为`md+jpg|png`

![image](https://user-images.githubusercontent.com/94537/28658087-4359da46-72dc-11e7-8930-64f93cf07c49.png)

支持的格式包括`doc, docx,pdf, ppt, pptx`

用户在点击`全部上传`前，数据是保存在一个临时的位置(提供临时url即可)， 可以让用户预览。
用户点击`全部上传`, 则`前端js`自动将相关文件， 逐个上传。

> 可以让用户等1小时，但是要告诉用户前面有多少文档在排队中, 类似youtube视频上传， 也基本要等很久

**Comment by LiXizhi** [comment]
```
天玑-杨宗泽(295501137)  2:51:32 PM
我们测试过转换比较大的pdf需要好几个小时
几百兆的pdf
我转了整整一个下午
天玑-杨宗泽(295501137)  2:52:09 PM
纯印影版的
天玑团队-杨昌玉(453283491)  2:52:27 PM
pdf先需要ocr识别，识别后又转换的。
这样转出的效果是html中的文字可选。
加上ocr识别更慢
```

- 可以设置一个限制， 超过多少时间或空间， 这个功能就不提供给用户了。 
- 比如github这个CI限制， 免费用户是1小时单核， 付费用户2小时多核

**Comment by LiXizhi** [comment]
1、keepwork检索对接接口
     http://keepwork.com/sangfor123456/kwquestions/detail_interface 

2、keepwork 上传文件 uploadfileMod 录屏下载地址
     烦请下载确认和需求是否一致。

   链接：http://pan.baidu.com/s/1dFBzPdR 密码：tcql


3、keepwork上下文Mod 示意图（假数据）
 
![Uploading image.png…]()

 
        
![Uploading image.png…]()

4、下一步工作
        1） 真实数据，待大富前端上传；
        2）接口待深圳大富的前端对接验证。

**Comment by tianjiyang** [comment]
#uploadMod上传展示效果，麻烦香安兄、李总确认下。

1、图片预览展示效果
![Uploading image001(08-25-11-00-16).jpg…]()

2、MD展示效果
![Uploading image002(08-25-11-00-16).jpg…]()
 
3、Gitlab上传地址
图片的Gitlab地址：http://git.keepwork.com/gitlab_www_test/keepworkdatasource/raw/master/test_files/%E5%A4%A7%E5%AF%8C%E9%9B%86%E5%9B%A2%E7%AE%80%E4%BB%8B32221.png 
md的Gitlab地址：http://git.keepwork.com/gitlab_www_test/keepworkdatasource/raw/master/test_files/%E5%A4%A7%E5%AF%8C%E9%9B%86%E5%9B%A2%E7%AE%80%E4%BB%8B3222.md

**Comment by tianjiyang** [comment]
李总需求点确认：
![qq 20170825105633](https://user-images.githubusercontent.com/31032856/29698241-b45f1c9a-8986-11e7-8702-169233c6f0ea.png)

**Comment by tianjiyang** [comment]
李总需求点：可以将Word， HTML从裁剪版，自动转MD。 UI是次要的。

李总，我们这边讨论下。针对您的剪贴板的需求，可以采取下面的步骤：
步骤1：将待拷贝的内容，拷贝到本地，存储为对应格式的文件（pdf，ppt 、pptx、doc、docx）；
步骤2：将存储的文件上传，走我们现在已实现的转换流程；
步骤3：转换后提交gitlab。
您看下如何？

**Comment by LiXizhi** [comment]
你们可以调研一下么？ 例如docs.google.com 
的ctrl+c/v是如何做的？ 如果不可行， 这个功能就不做了

**Comment by lbairong** [comment]
啊啊啊

**Comment by tianjiyang** [comment]
收到，我们这边调研下。

**Comment by lbairong** [comment]
1.1 企业简介
     深圳市大富科技股份有限公司成立于2001年，是一家集产品研发、生产和销售为一体的国家级高新技术企业，2010年10月26日于深圳市证券交易所挂牌上市（股票代码300134）。
    公司致力于成为全球领先的射频解决方案提供商，通过不断完善横向通用技术的综合融通能力，强化自主创新的研究开发和纵向一体化精密制造的能力，最终成为端到端网络工业技术提供商。公司总部位于深圳市宝安区，在国内外大中型城市设有十余处研发中心及生产基地，与华为、爱立信、阿尔卡特-朗讯、博世、康普等全球知名企业建立了稳定的合作关系。
    公司拥有一流的研发中心，技术力量雄厚，研发人员逾500名。拥有完整自主产权的技术优势，共有技术专利逾300余项。
    公司愿景：
公司致力于成为精密机电部件和产品的设计及制造商，工业装备设计和制造商，端到端的网络工业技术提供商(工业4.0解决方案提供商)，成为自然生态的伙伴，可持续发展的构成要素，天人合一的践行者。
    企业核心价值观：
持续遵循规律、不断科学创新、精诚团队合作
拥有核心能力、成为行业领先、永恒良性发展
    环境方针：
保护地球环境，建设绿色文化是深圳市大富科技股份有限公司的基本环境理念，我们承诺：
一、实施有效的环境管理体系，制定实现并定期评审环境目标、指标，并持续改善；
二、遵守国家和地方的环保法律和其它要求；
三、推行清洁生产、预防污染，逐步引用有利于环保的材料、装置及工艺技术；
四、开展全员节能降耗活动，提高废物的循环利用，努力实现资源、能源消耗最小化；
五、本方针传达到所有为组织工作或代表它工作的人员，并通过教育培训提高其环保意识和技能；
六、本方针可为公众所获取，并寻求相关方的监督、理解和协作。



1.2 企业荣誉
法人代表、董事长孙尚传先生的荣誉
2007年，荣获2006年度“深圳市产业发展与创新人才奖”
2008年，荣获2007年度“深圳市产业发展与创新人才奖”
2009年，荣获“深圳市地方级领军人物”称号
2009年，荣获2007-2008年度“深圳市宝安区科技创新奖区长奖”
2011年，荣获安徽省“蚌埠市2010年度工业发展贡献奖”
2011年，被蚌埠市第十三届运动会组委会授予“热心体育发展事业先进个人”称号
2011年，荣获第三届“蚌埠市十佳科技工作者”称号
2012年，荣获“2011安徽年度经济人物 ”称号
2012年，荣获“安徽省劳动模范”称号
2012年，荣获“2009-2011年度深圳市产业发展与创新人才奖”
2012年，荣获宝安区百优人物称号
深圳市大富科技股份有限公司的荣誉
2005年
04月，被认定为“外商投资先进技术企业”
05月，被认定为“深圳市高新技术企业”
2006年
07月，被评为“2005年度深圳市工伤预防先进单位”
2008年
10月，被评为“2008德勤高科技、高成长中国50强”
12月，被评为“2008德勤亚太地区高科技高成长500强”
12月，被认定为“国家级高新技术企业”
2009年
04月，荣获华为“2009年一季度供应保障专项奖”
05月，被评为“2008年宝安区纳税百强企业”
05月，被评为“宝安区首批自主创新型优势科技企业”
08月，被评为“2008年深圳市劳动关系和谐企业”
11月，荣获华为“2009年度杰出核心合作伙伴”奖
11月，被认定为“深圳市第一批总部企业”
12月，荣获“2009德勤亚太地区高科技高成长500强”称号
2010年
03月，荣获“深圳市成长型中小企业500强”称号
04月，被认定为“宝安区开放性研究开发基地”
06月，通过“深圳市市级研究开发中心（技术中心）”认定
07月，被认定为“宝安区第一批总部企业”
07月，被认定为“深圳市大企业直通车企业”
12月，荣获“2010德勤亚太地区高科技高成长500强”
12月，荣获华为“2010年度杰出核心合作伙伴”奖
2011年
01月，被评为“博士后创新实践基地”
06月，荣获“2010-2011年中国通信产业榜通信设备技术供应商50强”称号
07月，荣获“2010中国创业板上市公司市值20强”称号
07月，被认定为深圳市“宝安区2011年知识产权优势企业”
10月，被评为“2011中国创业板最具投资价值前10名”
10月，被认定为“国家火炬计划重点高新技术企业”
10月，通过国家高新技术企业认定复审
10月，荣获“宝安区纳税百强企业”称号
10月，荣获“宝安区工业百强”称号
11月，荣获华为“2011年度杰出核心合作伙伴”奖
11月，被认定为“宝安区战略性新兴产业领军企业”
12月，被认定为“宝安区百家自主创新型优势科技企业”
2012年
04月，被评为“深圳市2011年度知识产权优势企业”
10月，被评为“2011年度宝安区工业百强企业”、“2011年度宝安区民营百强企业”、“2011年度宝安区纳税百强企业”、“宝安区自主创新型优势科技企业”、“宝安区战略性新兴产业领军企业”
12月，荣获华为“2012年度杰出核心合作伙伴”奖
2013年
06月，被评为“深圳市2013年度知识产权优势企业”
12月，荣获华为“2013年度杰出核心合作伙伴奖”
12月，荣获宝安区科学技术奖
 安徽全资子公司——安徽省大富机电技术有限公司的荣誉
2010年
04月，被评为怀远县“2009年度工业企业纳税十强企业”
11月，被认定为“国家级高新技术企业”
12月，荣获“蚌埠市自主创新示范工程”奖
2011年
04月，被评为“蚌埠市2010年度先进单位”
10月，被蚌埠市第十三届运动会组委会授予“蚌埠市体育发展杰出贡献单位”称号
11月，技术中心被认定为省级企业技术中心
2012年
02月，荣获“2011年度蚌埠市工业发展贡献奖”
02月，被评为“2011年度和谐劳动关系示范企业”
12月，被评为“2011年度蚌埠市劳动保障诚信示范单位”
12月，荣获“ 安全生产标准化三级企业（机械）”
2012年
1月，被评为“蚌埠市优秀民营企业”
12月，2011年度蚌埠市劳动保障诚信示范单位
12月，安全生产标准化三级企业（机械）
2013年
1月，被评为“蚌埠市优秀民营企业”

**Comment by tianjiyang** [comment]
![111](https://user-images.githubusercontent.com/31032856/29761281-264ebaf6-8bfb-11e7-91ff-41e489a656c6.png)
`
![112](https://user-images.githubusercontent.com/31032856/29761283-2bbbafb2-8bfb-11e7-9afc-7099132c8d87.png)
`
李总是这个意思吗？如上图：
内容从本地或者其他网页拷贝，然后我们对内容进行格式转换，转换后的md再提交gitlab吗？
