### ISSUE TITLE
【调整】编辑器/添加链接

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#49]
随着用户输入，增加站内自动搜索功能
提供方便的站内地址的引用方式

**Comment by wxaxiaoyao** [comment]
![d6uafb n_t3w5a5 w me q](https://cloud.githubusercontent.com/assets/11922085/23250567/ac6cf412-f9e4-11e6-8132-d491e261f7c8.png)

![4m8i nouy 14t39li r k](https://cloud.githubusercontent.com/assets/11922085/23250571/b1ef432c-f9e4-11e6-9267-f1576d1d3717.png)
 
已修改如上图
