### ISSUE TITLE
【bug】交易所 的所有商品 无法购买

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#490]
![image](https://user-images.githubusercontent.com/28430070/28701134-9afebfc8-7386-11e7-94ce-7eb58ccde660.png)

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/28722324-ea162a92-73e5-11e7-997e-02d22aa1d8a8.png)

可能确实时被抢购了， 你试试其他的吧。 我这里可以
