### ISSUE TITLE
安全相关

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#493]
网络安全相关的需求

- [x] KeepWork TableDB的异地备份
- [ ] git.keepwork.com 数据源的异地备份: 可以只备份一年内的活跃项目，看下gitlab是否有现成方案

@DreamAndDead  请补充

**Comment by 243533** [comment]
各位好，以后这些bug可以不要抄送给我么？谢谢！




发自网易邮箱大师
在2017年07月28日 14:43，Li, Xizhi 写道：

网络安全相关的需求

KeepWork TableDB的异地备份
git.keepwork.com 数据源的异地备份: 可以只备份一年内的活跃项目，看下gitlab是否有现成方案

**Comment by DreamAndDead** [comment]
- [ ] 周期性备份关键数据
备份数据库中的业务数据，防止数据丢失；
经常进行备份恢复的测试，防止进入备份了数据却无法恢复的困境；
（optional）备份服务器应用的配置数据，方便快速进行服务的迁移；

- [ ] 关闭多余的服务，只保留必要的服务
每个服务都有自己的漏洞存在，一台机器运行的服务越少，被侵入的机率就越小。
线上环境的服务器应该只运行服务业务的进程如web server, database

- [ ] 端口控制
与**关闭多余服务**类似，只允许服务器对外暴露必要的端口，减少被攻击的渠道

- [ ] 修改默认口令
多数服务初始安装之后，都会提供默认用户与默认口令，如mysql的 -u root -p <null>。
所有的服务都要修改修改/禁止默认用户口令

- [ ] 使用加密传输(ssh)
明文传输网络包容易被抓包嗅探，暴露关键信息
使用加密协议包括但不限于
- 用 ssh 代替 rsh
- rsync 务必加上 -e ssh 选项
- https 代替 http
- sftp 代替 ftp

- [ ] root口令脆弱
所有的root口令都是一样的。。。一但一个被暴露，所有的服务器都会受牵连

- [ ] 访问服务器的用户权限
目前提供的服务器，大家全部都使用root来登陆访问，这是非常危险的。
应该提供多个普通用户，必要时用sudo来获取权限

- [ ] 个人本机安全防护
有这样一种情况，用ssh连接远程服务器每次都要输入密码，觉得乏味的人就会用ssh-copy-id，将自己加入服务器的认证名单，这样每次启动ssh连接的时候，就不需要再输入密码。
这样带来了危机，如果个人的电脑被侵入，侵入都也就变相取得了服务器的控制权。
包括但不限于
- 不要用ssh-copy-id在服务器加入自己的PC
- 电脑帐户定义自己的密码
- 开启防火墙软件

- [ ] 公司内网防火墙
关联**个人本机安全**项，保护连接服务器的终端，就是保护了服务器

**Comment by LiXizhi** [comment]
docker 相关， CI/CD中涉及的支付密码，APP secret key 管理等。 @DreamAndDead

**Comment by DreamAndDead** [comment]
@LiXizhi  嗯嗯，我疏忽的的点 :+1: ，我学习了解下，再加入细节到这里

**Comment by HYang21** [comment]
Super!

**Comment by DreamAndDead** [comment]
#562

**Comment by wxaxiaoyao** [comment]
七牛文件上传，模仿客户端一直上传， 需做日志警报
