### ISSUE TITLE
【bug】按参赛2v2 结果进的是1v1匹配界面，参赛状态是错的

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#495]
![image](https://user-images.githubusercontent.com/28430070/28706583-898ac040-73a7-11e7-849c-720d73c5b134.png)
![image](https://user-images.githubusercontent.com/28430070/28706597-9f9a0706-73a7-11e7-8b16-3b1a306d0eae.png)
![image](https://user-images.githubusercontent.com/28430070/28706633-b7b715ea-73a7-11e7-924e-0725a5ced42a.png)

**Comment by azothli** [comment]
最近没听到类似的问题
