### ISSUE TITLE
导航栏与应用中心

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#499]
需求： 目前大富的所有应用需要整合到KeepWork平台上， 形成统一入口，所有应用也可以有自己的独立网站

解决方案：最上方导航栏，仅对网址为`/wiki/开头或只有用户名的网页（/username）`做调整如下。 
      受影响的页面主要是：`首页，用户主页，设置中心，网站管理`等页面

![image](https://user-images.githubusercontent.com/94537/28744345-597f7ac2-7491-11e7-8dda-b0deb565896b.png)

应用中心设计稿

[keepwork.zip](https://github.com/tatfook/wikicraft/files/1184890/keepwork.zip)

![image](https://user-images.githubusercontent.com/94537/28744338-38f29014-7491-11e7-804d-879af317f5e0.png)

上面图片点击后，看放大图， 以上是设计草图。

@Tibet0312 @azothli @ZhangKaitlyn 

[keepwork.zip](https://github.com/tatfook/wikicraft/files/1184891/keepwork.zip)

**Comment by LiXizhi** [comment]
> 孙总要求 8月5日（月会）前将个模块将APP汇总到KeepWork，给他一个演示。 

请各模块负责人，将你们的网站URL， 留言在Issue中，方便我们的设计师放入应用中心里面。 例如：

- http://www.paracraft.cn/

- http://keepwork.com/paracra/3dcampus 
- http://keepwork.com/paracra/logitow 

- http://keepwork.com/idreamtech/mysite3dprint
- http://keepwork.com/idreamtech/mysitezysy

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/28814627-edba0108-76d0-11e7-96a6-e0e6200e5e0d.png)


效果图，内容待补充

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/28820853-c5269cd2-76e5-11e7-8eb4-95d8b7f7e719.png)

**Comment by Tibet0312** [comment]
没有相关的logo，暂时占位

![image](https://user-images.githubusercontent.com/25898720/28856203-2d390a38-7774-11e7-9cf6-46330e8e2d4f.png)
