### ISSUE TITLE
【调整】mod模块功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#50]
mods模块
	点击后打开新界面
		类似apps store的体验
	显示最近、推荐
	支持分类
	支持搜索
	对于复杂的模块组，考虑如何表现子模块的概念与关联
	对于后面有数据的模块，要可以访问后面的数据--官网
	支持一种图标mod

**Comment by wxaxiaoyao** [comment]
现在已有类似效果， 有问题再细分提。。。太抽象之能做备忘，自己记下就好。
