### ISSUE TITLE
构建ci服务器，正规化keepwork开发测试部署流程

### ISSUE THREAD

**Issue by DreamAndDead** [tatfook/wikicraft#503]
1. 搭建jenkins服务
内网还是公网？部署于docker还是直接部署宿主机？使用哪一种方式部署jenkins?

2. 配置jenkins
必要插件？多用户访问权限管理？

3. create job
代码运行环境？触发方式（被动周期/主动）？test/dev/prod的异同？单元测试/集成测试？代码质量/代码覆盖率？上线需要具备的条件？运行结果的通知机制？

**Comment by DreamAndDead** [comment]
watching progress [https://github.com/tatfook/KeepMonitor/blob/master/ci/readme.md](https://github.com/tatfook/KeepMonitor/blob/master/ci/readme.md) here

**Comment by DreamAndDead** [comment]
dev, test, prod CI的流程已经经过测试，prod环境部署在香港的服务器上

TODO
- 在252上架设docker，将香港服务器的服务器迁移过来

**Comment by LiXizhi** [comment]
OK we will review it on monday

**Comment by LiXizhi** [comment]
- CI/CD 用公网， 但是要限制IP， 为我们香港代理服务器的IP。  大家在公司翻墙时才能访问。

**Comment by DreamAndDead** [comment]
今天完善了文档，ci/cd的流程基本成型，这个issue描述的问题可以关闭。

至于限制IP和其它有关的细节，我们再开新的issue，详细解决
