### ISSUE TITLE
【需求】增加VIP中心页面，VIP包月充值页面

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#514]

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29255889-213d99f2-80d8-11e7-800e-6efb9202c876.png)

**Comment by ZhangKaitlyn** [comment]
## 非VIP：
![image](https://user-images.githubusercontent.com/18642919/29350290-962c3138-8290-11e7-959b-1360e5e5209f.png)

## VIP
![image](https://user-images.githubusercontent.com/18642919/29350268-7a1f8ed6-8290-11e7-8996-ab7c0f5a8128.png)
