### ISSUE TITLE
【bug】duergou取消关注duyigou，duergou没有显示动态，duyigou显示动态，如图

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#516]
![image](https://user-images.githubusercontent.com/28430070/28865821-bbe62098-77a3-11e7-8c0b-61c8645bb486.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/29203614-c364981a-7ea4-11e7-9a5c-b3fdb9232603.png)
![image](https://user-images.githubusercontent.com/18642919/29203624-d58cc008-7ea4-11e7-9c31-34dea748776d.png)
关注信息是否要增加到活动这？A关注或者取消关注B，应该只有B登录后顶部的动态显示这个消息吧
