### ISSUE TITLE
KeepWork中文LOGO设计

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#517]
集团要求KeepWork中文名从`乾坤一网`改为`e网乾坤`。 含义如下：
- KeepWork的发音和`E` `网`是最接近的， 所以放在最前面。 乾坤是为了做一个区别，因为E网是互联网的别名, 不能单独使用。 
- 集团除了KeepWork.com的主域名， 还注册了乾坤e网qkew.com和e网乾坤ewqk.com两个短域名，以备后用。 
- `e网乾坤`突出的是`E网`, 乾坤只是一个范围。

我们网站除了域名和主Logo，需要将全英文的KeepWork尽量改为`e网乾坤`。KeepWork将来出英文版是非常好的， 但是在国内确实需要一个中文名。

请美术也设计一个`e网乾坤`的美术LOGO。分成`e网`和`乾坤`两部分。

**Comment by LiXizhi** [comment]
http://www.akuziti.com/mb/

**Comment by azothli** [comment]
1. 介绍中的 乾坤一网 统一替换成 e网乾坤
2.K字的方形logo，替换成e的类似ie的款式？
3.长方形keepwork icon 看前面说的是不做替换

**Comment by Tibet0312** [comment]
分成e网和乾坤两部分。这个怎么理解？

**Comment by azothli** [comment]
1.只做 介绍文字的替换
2.主页banner条加上

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29009445-fcee2e90-7b55-11e7-9290-8e6ff6571ede.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29021046-d665c92c-7b96-11e7-943f-b61bc25e3400.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29021125-1172f08a-7b97-11e7-8c81-7c0bf8749f57.png)
