### ISSUE TITLE
paracraft Web安装包CI/CD

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#520]
目前www.paracraft.cn上的下载页面时指向：
http://www.nplproject.com/zh/download/download-paracraft
上面的包括Android版的链接很多已经失效， 并且不是CDN加速的。 

目前需要建立一个ＣＩ，自动发布内容到
- http://static.keepwork.com/paracraft/latest/paracraft_full.exe   对应252 上的/data/static/
- 页面用KeepWork的一个git数据源。 里面的版本号自动CI增加。 
  -- /official/paracraft/download

> 当ｐａｒａｃｒａｆｔ升级时，自动打包

**Comment by LiXizhi** [comment]
@azothli  下载页面请参考之前的重新设计下

**Comment by DreamAndDead** [comment]
ref #565
