### ISSUE TITLE
页面Footer优化并增加统计页面

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#521]
```
(c) tatfook     |      |   网站统计 | ... | 
```

KeepWork.com 页脚增加 网站统计(wiki/site_stats),  也就是将目前首页的红框中的内容移动到site_stats.page页面中。 

![image](https://user-images.githubusercontent.com/94537/29011743-1250aad0-7b68-11e7-81ef-154c79a20236.png)

> 还可以考虑罗列下最新的注册用户，最新的用户作品等，方便未来运营人员跟踪用户行为。  

对用户和运营有帮助的， 不消耗性能的统计信息都可以放在这个页面。

@ZhangKaitlyn  @wxaxiaoyao

**Comment by ZhangKaitlyn** [comment]
目前网站统计放了网站数量、名人数量、本周更新数量，其它需要的数据wxa提供了后随时加
