### ISSUE TITLE
再次精简下首先访问首页和一般用户网页的HTTP请求数

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#524]
![image](https://user-images.githubusercontent.com/94537/29083474-7319f86a-7c9b-11e7-81df-bbdae530310d.png)

例如：字体文件有4个请求， 没有打包的js有好多个。 

> 另外，首页的图片压缩下，每张FeatureList效果图，不超过100KB试试看(部分用JPG)？

**Comment by wxaxiaoyao** [comment]
![image](https://user-images.githubusercontent.com/11922085/30801379-a640c5ee-a215-11e7-9e45-f7254fd461f0.png)

**Comment by Sandu1213** [comment]
已与 @wxaxiaoyao 沟通过，涉及功能不断迭代，文件大小会逐渐增大，由开发本身进行自测，实时保证效果会好一些，请知悉。
