### ISSUE TITLE
全文搜索服务

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#526]
- [x] 全文搜索
- [x] 单网站内搜索
- [ ] Context上下文服务

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29501591-43a30a5c-865c-11e7-8b1c-b4ecfc20cbeb.png)
![image](https://user-images.githubusercontent.com/25898720/29501607-762a6a42-865c-11e7-9847-52bd9be7b13b.png)
![image](https://user-images.githubusercontent.com/25898720/29501639-b515673e-865c-11e7-99d4-5c345e7a7a13.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/30256887-9280bf5e-96e0-11e7-9c5f-196b666f820e.png)

**Comment by leopoldchen** [comment]
@wxaxiaoyao @azothli   Context上下文服务也是和天玑团队的mod相关

**Comment by leopoldchen** [comment]
@LiXizhi @wxaxiaoyao @azothli 

Context上下文服务的需求在这里做一下整理吧，以下是我的理解：
1. 目标是实现一个MOD，添加之后可以在文章底部自动显示相关网页，方便浏览者浏览更多相关内容。
2. 相关网页的检索规则是，网页内容中出现频率最高的词汇，不包括一些常用词汇。（建议：可以由文章作者定义关键字，这样可以更精准的定义关联网页）
3. Mod需要可配置。
   - 过滤条件可以是全网，本网站，还有个人所有网站等
   - 可以指定关键字
4. 添加一些网页模板，默认添加此mod，这样在某种类型的网站中用户就不需要每次都去添加这个关联。

**Comment by LiXizhi** [comment]
`网页内容`中出现频率最高的词汇。是最简单的做法， 
这里要问下是否有更好的方案， 例如，这个统计是否可以考虑这个人的其它网页的综合统计。 

例如一个网页中只出现了一次`NPL`，但是这个词汇在这个人的其它网页中反复出现，属于这个`网站`的高频词汇。 

也就是网站的高频词汇，给网页的高频词汇加分。

**Comment by leopoldchen** [comment]
除了定义高频词汇次序，网页关联性权值的计算其实这些高频词汇的复合相关权值。
比如 当前网页的高频词汇是 NPL 和 Keepwork， 那么一篇文章同时包含这两个词，并且出现的频次不低的话，可能权值不一定会比一个包含了很多NPL词的文章低。
所以，这里有两个问题需要解决：
1. 如何确定一篇文章的高频词汇
2. 如何计算一篇关联文章的关联权值

**Comment by tianjiyang** [comment]
![111](https://user-images.githubusercontent.com/31032856/31043511-a804735c-a5ef-11e7-9e2d-64f62d5b49be.png)

**Comment by tianjiyang** [comment]
![222](https://user-images.githubusercontent.com/31032856/31043513-b0dfd0e8-a5ef-11e7-86a5-5e490c249e94.png)

**Comment by tianjiyang** [comment]
陈总，李总的问题已经看到。
针对关键词的提取，肯定是有优化的空间
我们手上现在的keepwork数据不多，暂时只能在当前网页按词频去掉常用词停用词的办法来提取关键词。

**Comment by leopoldchen** [comment]
基于context的检索功能先移除，后续基于知识引擎来实现类似功能
