### ISSUE TITLE
Word,ppt, pdf文档导入插件对接

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#527]

**Comment by leopoldchen** [comment]
@wxaxiaoyao 等天玑那边的mod程序拿过来之后，我们做一下测试。mod交互上我们应该会做调整的，产品会针对这个功能做一下设计。 @azothli

**Comment by leopoldchen** [comment]
@Sandu1213 @duting1993 

需要准备几份测试文档来做解析测试。

目前支持 Word、PDF、PPT和HTML文件的解析。

**Comment by leopoldchen** [comment]
@azothli @Sandu1213 
现有的mod权当一个测试工具，主要目标还是服务端的转换服务可以做的比较好一些。
天玑团队需要一些可测试的案例，包括输入的文件和我们的预期效果。
旧的转换结果如果有问题，需要给他们测试报告，指导他们改进。

**Comment by azothli** [comment]
低优先级
用户可以通过第三方办法处理，不是一定要用我们自己的转化工具

**Comment by azothli** [comment]
Issue moved to [tatfook/KeepWorkDesgin #18](https://github.com/tatfook/KeepWorkDesgin/issues/18) via [**ZenHub**](https://www.zenhub.com/)
