### ISSUE TITLE
【需求】保存提示

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#53]
保存提示
	在切换出已变更代码的情况下给出提示，敦促用户保存
	增加缓存机制
		尽可能的在浏览器关闭、崩溃等情况下，保护用户的工作。

**Comment by wxaxiaoyao** [comment]
已修改成切换代码自动提交无需提示。但自动提交暂时只提交webserver  github这种第三方数据源太慢（而且不一定开启或有该账号）仅在手动保存时提交。
