### ISSUE TITLE
【bug】刚进入页面如果节点是没展开的，点击新建页只展开节点，不弹窗

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#532]
![image](https://user-images.githubusercontent.com/18642919/29151764-f489cbda-7db5-11e7-9715-9d4cb043c913.png)

bug产生原因：treeNodeMap里页面不全
![image](https://user-images.githubusercontent.com/18642919/29151817-36293864-7db6-11e7-8a1d-c0b7247d9ad1.png)

**Comment by wxaxiaoyao** [comment]
@ZhangKaitlyn 先把点击新建页，节点关闭的效果去掉，

**Comment by William0911** [comment]
keepwork 已改版
