### ISSUE TITLE
【需求】企业模板 2套

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#54]
企业X2
	参考
		github.com/lixizhi/paracraft/wiki/nplunion
	之后有20个兄弟企业的官网要做
		可能要考虑招一个专职美工

**Comment by ZhangKaitlyn** [comment]
http://dev.keepwork.com/kaitlyn/company/company1 企业模板1
http://dev.keepwork.com/kaitlyn/company/company2 企业模板2
