### ISSUE TITLE
KeepWork运营WIKI文档

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#542]
整理：https://github.com/tatfook/wikicraft/wiki
删掉过期内容。内容以API说明和运营为主

**Comment by DreamAndDead** [comment]
[keepwork docker化文档整理](https://github.com/tatfook/wikicraft/wiki/keepwork-docker-migration)

可以review下，提出反馈再修改

@LiXizhi @wxaxiaoyao @Xuntian
