### ISSUE TITLE
gitlab集群迁移

### ISSUE THREAD

**Issue by Xuntian** [tatfook/wikicraft#552]

**Comment by Xuntian** [comment]
https://github.com/NPLPackages/NplClusterManager/wiki/Gitlab-Cluster

**Comment by DreamAndDead** [comment]
目前进度卡在gitlab数据备份/恢复上

- 官方提供脚本，数据备份没有问题
- 在同样版本下面，运行数据恢复脚本，出现fatal error，导致仓库数据恢复失败
- 分析原因可能是数据库之间残存的多余数据引起的
- 目前 @xuntian 正在尝试用gitlab api的方式去提取迁移数据

**Comment by DreamAndDead** [comment]
对gitlab恢复过程的一些问题做了统计与处理，ref：

https://github.com/tatfook/wikicraft/wiki/gitlab-backup-restore

目前backup restore可正常运行，程序上运行正确，还需要有近一步的测试机制

**Comment by DreamAndDead** [comment]
备份线上数据库后，将没有namespace的project数据清除。

线上运作正常，全量备份再恢复到另外的一台服务器也正常。

对比

**229测试环境**
![229](https://user-images.githubusercontent.com/5028822/30143416-3f122ce8-93b8-11e7-82e0-056785ac2382.png)


**线上环境**
![online](https://user-images.githubusercontent.com/5028822/30143420-45729f82-93b8-11e7-9a3c-9e969a39269c.png)

目前完善备份恢复文档，以供参考 https://github.com/tatfook/wikicraft/wiki/gitlab-backup-restore

@LiXizhi 

可继续进行gitlab的docker化

@Xuntian

**Comment by DreamAndDead** [comment]
文档已整理 :100:

**Comment by LiXizhi** [comment]
昨天的几个新问题
- uploads
- Git lfs： large file system folder
- gitlab issues has error message: unable to find branch or merge request
