### ISSUE TITLE
大文件，流媒体等上传与保存解决方案

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#554]
我们的几个教育平台都有大文件和流媒体的保存和分享需求。 无广告。

目前主要在看几个产品：

- 7牛云： 我们上海的团队在使用。大富网络的账户已经是大客户VIP账户，所以比较推荐使用。 支持HSL（基于HTTP的Streaming）
- 优酷云 开放平台： 优点可能是如果欠费了， 视频也不会丢失，只是会出现广告。 不知道未来是否会一直这样。 
- 还有一些其它的做直播等的平台

目标：
- 希望对于大文件和视频，我们可以用统一的方式和图片一样来上传， 只不过GIT可能只存了一个Meta文件（例如xref/video_ABC.xref.md）， 文件的实际数据其实是存在7牛这样的第三方公共平台上。 
- `xref/*.xref.md` 甚至可以支持多个数据源：比如同时上传7牛和youku等等。 里面的格式需要我们设计下，虽然是自动生成的， 但是也支持用户手工修改，因为是md格式的。 
- 用户引用或嵌入视频，只需要引用`xref/*.xref.md` 即可。 用md的通用格式引用即可。 
- `xref/*.xref.md`  尽量做到，即时没有用我们的渲染器，也能有基本的播放链接。

**Comment by LiXizhi** [comment]
根据与您的交流，我提供了2份附件，一份是我们全产品线的介绍，一份是存储的介绍，请注意查收；

一、  七牛是存储起家，提供一整套的技术服务，从存储--数据处理--直播、点播--cdn分发--内容鉴黄--大数据分析等等一系列的服务；

1.对象存储：对象存储--开发者中心 https://developer.qiniu.com/kodo ，请点击超链接查看，或复制后面链接搜索查看；

2.数据处理：支持用户把高清视频上传到存储空间，可以转换成不同的码率进行播放，或打水印、裁剪等操作；

3.播放器：支持双平台播放器，首屏时间约100ms，得到业内视频客户的高度认可，在之前版本播放器功能的基础上新增了，变速不变调，H.265 播放，播放器缓存、边下边播、毫秒首开等功能；
获取方式：

Android 播放器下载地址：
https://github.com/pili-engineering/PLDroidShortVideo

Android 开发文档：
https://developer.qiniu.com/pili/sdk/1210/the-android-client-sdk

iOS 播放器下载地址：
https://github.com/pili-engineering/PLShortVideoKit

iOS 开发文档：
https://developer.qiniu.com/pili/sdk/1211/ios-playback-end-the-sdk

4.融合cdn：七牛采用自建加融合的方式，避免客户接入一家cdn厂商，在出现故障时不能快速切到另一个平台，如果接入多家，就会出现沟通运维对接成本，我们有预警监控系统，在出现故障时就会在1分钟内切到安全线路，确保稳定运行；

5.直播：随着业务的发展，很多教育平台通过老师直播授课的方式，进行在线教育，如果贵司后续有这种想法，我们可以实现从采集、推流、拉流、美颜、连麦、cdn分发一整套成熟的直播方案对接，实现快速上线；

二、资费标准

1.对象存储（包含小文件、流媒体文件）： 收取【存储空间+put/delete/get请求】费用，如果使用cdn，回源带宽免费；
2.cdn：按流量阶梯收费；
3.数据处理:见公开价；
4.播放器：不单独收费，下行cdn和存储使用七牛，给予免费使用；
5.直播SDK：不单独收费，下行cdn和存储使用七牛，给予免费使用；

价格请参见链接：https://www.qiniu.com/prices?source=kodo，请打开链接选择不同的产品查看价格，

**Comment by LiXizhi** [comment]
七牛在合同中承诺，不会因为欠费而删除上传数据的
之前我们看合同是终止协议后，甲方完成数据迁移，他们才删除.  即使欠费也不会删除。

因为我们希望做的其实一个类似7牛的代理。 当KP的VIP过期后，我们希望将用户的数据放到一个7牛不收费的目录， 可以无法访问， 不知道是否可以？

这样，7牛承诺我们什么， 我们也可以承诺VIP用户什么， 保证用户的VIP过期后，数据不会没有，只是无法访问。 但是我们不再支付7牛相应的存储空间和流量的费用。 

@wxaxiaoyao @yuki1206

**Comment by wxaxiaoyao** [comment]
- https://github.com/tatfook/wikicraft/issues/593
- http://keepwork.com/keepwork/wiki/%E6%96%87%E6%A1%A3/%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE

**Comment by leopoldchen** [comment]
#613 细致的功能点和UIUX请参考这个issue，还在设计中。 @wxaxiaoyao
