### ISSUE TITLE
【bug】建立3这个文件，包括theme 和index，在简历一个3的文件夹，显示如图1这个位置，显示出来的效果会让用户误认为，3这个文件夹包含了theme和index文件

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#555]
![image](https://user-images.githubusercontent.com/28430070/29352426-3ac31f7e-8299-11e7-992c-dd69ca872e9e.png)

**Comment by azothli** [comment]
目前表现为设计期待，不存在混淆
子内容有缩进
![image](https://user-images.githubusercontent.com/22001356/33247678-f7bd1866-d35a-11e7-86da-9b2e0858f77b.png)
