### ISSUE TITLE
paracra3d校园搭建功能的10分钟自动保存需求

### ISSUE THREAD

**Issue by adkevinchang** [tatfook/wikicraft#557]
3d校园项目由于是远程多人搭建。如果出现断电或死机，就会造成搭建的作品没有保存。

增加自动保存空间的功能。每10分钟自动保存空间一次。

很紧急，谢谢！

**Comment by LiXizhi** [comment]
please submit to paracraft/issues

**Comment by adkevinchang** [comment]
ok
