### ISSUE TITLE
【bug】_theme和grid模板冲突

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#563]
![image](https://user-images.githubusercontent.com/18642919/29455400-9e1d1d08-8443-11e7-968c-75cd2de97c73.png)
渲染出的dom：
![image](https://user-images.githubusercontent.com/18642919/29455459-c9c26274-8443-11e7-8b5c-dda69b7d9c32.png)
示例网页：http://dev.keepwork.com/kaitlyn/themetest/index

**Comment by azothli** [comment]
编辑方式改版，这个优先级降低
