### ISSUE TITLE
私有网站所有者权限问题

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#564]
创建公共网站，编辑好
然后设置改为私有网站
创建者可以看到网站，可以看到页面名，可以在编辑器打开，但是里面的文件没内容
不知道这个时候编辑保存会发生什么
赋予编辑权限的其他人正常。

尝试将自己添加到权限组，未成功，提示出错。

**Comment by duting1993** [comment]
测试步骤：1.创建公有网站，编辑内容
                   2.设置里切换私有，赋予别人编辑权限
                   3.从个人主页进入网站编辑，进入该网站编辑页面
实际结果：自己创建该网站没有显示内容，别人可访问编辑
期望结果：自己创建该网站显示有内容

**Comment by duting1993** [comment]
可能 token失效 api请求重定向到登陆页， 非必现，  增加刷新token功能 来验证避免此问题。
