### ISSUE TITLE
Paracraft下载页面与CI/CD联通

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#565]
- [ ] 用NPL写一个自动更新程序（以npl_mod的形式写）， 参考AutoUpdater C++代码。 这样可以在linux机器上通过命令行自动更新。 
- [ ] 写一个CI，自动pull监听version,   发布最新的PC，Android安装包到KeepWork的某个页面。 paracraft.cn的下载页面也连过去

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29647708-30be76f2-88bd-11e7-848c-74782b6e8e84.png)

**Comment by LiXizhi** [comment]
OK cool.

**Comment by ZhangKaitlyn** [comment]
[http://dev.keepwork.com/kaitlyn/downloads/index](http://dev.keepwork.com/kaitlyn/downloads/index)
