### ISSUE TITLE
【需求】分享功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#57]
分享
	top中的分享是分享wikicraft的链接
	网站中的分享，要做成模块，根据cname来确定内容

**Comment by caoyongfeng0214** [comment]
分享需用公司资料到各平台去注册。
请李宇童鞋将几个常见平台注册一下，如微信、新浪微博。

**Comment by azothli** [comment]
现在用模块已经可以分享了，还需要注册么？
