### ISSUE TITLE
【需求】gitlab中文化

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#580]

**Comment by DreamAndDead** [comment]
目前提供的中文化示例，是使用了第三方提供的汉化docker。
不推荐这样做，因为来自官方的镜像相对值得信赖。
推荐使用 官方镜像+[第三方汉化补丁](https://gitlab.com/xhang/gitlab) 的方式，

**Comment by azothli** [comment]
已经实现，打中文补丁
