### ISSUE TITLE
【需求】实名认证

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#582]

**Comment by azothli** [comment]
http://www.nciic.com.cn
全国公民身份证号码查询服务中心
有实名接口
查询按条付费

**Comment by azothli** [comment]
技术看下是否要使用这个
@LiXizhi @leopoldchen

**Comment by leopoldchen** [comment]
支持使用http://www.nciic.com.cn
参考知乎讨论
https://www.zhihu.com/question/30768186 
目前应该只能使用这个，其他很可能是黑服务，随时可能出问题。

**Comment by azothli** [comment]
目前确定使用手机验证实现
http://keepwork.com/keepwork/pwiki/pm/real_name/real_name_phone

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/31528250-cdaea036-b004-11e7-9111-9713edea1613.png)


![image](https://user-images.githubusercontent.com/25898720/31528353-58b3cc9c-b005-11e7-842c-eed8c71834a9.png)


![image](https://user-images.githubusercontent.com/25898720/31528424-c0d7e09c-b005-11e7-9b7a-e17c56fa3774.png)

![image](https://user-images.githubusercontent.com/25898720/31528467-f9aaaa30-b005-11e7-9961-1aec5fbcb9f1.png)

**Comment by azothli** [comment]
实名认证的数据与手机绑定的数据不同
绑定=账号，是可以解绑，是可以换的
实名这个是一个认证状态，不一样。

进行实名绑定的时候，如果这个手机号，没有进行绑定，则提示用户是否绑定

**Comment by yuanoook** [comment]
test site: stage.keepwork.com

**Comment by Sandu1213** [comment]
还有部分功能需要完善一下，稍后再验证

**Comment by yuanoook** [comment]
test site: stage.keepwork.com

**Comment by Sandu1213** [comment]
在进行以下操作的时候，触发实名认证状态检测：
– 新建网站（包括api创建的网站，例如paracraft存档） 
--- paracraft的存档，需要线上环境才能验证，```待后续验证```；
     新建网站模板，如果选择是课程模板，则会跳过实名认证;其他控制有效
– 使用评论comment模块
---  验证通过
– 编辑他人网站
---  ```待验证```
– 使用组织、比赛的 申请、提交功能
--- 申请功能验证通过；
     提交作品功能```待验证```；
– 用户的其他内容数据提交行为    
--- ```待验证```


目前存在的问题如下：
1.样式问题：
![real_name](https://user-images.githubusercontent.com/21214285/33006164-3dc7f418-ce04-11e7-9746-c21839904df7.gif)
![real_name2](https://user-images.githubusercontent.com/21214285/33006346-fb83f15a-ce04-11e7-88d0-0fa279b03620.gif)

**Comment by Sandu1213** [comment]
-  编辑他人网站
--- _缺少检测，请调整_
- 使用组织、比赛的 申请、提交功能
--- 申请功能验证通过；
提交作品功能验证通过，只有先创建网站才能进行提交；
- 用户的其他内容数据提交行为
--- 待验证

**Comment by duting1993** [comment]
用户的其他内容数据提交行为-预留功能待后续测试

**Comment by Sandu1213** [comment]
paracraft 的实名稍后再做处理；（后续会统一，含魔法哈奇）
该版本还需要考虑老用户未实名的问题，需要在存盘的时候加上相应的校验。

**Comment by leopoldchen** [comment]
@yuanoook 实名认证的前端存储有问题，新开一个页面做认证之后在第一个页面依然需要认证，刷新也无效。可以考虑参照user token的做法。
