### ISSUE TITLE
【需求】应用中心增加mod扩展

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#586]
需要logo @Tibet0312 

![image](https://user-images.githubusercontent.com/18642919/29761588-7e0e31a8-8bfc-11e7-9908-464a90bbbeb5.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/29800364-34f96cf8-8c9c-11e7-8e90-24dd05ca2c11.png)
