### ISSUE TITLE
支付页面，热门服务

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#599]
http://keepwork.com/official/haqi/payads

**Comment by onedou** [comment]
http://git.keepwork.com/gitlab_rls_official/keepworkhaqi/raw/bedd33ab3f022229678d5be03e207764d9f51822/official/haqi/payads.md

**Comment by onedou** [comment]
http://git.keepwork.com/gitlab_rls_official/keepworkhaqi/raw/master/official/haqi/payads.md

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/30008882-196a9cc8-9156-11e7-9395-87f0b48b0793.png)
