### ISSUE TITLE
网站模版   页面模版   模块 整理

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#603]

**Comment by azothli** [comment]
方案确定：
在official下创建一个模版网站，在其中进行模版编辑。
编辑后，需要程序人工添加到网站可使用的模版中。

**Comment by ZhangKaitlyn** [comment]
方案更新：
- 模块由程序添加
- 网页模板：在official下建一个网站，存放网页模板
- 网站模板：在管理后台进行表单配置，通过contentUrl这个参数配置存在于official下的网页模板
