### ISSUE TITLE
网站模版与新手引导

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#610]
这个月， 孙总希望能够让他使用KeepWork做个人网站。我们这个月强化一下下列用户的体验。
主要体现在（1） 新建网站，网页， 与网站模版的体验   （2） 新手视频 与 帮助文档。  

- 个人博客类应用： 多几个模版
- 个人私有笔记类应用： 参考evernote的版式
- PPT类网页应用：包括周报，月报， 汇报等

需要在9月内完成  

@azothli  @leopoldchen

**Comment by Tibet0312** [comment]
周报、月报模板，后续更新。。

http://keepwork.com/tibet/weekly/index

**Comment by LiXizhi** [comment]
孙总提到的手机上的个人私有笔记以及各人史记， 需要做成有编辑功能的网站模版或独立的应用才行。 

一网乾坤有一个通用的模块化的网站编辑器，虽然我们会不断优化体验， 但是无法满足所有应用场景的易用性。 
孙总提到每个网站可以像切换输入法一样切换编辑器，这个思路很好。 目前我们和道峰教育平台就是类似的做法。 

用户登录一网乾坤, 注册一个新的网站， 可以选择网站模版， 如果模版类型为课程， 则最后会跳到道峰的网站去编辑。

```
http://keepwork.com/lixizhi/programming_in_npl
【开始编辑】  跳到一个外部编辑器
```

如果用户强制用keepwork编辑也可以，但是keepwork editor UI上也会提示用户切换到推荐编辑器。 所有这些可通过网站模版MOD和模版的_theme文件实现。 
_theme.md文件中可以加入设置默认编辑器url的MOD. 

除此只外， 当直接访问 http://keepwork.com/lixizhi/programming_in_npl  也会有直接编辑课程的按钮。 也是通过_theme实现的。 

史记和个人笔记应该也是类似的做法。
这样针对不同的网站模版，可以有不同的网站编辑器，甚至不需要编辑器，编辑功能直接由网站本身的MOD实现。

**Comment by Tibet0312** [comment]
笔记模板
http://keepwork.com/tibet/weekly/%E7%AC%94%E8%AE%B0%E7%B1%BB%E6%A8%A1%E6%9D%BF-%E7%BD%91%E9%A1%B5

**Comment by leopoldchen** [comment]
@wxaxiaoyao 模板的拷贝用的是fork指令还是单个文件拷贝单独commit的？
