### ISSUE TITLE
帮助网站重新设计，使用KP网站即可

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#612]
![image](https://user-images.githubusercontent.com/94537/30094428-e1998aa2-92fe-11e7-8301-d2c9552437d9.png)

帮助网站直接指向一个常规网站即可。 

里面的内容完善下。 

参考: 
- https://help.github.com/

@leopoldchen @azothli

**Comment by azothli** [comment]
http://keepwork.com/official/help/
网站已经账创建，安排吴志远开始参考github做整理。

**Comment by leopoldchen** [comment]
这块是否考虑对接第三方服务？印象中这种帮助中心服务是和客服相关的，有些第三方服务可以把这块处理的很顺畅，可以由运营管理更新这块内容。比如[kf5](https://www.kf5.com/)和[美洽](https://meiqia.com/).
自己开发的缺点就是运营需要依赖开发来做这块的内容更新，而且也需要开发添加功能来直接对接客服

**Comment by 1534542119** [comment]
帮助界面可以做的更简洁一点,人工服务希望可以做的更明显一点
