### ISSUE TITLE
大文件资费与管理模块

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#613]
全部账号，免费送2GB空间
vip账号，额外送18GB空间（共20GB）
还想要更多的空间请按年付费。

对用户来说，本质上是一个内置的网盘，所以还需要文件管理器去满足用户的文件管理需求。

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/30098894-69057bce-9316-11e7-9c75-6e2963de5797.png)

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/30098906-741edeba-9316-11e7-89a6-c66bc76302b4.png)

**Comment by azothli** [comment]
@LiXizhi @leopoldchen

**Comment by LiXizhi** [comment]
0.06/GB是降级（低频）存储的价格。 非降级的费用还是挺高的：

![image](https://user-images.githubusercontent.com/94537/30106486-2cc5b31e-932e-11e7-92b6-c7c271a3961f.png)
![image](https://user-images.githubusercontent.com/94537/30106489-311bea32-932e-11e7-93d6-c9d11e0f8634.png)

是否考虑，免费用户的视频只保存7天，相当于试用（也避免用户开小号存视频了）。 VIP用户永久保存，连续2个月，如果访问量小于10则自动降级，否则不降级。 访问量增加时，自动恢复到正常存储。

**Comment by LiXizhi** [comment]
@azothli @leopoldchen

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/30107314-f103464a-9330-11e7-9542-ff3baee45060.png)

如果我们的后台也管理一套用户数据， 可以用hash, 自动去掉重复的文件。

**Comment by azothli** [comment]
按照0.145的活跃成本重新计算了下，供参考
![image](https://user-images.githubusercontent.com/22001356/30149466-4f2f52b4-93da-11e7-9c49-77f684aa64ab.png)

**Comment by azothli** [comment]
之前设定的扩展包价格过低，仅存储，费用预计为
![image](https://user-images.githubusercontent.com/22001356/30149520-7b1503f6-93da-11e7-9f78-65e883245ea8.png)

**Comment by azothli** [comment]
正常存储  0.125左右
降级存储 0.06左右  但是直接60天起，不足60按照60天算，且读取需要额外收费（0.06/GB）

除非是那种万年不用一次的纯备份，不然还是不太划算啊（费用不一定真的低，且体验还不够好）

我觉得这个值得重新考虑下

**Comment by leopoldchen** [comment]
扩展包的递增关系可能可以跨度更大一些。20G的存储可能已经可以满足99%的个人VIP用户了，而剩下的的1%的用户应该大比例是企业或者组织用户，这时候对存储的需求可能希望一步到位，那么比如200G, 1T, 10T这样的跨度会合适一些。
不过以上也只是猜测，最好是有用户数据来做一下分析，目前我们存储需求最大的用户，存储量大概是多少呢？@azothli

**Comment by azothli** [comment]
当前接触的用户，大富文教的存储应该是数个T的这个级别就够了
数千个 视频

**Comment by leopoldchen** [comment]
@ZhangKaitlyn @Tibet0312 @wxaxiaoyao 
 http://keepwork.com/tatfook/keepwork/big_file

**Comment by Tibet0312** [comment]
页面链接：

http://keepwork.com/tibet/file/index

**Comment by Sandu1213** [comment]
大文件相关问题记录如下，回归问题时请参考验证
http://keepwork.com/duting/dawenjian/index
[大文件问题汇总.zip](https://github.com/tatfook/wikicraft/files/1410290/default.zip)
