### ISSUE TITLE
【bug】keepwork充值VIP，充值成功，没有显示消费记录，我的VIP没有显示到期日期

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#615]

**Comment by onedou** [comment]
http://dev.keepwork.com/wiki/vip

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/30104067-201ae712-9327-11e7-9e64-3e594b9541e1.png)
请问是不是CDN的问题 @wxaxiaoyao

**Comment by onedou** [comment]
dev 是可以的

**Comment by onedou** [comment]
后台是已经收到了pingxx的支付信息
现在是vip没有收到

**Comment by leopoldchen** [comment]
@duting1993 上次修改了回调url之后应该已经正确了，不过test服务器上应该不能支付。
另外，这块的重构 @onedou 应该已经在修改，上次群里讨论的时候有看到
