### ISSUE TITLE
北京大数据百科数据

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#627]
查看百科数据的导入情况

**Comment by DreamAndDead** [comment]
百科数据导入在keepwork用户的baike项目下，gitlab地址： http://git.keepwork.com/gitlab_rls_keepwork/keepworkbaike

最新提交文件时间为 ` Sat Sep 9 00:51:05 2017 `

![git-latest-commit](https://user-images.githubusercontent.com/5028822/30266172-22b822d0-9711-11e7-8a4c-892fcb60bbbe.png)

百科目录下，共4个子目录，累计 52859 个文件

```
└── 百科
    ├── 佛学网站
    ├── 国学网站
    ├── 科学
    └── 道学网站
```

文件列表， 见附件 [files-list.txt](https://github.com/tatfook/wikicraft/files/1291944/files-list.txt)

**Comment by DreamAndDead** [comment]
今天又查看了下，百科的数据还是如上，没有再更新过

**Comment by LiXizhi** [comment]
备忘：
- 百科搜索融入外网数据
- PDF的图片扫描件效率问题
- 众包翻译
- 默认KeepWork路径
- 大文件，例如视频的存储接口
