### ISSUE TITLE
【需求】搜索栏支持下拉框，选择搜索范围

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#628]
下拉框内容
“全部”
“本站”

在非用户创建网站中，默认 全部
在用户创建的网站中，默认 本站
可以点击切换

**Comment by LiXizhi** [comment]
默认规则， 应该和github一致。 只和网址有关。 如果已经是下拉了， 可以将
- 全部
- 本站
- 当前人

等都做了。 

http://keepwork.com/tatfook/  则默认搜索tatfook这个人
http://keepwork.com/tatfook/wiki  则默认搜索tatfook/wiki这个人
http://keepwork.com/ 则默认搜索全站


@azothli @leopoldchen

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/30315250-e2e05bee-97d5-11e7-8040-16742e6b6eeb.png)

 这种也可以考虑。 目前没有地方显示当前网站名和用户名
