### ISSUE TITLE
网站升级，进行消息提示

### ISSUE THREAD

**Issue by DreamAndDead** [tatfook/wikicraft#629]
周四进行进行升级的时候，keepwork网站升级速度是快速的，但是涉及到gitlab后端迁移部署到集群，中途如果出问题，可能出现网站宕机的情况。

用一个替代的页面，友好的提示用户，目前发生了什么，不至于只看到400 500错误

**Comment by DreamAndDead** [comment]
考虑目前的需求情况

1. 大部分情况下，keepwork保持在线
2. 周四进行keepwork升级的时候，销毁docker镜像并重启新镜像，所花费的时间可忽略不计。这个时候不应该使用替代页面提示升级，因为我们也需要测试
3. 回滚同2
4. gitlab需要迁移的情况，这时候原有的gitlab服务会停止，这时候访问keepwork无法保存数据，应该使用替代页面提示用户，网站正在升级。在gitlab部署到集群之后，又需要TODO

**Comment by leopoldchen** [comment]
其实可能还需要添加一个出现在footer栏的弹出提示。比如告知用户，keepwork将在哪个时间点做更新，请保存好正在编辑中的网站资料。因为如果刚好有人在线编辑网站，是可能导致数据丢失的吧？

**Comment by DreamAndDead** [comment]
@leopoldchen  good point，前端进行友好的提示比整个网站都down掉要合理人性化一些

是的，以下几种情况会有丢失数据的风险

1. keepwork网站上线 这一瞬间
2. gitlab服务停止，正在迁移至集群。这一段时间，用户调用数据接口会出错
3. gitlab集群启动，测试发现有问题，又回滚之前的服务。这一段时间，用户保存的数据存在于集群中，不存在于原先的gitlab服务中

今天晚上进行gitlab集群的迁移，如果集群迁移成功，就不存在2 3点的顾虑

@Xuntian @LiXizhi

**Comment by LiXizhi** [comment]
目前所有没有保存成功的数据会存在chrome浏览器的前端， 即时关机，也不会丢失。 

这个可以验证下。 之前测试过。 @duting1993

**Comment by DreamAndDead** [comment]
目前关于网站停止维护页的设定

网站的所有link请求（无论GET or POST）都会返回这样的响应

HTTP return code: 503

附加防止cache的HTTP header: 
- Cache-Control: no-cache, no-store, must-revalidate
- Pragma: no-cache
- Expires: 0

页面内容
![default](https://user-images.githubusercontent.com/5028822/30623648-7148b8de-9deb-11e7-849b-03ca3993a5cf.png)

整体呈现
![default](https://user-images.githubusercontent.com/5028822/30623879-e25f29da-9dec-11e7-86f5-8add2218e030.png)
