### ISSUE TITLE
toc在顶部处理方式

### ISSUE THREAD

**Issue by ZhangKaitlyn** [tatfook/wikicraft#634]
```@toc
```
默认让toc显示在顶部。
在顶部的时候toc的处理是要

1. 加个白底
![image](https://user-images.githubusercontent.com/18642919/30267779-35bbf820-9716-11e7-9183-4e08c2a28d89.png)
2. toc不固定在窗口顶部，随着滚动条滚（这是toc类似于普通目录）
![image](https://user-images.githubusercontent.com/18642919/30267843-6ed132b0-9716-11e7-9772-21416def4b52.png)

1和2是我能想到的处理方案，选哪个？或者要别的方式？
@LiXizhi @azothli

**Comment by azothli** [comment]
Issue moved to [tatfook/KeepWorkDesgin #17](https://github.com/tatfook/KeepWorkDesgin/issues/17) via [**ZenHub**](https://www.zenhub.com/)
