### ISSUE TITLE
【需求】mod：vip查看更多

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#636]
![image](https://user-images.githubusercontent.com/22001356/30307630-0a71d6b6-97b2-11e7-98ae-280fdf6d8753.png)
类似这个图，文字改为 Vip查看更多

该mod加入到页面后，用户载入的时候首先判断是否登录，未登录要求登录，登陆后检查是否vip，是vip则不显示相关效果。
不是vip，遮蔽掉下面60%内容（高度），然后提醒用户激活vip。

**Comment by azothli** [comment]
```@wiki/js/permission
{
"moduleKind":"vipPermission"
}
```
dev上好了

**Comment by ZhangKaitlyn** [comment]
\```@ wiki/js/permission
 {
 "moduleKind":"vipPermission"
 }
 \```

**Comment by LiXizhi** [comment]
Good
