### ISSUE TITLE
【bug】cname转发，导航条登陆 组织模板未登录 登陆后刷新 申请加入按钮没有出现，组织/大赛 申请加入无法加入该组织/大赛，

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#653]
![image](https://user-images.githubusercontent.com/28430070/30463104-777fd09a-99fc-11e7-9868-69d3e503cba9.png)
pacpac.keepwork.com

**Comment by duting1993** [comment]
console报错 TypeError: Cannot read property '_id' of 
打开 ng-href 减少使用 util.go()

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/30537015-af45f3ec-9c9a-11e7-9095-5a8b9291c7ce.png)
新的大赛和组织模板将申请加入等页面移到模板内
