### ISSUE TITLE
【需求】申请加入XX，组织/大赛名加粗，点击申请，弹窗，提示改为，申请已提交，请等待管理员审核，个人简介要修改

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#654]
![image](https://user-images.githubusercontent.com/28430070/30464587-eca36c58-9a04-11e7-9b65-e481705d9fa4.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/30465672-f1b329f8-9a0a-11e7-9578-b3471a0a5e4e.png)

![image](https://user-images.githubusercontent.com/25898720/30465680-05e2fcf0-9a0b-11e7-901f-610eb212fed4.png)
