### ISSUE TITLE
OAuth Secret放到Config中， 不要上传public GIT

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#658]
https://github.com/tatfook/wikicraft/blob/master/www/wiki/models/oauth_app.page

![image](https://user-images.githubusercontent.com/94537/30513561-eddd3318-9b37-11e7-822e-b0744946ea94.png)

@onedou @wxaxiaoyao

**Comment by onedou** [comment]
oauth key放到数据库会不会好些
以后他们也可以通过后台管理修改自己的key

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/30532347-76717e8c-9c19-11e7-9f81-4804a256568e.png)

**Comment by onedou** [comment]
pull request see #679

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/30678090-9535da8c-9e55-11e7-9d87-9a8988b835ab.png)

**Comment by leopoldchen** [comment]
@onedou  @wxaxiaoyao  
#679 已经被合并的master分支了，这个是否会影响现有的oauth app?

**Comment by leopoldchen** [comment]
@duting1993 @Sandu1213 

尽快配合测试这个功能

@onedou 需要有一个新版本，废弃就的config，使用存储在数据库中的oauth数据。请创建一个feature/oauth 分支来做这个事情，开发完成后提交pr到dev分支

@DreamAndDead 如果big需要部署测试，请提供协助。

**Comment by onedou** [comment]
等下会发一个版本，现在接口还在改

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/32259208-d3012fbe-bef9-11e7-89a8-8e7864584cd4.png)
![image](https://user-images.githubusercontent.com/21214285/32259274-4d71bbc4-befa-11e7-9d4d-f9c26268637a.png)

**Comment by Sandu1213** [comment]
目前paycallbackUrl和RedirectUrl的过滤还有些问题，还需要再调整；
另外，涉及appName不支持中文的原因，凡是之前是appName中文的地方都需要重新调整

**Comment by Sandu1213** [comment]
已经测试完成，待申请机制确定后可以合入线上。
