### ISSUE TITLE
【需求】针对手机的，笔记模版

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#660]
针对手机的笔记模版，兼容pc（以前的是针对pc开发，然后响应式兼容手机）

**Comment by Tibet0312** [comment]
页面链接：

http://keepwork.com/tibet/weekly/%E7%AC%94%E8%AE%B0%E7%B1%BB-%E6%89%8B%E6%9C%BA%E7%89%88

**Comment by azothli** [comment]
有了adi编辑器 keepnote 目前不需要了
