### ISSUE TITLE
网站设置DIY数据源不见了

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#666]
![image](https://user-images.githubusercontent.com/94537/30626752-843ca154-9dfe-11e7-8e07-d580ec0370fd.png)

- 最上方应该告诉用户当前的网站是什么。 
- 数据源DIY UI 不见了

另外：
- 设置页的网站地址前面没有http://
- CNAME是什么，要加上说明文字和例子。目前只是配置。

**Comment by ZhangKaitlyn** [comment]
数据源的设置之前是一个单独的页面的中，网站设置里只有选数据源的吧？
![image](https://user-images.githubusercontent.com/18642919/30740007-e6575a22-9fc1-11e7-8ce7-5f948d5e3afc.png)

**Comment by LiXizhi** [comment]
OK  ic.  我看错了
