### ISSUE TITLE
【讨论】keepwork 的内容功能分流

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#675]
当前的keepwork网站功能不是很纯粹，同时混合了网站创建+内容展示的功能
这样发展下去，会显得网站的功能逻辑比较混乱

所以keepwork应该按照 工具网站来发展，之后的维护与发展侧重于：
创站功能强化、丰富
网站、网页模版优化与追加
功能mod优化与追加
额外创站服务的丰富（最近的大文件、之后的短域名等服务）

同时我们可以考虑创建一个keepwork内容的大展示平台，专门做内容展示。
@LiXizhi @leopoldchen

**Comment by leopoldchen** [comment]
这里其实有个问题需要考虑，keepwork是创作工具，还是创作及分享传播平台？
如果是前者，那么首页就和现在的展示没有太大差别。 可以参考[石墨文档](https://shimo.im/)
如果是后者，那么keepwork的首页应该侧重于内容展示，让用户更好的检索和浏览知识。工具功能展示和创作入口放在次要位置。参考[知乎](https://www.zhihu.com)、[简书](https://www.jianshu.com)
