### ISSUE TITLE
【需求】网站配置，添加配置“默认首页”的项

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#676]
可以指定非index作为默认首页。

**Comment by azothli** [comment]
![image](https://user-images.githubusercontent.com/22001356/30675468-59aa7abe-9eb3-11e7-9da0-130d2957624d.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/31373604-4b80c384-adcd-11e7-869f-3cece31aba56.png)


![image](https://user-images.githubusercontent.com/25898720/31374227-acd167d6-adcf-11e7-9db9-6f36ceebcc61.png)

**Comment by Sandu1213** [comment]
@azothli 宇哥，请审核下UI效果图，如果可以的话，晚点就让郭璐那边帮忙实现下。实现完成后，测试这边再进行验证哈。

**Comment by William0911** [comment]
我让宇哥确认过功能了

**Comment by William0911** [comment]
测试地址：10.27.2.117:8099

**Comment by Sandu1213** [comment]
当index页面被删除后，判断实现有些问题，请再调整

**Comment by William0911** [comment]
这个红字提示需要调用gitlab接口查询page是否存在，我们数据库上没有相应的数据。和李宇商量了一下，觉得这样做不太好，还是不做红字提示了。

**Comment by Sandu1213** [comment]
因为缓存的原因，如果删除index页面后，再快速恢复默认主页为index则会出现创建index页面的情况；修改为非index默认页或者多等几分钟则会正常显示，除此以外，验证通过。上述问题，产品已知。
