### ISSUE TITLE
jgraph Diagram 模块开发

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#680]
jgraph Diagram 模块开发

https://www.draw.io  
https://github.com/jgraph/drawio

**Comment by LiXizhi** [comment]
@onedou   集成方案，请参考曹老师自己写的那个diagram mod代码

Diagram数据可以用WXA最新的超链接接口形式。这样数据是一个独立的文件， 可以被多个网页引用。

**Comment by onedou** [comment]
https://github.com/jgraph/mxgraph

**Comment by Sandu1213** [comment]
已经简单验证过一遍，目前可以画图成功，存在部分遗留问题如下，请见附件。（如再有发现，会再进行更新，请知悉）
