### ISSUE TITLE
【需求】编辑器中url复制功能

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#682]
url不能直接复制，建议在边上加一个复制按钮

![image](https://user-images.githubusercontent.com/1396883/30683585-8e6c5560-9ee0-11e7-92ae-d5f4bad3d45f.png)

**Comment by leopoldchen** [comment]
url为空的时候点击依然会打开新页面，需要优化
![empty_url](https://user-images.githubusercontent.com/1396883/30684975-dd5fd642-9ee5-11e7-922d-3b18fa05f3ec.png)

**Comment by azothli** [comment]
url点击新窗口打开
后面增加 点击复制 按钮
