### ISSUE TITLE
【bug】参与的项目，这三个图标应该不显示

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#683]
![image](https://user-images.githubusercontent.com/28430070/30684602-784498a2-9ee4-11e7-85d7-7564f00afb6a.png)

**Comment by duting1993** [comment]
设置按钮不显示，其他两个按钮显示

**Comment by ZhangKaitlyn** [comment]
参与的项目去掉设置按钮
临时的项目去掉 新建网页、新建文件夹、设置、删除、同步 按钮
