### ISSUE TITLE
TableDB Raft 对接测试

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#686]
目前tabledb raft已经提交新的版本，我们也在处理后台管理相关的事项，因此，考虑基于日志系统来对新的数据库做一下测试。

- [ ] 测试集群部署，可以在多台服务器间建立连接，并能正常使用
- [ ] 创建demo，测试tabledb raft性能

**Comment by Xuntian** [comment]
目前tableDB的raft集群部署遇到的问题
1，启动命令封装不够
2，server端和client端的代码混杂在一起，调用代码时必须include所有代码
3，server端和client端必须都有能够访问的ip，不能是内网地址
4，调试只能看日志，比较麻烦

**Comment by Xuntian** [comment]
目前tableDB的raft集群部署遇到以下问题：
1，启动命令和配置比较麻烦，涉及到npl命令的dev目录
2，server端和client端必须有相互能访问的ip，不能用内网地址
3，server端和client端的代码混杂在一起，使用时需要包含所有的代码
4，调试只能通过log，比较麻烦

**Comment by leopoldchen** [comment]
还需要考虑单表数据量超大情况时的解决方案，数据库操作日志是一张数据量极大的表

**Comment by liuluheng** [comment]
感觉都不是问题啊。。

**Comment by Xuntian** [comment]
的确都不是什么大问题，但是这是要用于实际开发和生产环境的应用的，没有友好的封装，之后的部署，开发，调试和测试都是灾难，是否有办法先解决第四点？ @liuluheng

**Comment by liuluheng** [comment]
我调试系统都是用log。你觉得麻烦，是指和debugger相比吗？打断点的形式？

**Comment by Xuntian** [comment]
是否有办法方便快速地查看数据库里的内容，至少满足这一点

**Comment by liuluheng** [comment]
可以用[sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.0)

**Comment by Xuntian** [comment]
好的，明天我看看

**Comment by leopoldchen** [comment]
@Xuntian 
测试demo看一下能不能这样子设计：
准备一张history表和相关的user表与website表。history表的结构参考如下示例：
```
user_id
resource_type -- 模拟数据中有website和user
resource_id 
action -- crud增删查改
created_at -- 记录创建时间
```
demo要做的一个事情是模拟往history表插入一亿条记录。首先创建一万个用户，为每个新创建的用户启用单独线程来模拟生成history信息，比如更新用户信息，做website的增删改查操作等。

考虑一下几个问题：

1. 插入过程多个server的数据同步是否正常？
2. 在并发插入数据时效率如何？
3. 数据插入完成后，尝试做数据检索，比如查询某一天某个人的history记录，查看性能是否ok。这块我们可以细化。

**Comment by Xuntian** [comment]
可以

**Comment by Xuntian** [comment]
目前遇到的问题：
1，tabledb.config.xml文件必须得放到client下的temp/test_raft_database目录下，否则无法向server端传送数据
2，client端出现大量的一下error信息，这些由于timeout引发的error是否可以规避？
![image](https://user-images.githubusercontent.com/17767432/31375310-acf7776a-add3-11e7-8b85-450f9b82bfa8.png)
3，当向数据库新建一万个用户时用时很久，4分多钟，而且数据库操作经常中断
![image](https://user-images.githubusercontent.com/17767432/31375448-2bcb9ff8-add4-11e7-8ecf-48312467d416.png)
而且，日志里虽然记录了有1万条数据库操作的日志，但是用UE和navicat软件打开数据库文件User.db是只有275个用户的数据

**Comment by leopoldchen** [comment]
@Xuntian 是否有尝试过停掉其中的一个Server，会产生怎样的影响？

**Comment by leopoldchen** [comment]
这个raft测试已经通过，关闭了
