### ISSUE TITLE
【bug】搜索没有返回的时候，要添加一个默认的返回内容，提醒用户

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#688]
![image](https://user-images.githubusercontent.com/28430070/30725790-ba3c2ae6-9f79-11e7-9fdd-65193ab64a4c.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/30731737-c5951a10-9fa1-11e7-881d-969158fcee55.png)

**Comment by Sandu1213** [comment]
请再调整一下。
