### ISSUE TITLE
【bug】已经被绑定的邮箱，，输入邮箱之后，点击发送验证码，会出现弹窗，提示被弹窗覆盖

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#690]
![image](https://user-images.githubusercontent.com/28430070/30727311-127ac9fc-9f83-11e7-9ccd-b647f97b3772.png)

**Comment by leopoldchen** [comment]
@ZhangKaitlyn 需要将提交的pr绑定到issue上
