### ISSUE TITLE
【bug】没有编辑权限，当编辑过后保存，提示保存失败，左边还有米字符号，当关闭时，会提示页面没有保存等文字

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#695]
![image](https://user-images.githubusercontent.com/28430070/30848312-5bb0f9a6-a2d1-11e7-8a5e-6582b349cca6.png)
![image](https://user-images.githubusercontent.com/28430070/30848344-6eba0c18-a2d1-11e7-8ba6-5b10a3da3131.png)

**Comment by azothli** [comment]
这里应该提示用户另存到自己的网站

**Comment by ZhangKaitlyn** [comment]
调整：临时页面不记录修改状态

**Comment by ZhangKaitlyn** [comment]
测试环境： http://fix-695-1083.dev.keepwork.com/wiki/home
