### ISSUE TITLE
【需求】笔记网站模版

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#704]
可以再提供一个电脑版本的笔记网站模版
与手机版的共用相同数据。
![image](https://user-images.githubusercontent.com/22001356/30955748-4c6538f8-a467-11e7-86e6-72ae1fec9c85.png)

参考#660

**Comment by Tibet0312** [comment]
手机版：
http://keepwork.com/tibet/weekly/%E7%AC%94%E8%AE%B0%E7%B1%BB-%E6%89%8B%E6%9C%BA%E7%89%88



网页版：
http://keepwork.com/tibet/weekly/%E7%AC%94%E8%AE%B0%E7%B1%BB%E6%A8%A1%E6%9D%BF-%E7%BD%91%E9%A1%B5
