### ISSUE TITLE
【优化】个人首页，优化手机效果

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#707]
手机版 设计下，方便用户打开自己的网站

**Comment by LiXizhi** [comment]
这个要好好设计下， 很多笔记类的网站， 可能也是通过这个入口进入的。 
- 手机上可以用列表的形式，参考Evernote的笔记本。 （其实PC版也可以用列表，显示更多有用信息）
- 我参与的项目可以放在tab中。不用都显示在首页。（待定）
- 可以考虑增加一个可DIY的popularity的数值，影响首页的项目排序。 例如个人笔记可以放在比较前面。

参考github: 支持pin to  homepage, 以及在另外的tab中显示全部：

![image](https://user-images.githubusercontent.com/94537/30998308-27814d30-a500-11e7-86f2-96683c2a62eb.png)

@leopoldchen

**Comment by leopoldchen** [comment]
将常用的网站标星置顶是一个通用设计。
个人首页的手机版要先考虑一下有哪些内容是要优先展示的，一些无必要的信息，建议可以直接移除，在手机版本不显示。部分内容可以直接考虑拆分到不同的tab或者新页面中。
在显示内容定下来的前提下，再考虑排版问题。

另外，一些响应区域需要调整，比如点击网站块就可以直接跳转到网站，而不是点击网站名。（好像在手机上点击网站名也无法跳转）

**Comment by leopoldchen** [comment]
建议先把手机上显示失常的页面整理出来，然后再安排时间优先级做调整，除了个人首页外，其他一些页面，比如新建网站页面等，也都是显示不正常的。

@Sandu1213 @duting1993
