### ISSUE TITLE
VIP相关流程问题修复

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#710]
已知的有以下几个问题：
- [ ] 订单中心与消费记录概念上的容易让人误解。正常情况只要用户下了单，不管支付与否，应该在订单中心有记录。目前的情况是未支付订单在订单中心无显示，而是在消费记录中有未支付记录，而且，这个未支付记录无法继续进行支付操作。一般的做法应该是归为待支付订单，可以选择继续支付。
- [ ] 关于钱包，一般钱包相当于是有用户余额的，这些余额的存在是为了支撑后续的一些其他交易，比如VIP自动续费，购买其他的一些服务等。目前下订单如果钱包没钱，那么选择充值，并直接从钱包扣钱，这个是合理的，但是表现出来的一个现象是钱包的余额永远为0。但是在一次服务器出错的情况下，我的钱包出现了余额，原因是充值成功而支付订单失败。在这种情况下购买VIP应该是优先从钱包余额扣费，但是发现并没有。

![jw9jmx_os m5dano5w xs3k](https://user-images.githubusercontent.com/1396883/30997811-e2066414-a4fc-11e7-90f9-2e0259bba8b1.png)

**Comment by onedou** [comment]
1.正常情况下，在发起订单之后才会有交易记录
2.现在支付成功，扣费失败的情况应该要分几种：
2.1. 机制原因，price字段可以更改导致支付金额和订单金额不符，建议：
        2.1.1. 跳转到支付页面时，使用订单号和第三方的api获取交易金额
        2.1.2. 第三方在收到支付成功信息后，对金额进行比对，如果不一致则退回交易金额
2.2 第三方接口返回失败，可以在用户再次支付时，减去钱包中的余额，支付剩余的金额。
2.3 创建订单后用户中途退出支付，建议在30分钟内可再次支付次交易，过期后自动关闭交易

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #2405](https://github.com/tatfook/keepwork/issues/2405) via [**ZenHub**](https://www.zenhub.com/)
