### ISSUE TITLE
【测试】keepwork界面功能对手机的兼容通测

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#712]
我们的策略是先完善PC版本，过程中对手机做兼容。
随着功能的完善，可以更多的关注keepwork对手机的兼容性问题。
跑一个通测，将有问题的内容整理出来。

**Comment by Sandu1213** [comment]
@duting1993 
这个和#707类似，我们先将Keepwork的整体功能在手机上过一遍，把显示失常及存在问题的整理出来先。

**Comment by Sandu1213** [comment]
已经汇总如下：（后续手机端的会在这个基础上进行更新）
http://keepwork.com/duting/shoujiceshi

**Comment by Sandu1213** [comment]
#768 #769 #770 #771 #772 #773 #774 #775 
待以上问题修改完成后，再重新回归验证一遍。
