### ISSUE TITLE
重建搜索服务器es数据索引

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#713]
旧的数据有一些是错误的，包括部分就是私有网站数据。
需要写一个重新build数据索引的脚本，重新将数据库数据导入es。注意：一般情况下，这种数据重建是支持无缝衔接的，在build新数据的同时，旧数据依然在线使用，当新数据build完成，再切到新数据上。

**Comment by leopoldchen** [comment]
@wxaxiaoyao 
可能需要咨询下天玑团队

**Comment by leopoldchen** [comment]
@William0911 可以重新改写数据结构，直接使用es9200服务

**Comment by William0911** [comment]
目前正在搭建新的搜索服务，页面搜索在上线后将会暂时只支持搜索新建的网页和搜索服务上线后更新过的页面。把已有网页内容放入搜索引擎中需要遍历git所有md文件，刷脚本时对服务器可能会有影响，暂时打算引入消息队列中间件后再进行。

**Comment by William0911** [comment]
新搜索服务请测试
用户以及站点搜索内容已引入
旧网页内容暂时需要更新过的或新创建的才能搜到
环境为 release环境
