### ISSUE TITLE
编辑器History功能优化

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#714]
- [ ] 产品设计
- [ ] UI设计
- [ ] 程序实现

**Comment by leopoldchen** [comment]
目前提供版本管理功能，可以检索和切换到旧版本的网页内容，但是这个相对来说还是比较弱。
[简书](https://jianshu.com) 提供的历史版本功能相对来说优雅许多，我们可以借鉴一下。

**Comment by azothli** [comment]
1. 如果编辑器当前有选中的编辑文件，直接填入查询文件的位置
2. 终止时间自动填入当前日期
3. 直接将最近的版本查询出来（执行一次查询）

4. 待确定：是否可以将git上的代码直接读出来，实现代码与预览的切换显示 @ZhangKaitlyn

**Comment by leopoldchen** [comment]
Issue moved to [tatfook/KeepWorkDesgin #12](https://github.com/tatfook/KeepWorkDesgin/issues/12) via [**ZenHub**](https://www.zenhub.com/)

**Comment by leopoldchen** [comment]
Issue moved to [tatfook/KeepWorkDesgin #13](https://github.com/tatfook/KeepWorkDesgin/issues/13) via [**ZenHub**](https://www.zenhub.com/)
