### ISSUE TITLE
【需求】开大方案

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#725]
今天说的学分的事情，加个Issue。 需要一个可以给开大的策划案。LinkedIn 是一个不错的参考。@liyu @c_清华

**Comment by azothli** [comment]
@caoyongfeng0214 
曹老师预计10月13日出ppt，到时候根据ppt进一步讨论

**Comment by leopoldchen** [comment]
@azothli  这个issue直接关了？
