### ISSUE TITLE
【需求】新建页面添加页面模版选择

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#731]
http://keepwork.com/keepwork/pwiki/pm/template/page_template

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/31528677-6b11d01c-b007-11e7-9d88-70c7776f5c41.png)


![image](https://user-images.githubusercontent.com/25898720/31528688-768c8644-b007-11e7-9a88-1985841796ba.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://stage.keepwork.com/wiki/wikieditor

**Comment by Sandu1213** [comment]
#913 关联issue

**Comment by Sandu1213** [comment]
1. 目前模板无法进行预览操作，请调整
2. 新建页选择下载模板，保存成功后添加画板，然后再查看时发现下载页面的显示比例不合理
![image](https://user-images.githubusercontent.com/21214285/32474994-83834d72-c3aa-11e7-9989-ce4873a5223c.png)

**Comment by ZhangKaitlyn** [comment]
第二个问题是和wiki布局模板有关

**Comment by duting1993** [comment]
http://bigfile.dev.keepwork.com/wiki/wikieditor

**Comment by Sandu1213** [comment]
1.预览问题已经解决；
2.布局相关的问题已经另外提单跟进（#935）
