### ISSUE TITLE
【Bug】账号退出后应该返回到首页，而不是个人主页

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#738]
## The problem
用户在进行退出登录操作后，页面应该跳转到主页面，而不是个人主页页面

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [dev.keepwork.com](http://dev.keepwork.com)
* Model:  登录注册功能

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问dev.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进行退出登录操作，确认退出后观察页面切换情况
* Expected Result:
1.返回主页面
* Actual Result:
1.停留在个人主页，刷新后也无效果

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31418727-59474f0e-ae6a-11e7-966d-a68b250f6d84.png)

**Comment by azothli** [comment]
按照设计
因为允许用户不登录就进行内容查看，所以登出保持了之前访问的内容。

**Comment by azothli** [comment]
@Sandu1213  确认下是否可接受，可接受的话，我们关闭

**Comment by Sandu1213** [comment]
可以，那该问题先关闭吧
