### ISSUE TITLE
【需求】系统网页：个人网站 增加星标功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#745]
![image](https://user-images.githubusercontent.com/22001356/31484766-27ff8ba0-af64-11e7-9d38-8763e77b6f0e.png)
是一个账号登陆者专有的整理功能。方便用户管理自己的众多可编辑网站。

在创建的网站之上，增加“星标网站”，仅供账号登陆者查看。
数据存在服务器。
自己创建与管理的网站上新增一个星星，可以点，切换是否为星标网站
选中后，会在上面复制一份做显示。

**Comment by Tibet0312** [comment]
“ 星标网站  ” 重命名为"重点网站" 

![image](https://user-images.githubusercontent.com/25898720/31592253-857695c4-b259-11e7-9ffd-3685bd65191e.png)
