### ISSUE TITLE
限制充值大小限额，防止溢出

### ISSUE THREAD

**Issue by onedou** [tatfook/wikicraft#748]
![image](https://user-images.githubusercontent.com/3422640/31500644-92686d0e-af2d-11e7-852a-3dcaa15f1dd7.png)
限制充值大小限额，防止溢出
最大的限制为多少元？

**Comment by Sandu1213** [comment]
请问，这里的限额大小是？

**Comment by Sandu1213** [comment]
Keepwork上已验证，哈奇上待验证。目前最大充值金额为1000元。
![image](https://user-images.githubusercontent.com/21214285/32874422-1b19a3b0-cacd-11e7-8f24-78aef8508725.png)

**Comment by Sandu1213** [comment]
哈奇上验证通过
![image](https://user-images.githubusercontent.com/21214285/32876782-48b3dc12-cad9-11e7-9f27-d29ea3213c79.png)
