### ISSUE TITLE
【调整】权限管理，提示文字调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#752]
例如：成员username同是存在......

调整为

例如：某用户同时存在于“编辑”权限与“禁止访问”权限的2个组，则会禁止访问。

**Comment by yuanoook** [comment]
Testsite: http://ui_words_752_833_834.dev.keepwork.com

**Comment by Sandu1213** [comment]
测试通过
![image](https://user-images.githubusercontent.com/21214285/32151485-329a7cda-bd58-11e7-9180-ed4ebb32a781.png)
