### ISSUE TITLE
【Bug-手机端】手机上第三方登录方式都不可用，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#768]
## The problem
手机上第三方登录方式都不可用，请调整

## Environment
* Device Info: IPhone SE/魅蓝 Note5
* OS Info:  IOS 10.3.2/ Android 6.0
* browser Info: chrome  61.0.3163.73 /自带浏览器
* URL: [keepwork.com](http://keepwork.com) 
* Model:  登录注册功能

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面

* Details:
1.分别用QQ，微信，微博，GitHub进行登录操作，观察登录结果

* Expected Result:
 1.  登录成功
* Actual Result:
1.登录失败
 

## Attachments (eg:logs/video/screenshot)
暂无（NA）

**Comment by ZhangKaitlyn** [comment]
测试了下，在手机版chrome第三方可以登录，但是在自带的浏览器以及QQ直接打开时，登录后本应该进到确认授权页面，但是直接返回到最开始的登陆页了

**Comment by William0911** [comment]
这个问题和#771同。 
我用iphone的safari试了一下，QQ、weibo、github都可以通过网页验证绑定登录，只有微信登录不可以，会跟PC端一样弹出一个二维码扫描登录，但不会通过网页的形式唤醒微信授权/登录页，这样确实很不方便。
如果不希望通过二维码形式登录就只能走微信app内部了，而且还需要跟微信官方要权限。我对几个比较大的网站（京东、微博、知乎）的手机页面进行调查后发现，只有和腾讯有合作的京东手机浏览器页面可以通过微信登录。是否可以考虑去掉手机网页端的微信登录？

**Comment by William0911** [comment]
这个问题和#771同。
我用iphone的safari试了一下，QQ、weibo、github都可以通过网页验证绑定登录，只有微信登录不可以，会跟PC端一样弹出一个二维码扫描登录，但不会通过网页的形式唤醒微信授权/登录页，这样确实很不方便。
如果不希望通过二维码形式登录就只能走微信app内部了，而且还需要跟微信官方要权限。我对几个比较大的网站（京东、微博、知乎）的手机页面进行调查后发现，只有和腾讯有合作的京东手机浏览器页面可以通过微信登录。是否可以考虑去掉手机网页端的微信登录？

**Comment by Sandu1213** [comment]
在keepwork环境上验证，使用chrome浏览器，确实只有微信不能进行登陆，请评估如何处理下。
@leopoldchen  @azothli

**Comment by azothli** [comment]
我试着用手机抓图，然后微信扫码，并没有登录，直接到了开放平台。
最低限度的就是抓图，然后用微信扫描够进入了。

**Comment by azothli** [comment]
重新验证了这个问题，应该是腾讯做了限制（微信自身的功能）
如果扫描来自摄像头，可以登录
如果来自图片，直接跳开放平台
应该是为了加强账号安全的。

因此，移动端的微信登录方式，可以不支持了，改为提示：

“因微信登录自身的限制，该功能仅限使用设备扫描进入。我们推荐您用手机微信登录电脑浏览器中的Keepwork。”

**Comment by William0911** [comment]
商讨后打算通过在微信二维码界面加提示解决

**Comment by Sandu1213** [comment]
由 #1091 进行跟进
