### ISSUE TITLE
【Bug-手机端】微信进行支付，支付不了，请排查处理

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#769]
## The problem
微信进行支付，支付不了，请排查处理

## Environment
* Device Info: IPhone SE/魅蓝 Note5
* OS Info:  IOS 10.3.2/ Android 6.0
* browser Info: chrome  61.0.3163.73 /自带浏览器
* URL: [keepwork.com](http://keepwork.com) 
* Model:  服务中心->购买VIP

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面

* Details:
1.进入VIP购买界面，选择微信进行支付，观察购买结果

* Expected Result:
 1.  购买成功
* Actual Result:
 1.  购买失败，无法进行支付
 

## Attachments (eg:logs/video/screenshot)
暂无（NA）

**Comment by onedou** [comment]
测试环境
http://fix.mobile.pay.stage.keepwork.com/

**Comment by Sandu1213** [comment]
回归不过，存在以下问题，请再排查：
1.支付宝无法跳转打开支付；
2.未安装微信时，进行支付，无法支付（不会自动打开对应的网页进行支付）
![image](https://user-images.githubusercontent.com/21214285/34087670-9049bbc2-e3df-11e7-8a32-f51c4f0fff0e.png)

**Comment by onedou** [comment]
好像安卓不行

**Comment by onedou** [comment]
我看看

**Comment by onedou** [comment]
微信支付 已加提示，支付宝应该可以了 @Sandu1213

**Comment by Sandu1213** [comment]
keepwork环境还是无法进行支付的，缺少用户的信息。
![image](https://user-images.githubusercontent.com/21214285/35392370-9d692396-021c-11e8-8a61-ff918bfad8be.png)

**Comment by onedou** [comment]
已更新，请测试

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/35659818-5fc161da-0743-11e8-915d-308c996a419e.png)

**Comment by Sandu1213** [comment]
release环境验证通过

**Comment by Sandu1213** [comment]
@onedou  big，release环境，登录后就去购买，第一次还是读取不到用户的信息（Apple手机上，已在2台手机上试过，都是这样，请知悉）

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/35710773-3ae4b8ec-07f4-11e8-911b-24b1bbbe7abb.png)

![image](https://user-images.githubusercontent.com/3422640/35710776-3e25756e-07f4-11e8-94a2-f19ff8f4425d.png)

我也是试了两台设备，是可以没有问题
