### ISSUE TITLE
【Bug-手机端】样式相关的问题汇总

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#775]
## The problem
样式相关的问题汇总

## Environment
* Device Info: IPhone SE/魅蓝 Note5
* OS Info:  IOS 10.3.2/ Android 6.0
* browser Info: chrome  61.0.3163.73 /自带浏览器
* URL: [keepwork.com](http://keepwork.com) 

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面

* Details:
1.请见截图
* Expected Result:  
1.请见截图
* Actual Result:  
1.请见截图 （也可参考链接：http://keepwork.com/duting/shoujiceshi/index）
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/31543189-a5096e0c-b047-11e7-8014-15bc0c9c78c3.png)
![image](https://user-images.githubusercontent.com/21214285/31543227-c8062724-b047-11e7-931b-0142e8258a1c.png)
![image](https://user-images.githubusercontent.com/21214285/31543245-d63ad09c-b047-11e7-838a-218e7dbd3cfa.png)
![image](https://user-images.githubusercontent.com/21214285/31543256-e1f231dc-b047-11e7-9163-ea2f781890af.png)
![image](https://user-images.githubusercontent.com/21214285/31543285-fd10c78a-b047-11e7-8eca-ca5f0c59f0f5.png)
![image](https://user-images.githubusercontent.com/21214285/31543313-11be96b2-b048-11e7-8fae-4d81921b40c5.png)
![image](https://user-images.githubusercontent.com/21214285/31543353-3c6052fc-b048-11e7-9b2b-ec2fe254ed5f.png)
![image](https://user-images.githubusercontent.com/21214285/31543380-5ad5e558-b048-11e7-9750-c92a99ce866d.png)
![image](https://user-images.githubusercontent.com/21214285/31543395-6a89eaf8-b048-11e7-9e10-5fee2af8e320.png)
![image](https://user-images.githubusercontent.com/21214285/31543411-7b9b45c6-b048-11e7-9f1e-532892adb540.png)
![image](https://user-images.githubusercontent.com/21214285/31543426-8b6c081e-b048-11e7-82df-305fec481d85.png)
![image](https://user-images.githubusercontent.com/21214285/31543432-93a64b84-b048-11e7-9076-4caf5df67fa5.png)
![image](https://user-images.githubusercontent.com/21214285/31543438-a1dd9db0-b048-11e7-8e45-c788d923e28a.png)
![image](https://user-images.githubusercontent.com/21214285/31543452-b42bd676-b048-11e7-95bf-ffb3c6cfa5dd.png)
![image](https://user-images.githubusercontent.com/21214285/31543470-c20da490-b048-11e7-8306-df4e20a926f9.png)
![image](https://user-images.githubusercontent.com/21214285/31543537-1a84a8ee-b049-11e7-8b7a-d25add6e4a46.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/32762397-0c65607e-c934-11e7-9f57-bd8c247e8241.png)
这个是用户页，需要用户自己设置
