### ISSUE TITLE
【bug】最上面的URL链接不对

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#778]
![2o3_afe01s a uizn5u c7r](https://user-images.githubusercontent.com/28430070/31591939-2cff9c4e-b257-11e7-819b-9d192f1679c2.png)
http://keepwork.com/official/company/building

**Comment by ZhangKaitlyn** [comment]
若配置了url，则首行为link，否则为普通文本
![image](https://user-images.githubusercontent.com/18642919/31762295-5d244562-b4ed-11e7-9aba-d0b0eb594365.png)

**Comment by Sandu1213** [comment]
验证通过，目前可以设置为有链接和无链接的情况，由页面编写人员自己管理配置，默认是无链接的情况。
