### ISSUE TITLE
【Bug】输入框超限后建议给出提醒而不是自动截断，且防止出现乱码的情况

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#782]
## The problem
1.输入框超过限制后，会出现自动截断的情况，用户无法感知，用户体验不好
2.个人简介超过169字时会出现乱码，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:   设置中心->我的资料

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.对我的资料里输入框进行输入操作，观察当输入超限后的处理方式
2.对个人简介输入170多字后，到个人主页页面观察显示情况

* Expected Result:
1.输入超限后会有相应提醒
2.显示信息正确，无乱码的情况
* Actual Result:
1.超限后无提醒
2.存在显示乱码的情况
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31593216-e193d3a2-b25f-11e7-8c4e-87ef8dc9067b.png)

**Comment by Sandu1213** [comment]
@azothli 宇哥，请定义下输入框的长度限制及超限后提示语信息。

**Comment by azothli** [comment]
个人介绍输入内容数量不做限制。(之后其他地方调用，可以显示完整的）
个人首页显示的量控制在8行，超出后面截断，显示...... @ZhangKaitlyn @Tibet0312

**Comment by yuanoook** [comment]
Test site: http://ui_782_805.dev.keepwork.com/

**Comment by Sandu1213** [comment]
页面显示不合理，且会低概率出现修改个人简介信息失败的情况，请排查，谢谢
![image](https://user-images.githubusercontent.com/21214285/32207716-c8f61802-be38-11e7-9d99-9f4dde4a6bfd.png)

**Comment by Sandu1213** [comment]
验证通过，目前个人简介最多显示8行，超过8行以省略号显示
![image](https://user-images.githubusercontent.com/21214285/32262627-947f64f6-bf10-11e7-9001-1130f9136336.png)
