### ISSUE TITLE
【需求】在新的编辑器mod中增加插入ctrl+v图片

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#785]

**Comment by onedou** [comment]
reference https://codepen.io/netsi1964/pen/IoJbg

**Comment by onedou** [comment]
readAsDataUrl https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

**Comment by Sandu1213** [comment]
**ctrl + V 的图片限制为：**
1.分辨率 为520 *520 以下；
2.文件大小小于1MB。
以上2个条件同时满足的文件才能 粘贴进去。

**Comment by Sandu1213** [comment]
目前ctrl + V存在的问题：
1.ctrl + V多次后，删除图片，画板的画布没有自动居中；
2.ctrl + v粘贴后的图片应该也要控制下最大的显示比例，否则会出现页面超标的情况；
3.文件大小超限后，提示框样式很丑，请调整；
![image](https://user-images.githubusercontent.com/21214285/33063661-13664bcc-cede-11e7-88e9-2adf08bcbb81.png)

4.还有就是背景有线条，影响不大，可以处理的话建议处理下。
