### ISSUE TITLE
【Bug】页面切换后,再次重新打开缺少初始化操作

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#789]
## The problem
页面切换后,再次重新打开缺少初始化操作

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  设置中心->账号安全

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号
* Details:
1.进入修改密码界面，对输入框进行输入，输入完成后切换到其他页面，例如“我的动态，我的关注等”，切换完成后再次打开修改密码页面，观察页面显示
2.用一个已绑定的手机号再次进行绑定操作，当出现提示信息后，关闭页面，修改手机号码，再次打开
绑定页面，观察页面显示

* Expected Result:
1.页面显示合理
2.页面显示合理
* Actual Result:
1.页面显示不合理，应该重新进行初始化
2.页面显示不合理，应该重新进行初始化

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31601327-1a2cbd10-b28c-11e7-8529-0a353713e00a.png)
![24](https://user-images.githubusercontent.com/21214285/31601332-200da80c-b28c-11e7-91c8-5f09f78d56a2.png)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://init.dev.keepwork.com/wiki/user_center

**Comment by Sandu1213** [comment]
在release环境验证通过
