### ISSUE TITLE
【需求】编辑器预览支持缩放

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#79]
编辑器预览支持缩放

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/25032494/feedc43e-2106-11e7-940d-6c941288d3ba.png)
考虑参考acrobat reader

**Comment by Tibet0312** [comment]
![image](https://cloud.githubusercontent.com/assets/25898720/25078200/71a426fe-2363-11e7-99f3-a77162ed36a0.png)
