### ISSUE TITLE
【Bug】个人动态里数据显示需要调整下样式

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#792]
## The problem
个人动态里数据显示需要调整下样式

## Environment
* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  设置中心->我的动态

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
3.个人动态页面存在数据
* Details:
1.对个人动态页面进行查看

* Expected Result:
1.请见截图
* Actual Result:
1.请见截图
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31603823-f1f99cac-b293-11e7-9570-9ef85488f44b.png)

**Comment by Tibet0312** [comment]
![image](https://user-images.githubusercontent.com/25898720/31607424-dcd72b40-b29e-11e7-8508-feeff723c427.png)
