### ISSUE TITLE
【Bug】已关注的用户如果存在粉丝列表里，关注状态显示不对

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#795]
## The problem
已关注的用户如果存在粉丝列表里，关注状态显示不对

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  个人主页->粉丝

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.对用户A进行关注操作，关注成功后，观察关注作者列表
2.用户A同时对该用户进行关注，用户A出现在粉丝列表里，观察关注状态是否正确

* Expected Result:
1.关注状态应该为‘已关注’
* Actual Result:
1.关注状态显示不对
 

## Attachments (eg:logs/video/screenshot)
![-](https://user-images.githubusercontent.com/21214285/31606694-65d9f6c8-b29c-11e7-8ed4-0667bb406ba0.png)

**Comment by Sandu1213** [comment]
@azothli 宇哥，请定义下关注状态是分为“已关注”和“关注” 还是“取消关注”和“关注”？

**Comment by azothli** [comment]
这里是关注没错
意思是 点击关注自己的粉丝（偶像关注粉丝）。
这里应该是对粉丝的关注状态进行读取，如果已经关注，则显示“取消关注”，否则，显示“关注”

**Comment by Sandu1213** [comment]
那这里应该显示“取消关注” （因为已经对粉丝进行关注过了，请知悉）
