### ISSUE TITLE
【Bug】新建网站页面的Cname，建议加上必须开通VIP才能使用的说明

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#797]
## The problem
新建网站页面的Cname，建议加上必须开通VIP才能使用的说明

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  网站管理->新建网站

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入网站管理->新建网站，对新建网站页面进行查看

* Expected Result:
1.Cname使用必须开通VIP的说明
* Actual Result:
1.请见截图
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31645072-84a99f0a-b32c-11e7-9561-595ada55ac60.png)

**Comment by azothli** [comment]
调整文字：VIP可在网站设置中进行cname转发
@ZhangKaitlyn

**Comment by Sandu1213** [comment]
验证通过，涉及VIP才能使用的功能目前也加上了购买引导项
