### ISSUE TITLE
【Bug】企业模板里的样式风格请保持一致

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#798]
## The problem
企业模板里的样式风格请保持一致

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  网站管理->新建网站

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入网站管理->新建网站，选择模板时选择企业模板，观察模板的样式风格是否一致

* Expected Result:
1.样式风格一致
* Actual Result:
1.样式风格不一致
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31645303-eb13f154-b32d-11e7-9321-ba9af70a182f.png)

**Comment by azothli** [comment]
跟整理工作一起，不存在这个问题了
