### ISSUE TITLE
PPT模块开发

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#803]
- 参考 https://github.com/gamell/markpress (https://github.com/impress/impress.js/),  https://github.com/hakimel/reveal.js
- 使用 impress.js or reveal.js

自动将markdown 转换为 presentation slide show

增加一个PPT播放按钮。 用 `---` 作为分隔符

新增命令
```
@wiki/js/ppt
```
渲染为一个`开始|结束演示`, 的按钮, 点击开始后自动将之后同级别的所有HTML，自动format成slides的形态。 
format的原则是 遇到 `<h1,h2,h3>`或`<hr>`自动形成一个slide section. 
点击退出， 恢复正常。

**Comment by onedou** [comment]
researching

**Comment by onedou** [comment]
阿发制作

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #495](https://github.com/tatfook/keepwork/issues/495) via [**ZenHub**](https://www.zenhub.com/)
