### ISSUE TITLE
ICP备案后台日志记录

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#804]
ICP备案日志需求：记录用户操作记录，ip，登入，登出，交易，修改，订单等，需要提供搜索

@azothli @Xuntian @wxaxiaoyao  目前使用之前动态生成的方式添加这部分日志信息，可以覆盖到登录、注册、用户信息修改、网站增删改等

**Comment by Sandu1213** [comment]
目前日志记录范围为：

**Comment by Sandu1213** [comment]
日志功能验证通过，后续有优化或者调整再跟进
