### ISSUE TITLE
【调整】编辑器，keepwork图标，替换成用户头像

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#805]
在编辑器中，非登录状态，显示系统改头像，用户点击可以弹出登录框，登录后进行编辑
已经登录状态下，点头像，回到个人主页。

**Comment by Tibet0312** [comment]
未登录状态头像显示：
![image](https://user-images.githubusercontent.com/25898720/31703759-aed9efe8-b410-11e7-8937-b6d88700489a.png)


已登录显示用户头像;
![image](https://user-images.githubusercontent.com/25898720/31706057-365a3cda-b41a-11e7-87b4-c61fe226ffa8.png)

**Comment by yuanoook** [comment]
设计稿和产品逻辑有偏差，当前情况没有登陆是拿不到页面可编辑的内容的，也看不见页面列表。请 @azothli @Tibet0312 确认

**Comment by yuanoook** [comment]
经确认，点击登陆逻辑暂不变更，只把Logo更换成头像，方便用户辨识当前用户状态。

**Comment by yuanoook** [comment]
经确认，点击登陆逻辑暂不变更，只把Logo更换成头像，方便用户辨识当前用户状态。

**Comment by yuanoook** [comment]
Test site: http://ui_782_805_214.dev.keepwork.com/

**Comment by Sandu1213** [comment]
只有登录状态下才能查看网页编辑器，图标显示正确
![image](https://user-images.githubusercontent.com/21214285/32203293-30b50276-be1d-11e7-9d3a-a3480c2755af.png)
