### ISSUE TITLE
【bug】页面编辑器，添加模板，评论区域，时间应该为冒号，且头像应该和评论人账号头像一致

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#806]
![s9ryq2 f cj dms9fejrx f](https://user-images.githubusercontent.com/28430070/31703225-4b33a0bc-b40e-11e7-983e-a8c4ab96eceb.png)

**Comment by ZhangKaitlyn** [comment]
test link: http://fix806.dev.keepwork.com/kaitlyn/bigfile/index

**Comment by Sandu1213** [comment]
用户未登陆时进行评论，应该引导用户进行登陆，目前缺少引导；
