### ISSUE TITLE
【调整】cname转发设置，支持多条

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#81]
cname转发设置，支持多条

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/23890265/00e8ecbc-08cc-11e7-853f-bacb0f0e7f31.png)
调整成支持多条的方式

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24282670/f86f90fe-109b-11e7-9d71-324e0f6bde8b.png)
已调整
