### ISSUE TITLE
【Bug】在编辑器页面点击不同的网页，会出现页面风格显示不同的情况，请保持一致

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#811]
## The problem
在编辑器页面点击不同的网页，会出现页面风格显示不同的情况，请保持一致

## Environment
* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model: 网页编辑器

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.打开新的帮助页面（http://keepwork.com/official/help/index）
2.点击“Edit”按钮，进入网页编辑器页面
3.对keepwork帮助项目下面的页面进行切换查询，观察页面显示变化情况

* Expected Result:
1.页面排列整齐，显示风格一致
* Actual Result:
1.显示风格不统一，请优化调整
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31750556-787b1b0e-b4b3-11e7-8b21-11cff1c7c528.gif)

**Comment by yuanoook** [comment]
`<style type="text/css">body{text-align:center;}</style>` affected it.

**Comment by Sandu1213** [comment]
验证不通过，请再排查 @ZhangKaitlyn
