### ISSUE TITLE
商品管理

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#813]
目前商品列表（goods）hardcode在项目源码中，因提取存放到数据库中，在后台dashboard中添加goods管理

**Comment by onedou** [comment]
此功能由TPP处理 @leopoldchen 请 @yq33z3069 上传 goods manager feature 分支

**Comment by leopoldchen** [comment]
有进展吗？

**Comment by onedou** [comment]
tpp 在 berrychat 叫测试了 @leopoldchen

**Comment by onedou** [comment]
测试地址 http://goods_manager.dev.keepwork.com/ @Sandu1213

**Comment by Sandu1213** [comment]
@duting1993 可以一起验证一下，测试环境为: http://goods_manager.dev.keepwork.com/

**Comment by Sandu1213** [comment]
验证不过，请重新调整下
![image](https://user-images.githubusercontent.com/21214285/33316877-7745084e-d470-11e7-8a6a-daaa06ed22e4.png)

**Comment by Sandu1213** [comment]
修改的功能也需要调整下
![image](https://user-images.githubusercontent.com/21214285/33317126-4112f582-d471-11e7-80e6-139db2680dca.png)

**Comment by onedou** [comment]
支付那里是配置问题

**Comment by onedou** [comment]
修改那里要读记录的参数

**Comment by Sandu1213** [comment]
1.商品管理页面，点击“修改”按钮后，再去查看详情，数据就看不到了
2.修改时应该带出appname相关的信息，否则，很容易覆盖了

**Comment by Sandu1213** [comment]
keepwork 的VIP购买在http://goods_manager.dev.keepwork.com 环境验证通过
