### ISSUE TITLE
keepwork支付服务

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#814]
Keepwork的支付模块提供的是类似支付宝的服务。不处理订单内容和具体信息，而只是完成钱的支付。

 第三方对接keepwork支付服务需要注册oauth app，提供callback url来完成支付与具体业务的对接。

@onedou 请在评论中贴一下之前设计的流程。

**Comment by onedou** [comment]
This issue is too long time. I shut it down first.
