### ISSUE TITLE
【调整】新建网站流程中关于cname的说明

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#82]
![image](https://cloud.githubusercontent.com/assets/22001356/23890804/63cabef8-08ce-11e7-972e-3a55be1e378e.png)

**Comment by ZhangKaitlyn** [comment]
已修改
![image](https://cloud.githubusercontent.com/assets/18642919/23941663/a13c69c2-09a4-11e7-85e6-a32b0a5061f6.png)
