### ISSUE TITLE
【调整】第三方注册增加同意用户许可协议的内容

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#831]
![image](https://user-images.githubusercontent.com/22001356/31813760-16a1efa4-b5ba-11e7-8250-c4eb40ec8b1a.png)

**Comment by yuanoook** [comment]
Test site: http://join_831.dev.keepwork.com/

**Comment by News2017** [comment]
暂时只验证了github的登录方式，QQ/wechat/微博的登录方式需要正式环境才能验证。
![image](https://user-images.githubusercontent.com/32192965/32202857-88a636b0-be1a-11e7-9974-fc6e43645a87.png)

**Comment by Sandu1213** [comment]
目前只验证了GitHub的登录方式，QQ/wechat/微博的方式都需要正式环境才能验证。
![image](https://user-images.githubusercontent.com/21214285/32202876-acaeca36-be1a-11e7-85cf-dfa792fc0826.png)
