### ISSUE TITLE
【调整】搜索，tab页面名称

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#833]
![image](https://user-images.githubusercontent.com/22001356/31857297-a8aa023e-b70d-11e7-8353-0b75a32d2e77.png)
调整
用户页---》页面

**Comment by yuanoook** [comment]
Testsite: http://ui_words_752_833_834.dev.keepwork.com

**Comment by Sandu1213** [comment]
测试通过
![image](https://user-images.githubusercontent.com/21214285/32151392-65330122-bd57-11e7-8f85-797ce30a5c96.png)
