### ISSUE TITLE
【调整】个人首页-》活动次数 文字调整

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#834]
![image](https://user-images.githubusercontent.com/22001356/31857308-6e8af116-b70e-11e7-96d2-5403a681d408.png)
调整为   活跃度

**Comment by leopoldchen** [comment]
@ZhangKaitlyn 这几个调整可以放在一个branch里 做，当做bug fix来处理，从Release分支checkout新分支做。

**Comment by yuanoook** [comment]
Testsite: http://ui_words_752_833_834.dev.keepwork.com

**Comment by Sandu1213** [comment]
测试通过
