### ISSUE TITLE
【Bug】对浏览器的显示比例进行缩放时，网页编辑器里的内容会出现遮挡的情况，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#838]
## The problem
对浏览器的显示比例进行缩放时，网页编辑器里的内容会出现遮挡的情况，请调整

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  网页编辑器

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.打开[介绍页面](http://keepwork.com/offical/open/index)
2.点击‘Edit’进入编辑器页面，然后对浏览器显示比例进行缩放，观察显示结果

* Expected Result:
1.显示数据正确
* Actual Result:
1.显示不合理，请调整

**Comment by yuanoook** [comment]
浏览器缩放的表现，已经超出了网页代码的控制范围。不同浏览器不同缩放级别表现由浏览器控制，不建议修改。
