### ISSUE TITLE
对于大陆，必须手机号（实名认证）才能CNAME， 甚至是公开连接。 

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#84]
这两天交流中， 提出一个网站内容管理的问题。 4月份，我们可能要考虑下， 对于大陆，必须手机号（实名认证）才能CNAME， 甚至是公开连接。 

这样封号就可以直接将手机号也一并封掉。 

封号的用户只能自己登录编辑自己的网站。其他人都无法查看了。
这里需要设计一些内容上的规则， 包括举报。

**Comment by azothli** [comment]
举报在用户的信息页有。确定不实名就不能cname么？我之前看到的资料是没什么限制。

**Comment by LiXizhi** [comment]
实名对我们封号有些帮助， 避免大量小号。这个先放后面考虑

**Comment by azothli** [comment]
cname应该没限制，但是按照现在的管理办法，我们这个用户创建内容的方式，全部作者应该都需要实名的。
转入实名的开发。
