### ISSUE TITLE
【Bug】设置画板背景色为非白色，设置成功后绘制的图形在页面编辑器里显示不对，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#845]
## The problem
设置画板背景色为非白色，设置成功后绘制的图形在页面编辑器里未显示对应的颜色，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  页面编辑器->绘图

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.从个人主页页面点击“页面编辑器”，进入编辑器页面，选择模板->画板进行添加
2.进行绘图操作，设置背景色为非白色，绘图完成后观察图形在页面编辑器里的展示情况

* Expected Result:
1.图形显示正确
* Actual Result:
1.背景色显示不对
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/31882999-184b64d0-b81b-11e7-8de9-901f61acee6c.png)

**Comment by onedou** [comment]
背景颜色在preview里面不可用，建议先隐藏此功能

**Comment by Sandu1213** [comment]
该功能已被屏蔽了，暂不关注了。
