### ISSUE TITLE
【需求】mod增加编号功能

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#846]
方便整理区分定位
用户可以根据mod编号来快速找到对应的mod
编号可以在创建的时候由创建者指定
使用数字编号，之后会给这个编号一定的意义。

**Comment by wxaxiaoyao** [comment]
数据库自带的_id  可做为编号，   但此编号不可更改。   下周可以加个编号字段，使其可以更改。

**Comment by yuanoook** [comment]
根据后面沟通调整情况：
1.调整布局为左右布局，右侧导航支持二级目录
2.搜索位置调整，增加模糊搜索支持

test site: http://mod_ui_update.dev.keepwork.com/yuanoook

**Comment by Sandu1213** [comment]
mod里的问题记录：
1.关注页面里的mod，收藏星号都要实体
2.空白页需要有默认图（可看列表页面）
3.视频mod，3D海洋mod及其他多媒体mod组合时，页面显示有误
http://10.27.2.69:8099/yuanoook/about/index

**Comment by yuanoook** [comment]
1, 2, 已修正；
* mod 的冲突，请单独提单，改相应的 mod，标记为 mod 优化.

**Comment by Sandu1213** [comment]
问题1,2已经验证通过；
问题3.会针对mod组合进行专门的测试，在另外跟踪；
问题4.已与产品沟通过，按全部模块来处理，不需要分小的范围来。
