### ISSUE TITLE
画板模块支持思维导图

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#851]
draw.io最近刚刚开发了一个新的plugin,在测试阶段。 如下：

- https://www.draw.io/?p=trees
- https://about.draw.io/organization-charts-and-mind-maps-in-draw-io/

需要跟进一下这个控件，支持mind map. 

![image](https://user-images.githubusercontent.com/94537/32049470-b57c94fc-ba7f-11e7-847b-31f679c444c5.png)

**Comment by onedou** [comment]
是plugin来的

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #493](https://github.com/tatfook/keepwork/issues/493) via [**ZenHub**](https://www.zenhub.com/)
