### ISSUE TITLE
【Bug-大文件】上传相同的文件时，缺少判断

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#857]
## The problem
上传相同的文件时，缺少判断

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入设置中心->服务中心，选择“我的网盘”
2.选择同一个文件同时进行上传，观察上传结果

* Expected Result:
1.存在相关提醒
* Actual Result:
1.缺少相应的提醒 (截图里的问题1请忽略）
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/32091073-302392d2-bb25-11e7-8e2e-d776bf563844.png)

**Comment by ZhangKaitlyn** [comment]
测试地址： http://bigfile857.dev.keepwork.com/wiki/wikieditor
