### ISSUE TITLE
在页面编辑器里进行添加时，这里需要调整下

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#858]
## The problem

在页面编辑器里进行添加时，这里需要调整下

## Environment

* OS Info: Window10
* browser Info: chrome61.0.3163.100
* URL: [keepwork.com](http://keepwork.com) 
* Model:  新建网站

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器-新建网站-选择模板下一步

* Expected Result:
1.页面编辑器进行添加时，页面编辑器中的新建访问地址要与主页新建网站和网站管理-新建网站的文字描述一致
* Actual Result:
1.在页面编辑器里进行添加时，与主页新建网站和网站管理-新建网站的文字描述不一致
 

## Attachments (eg:logs/video/screenshot)

![image](https://user-images.githubusercontent.com/28430070/32091089-3f7a5054-bb25-11e7-9dba-8d9cc764075a.png)

**Comment by yuanoook** [comment]
test site: http://10.27.2.69:8099/wiki/user_center

**Comment by Sandu1213** [comment]
验证通过
