### ISSUE TITLE
【Bug-大文件】在页面编辑器直接拖拽大于10MB的文件进行上传， 没有自动打开大文件上传页面且不支持上传应用程序

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#859]
## The problem
在页面编辑器页面直接拖拽大于10MB的文件进行上传，没有自动打开大文件上传页面且不支持上传应用程序

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器页面，直接拖拽大于10M的文件进行上传操作，观察上传情况
2.直接上传应用程序，观察上传结果

* Expected Result:
1.自动打开大文件上传窗口进行上传
2.可以上传应用程序，上传方式为大文件上传
* Actual Result:
1.没有打开大文件上传页面
2.不能上传应用程序
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/32091714-eb3a38bc-bb27-11e7-85b0-143153d5ed0f.png)

**Comment by LiXizhi** [comment]
@azothli 当文件大于10M时，需要提示用户是否决定上传qiniu，并需提示对容量的影响。是否需要弹出qiniu上传框，用户可能需要决定插入url还是插入mod

**Comment by azothli** [comment]
***正在上传文件  5KB/10KB (50%)***
***网盘：正在上传文件  5Gb/10Gb (50%)，上传完成后可以在网盘中管理，上传过程中请不要刷新窗口***

**Comment by Sandu1213** [comment]
存在问题：
1.提示语不合理
2.上传10M以上的文件上传成功后，不是插入文件的效果（只有一个文件名而已）
3.插入过大的文件(1.8G的），会出现页面崩溃的情况
![image](https://user-images.githubusercontent.com/21214285/33587957-639bd3f0-d9ab-11e7-9619-e770af95f694.png)
4.上传的过程，还能进行编辑，与需求说明的不符

**Comment by ZhangKaitlyn** [comment]
测试地址： http://bigfile.dev.keepwork.com/wiki/wikieditor#/kaitlyn/bigfile/index

**Comment by ZhangKaitlyn** [comment]
超过1GB的文件，弹窗提示，让用户选择打开大文件还是继续上传还是取消上传

**Comment by duting1993** [comment]
第一次拖拽1点多g的文件，弹窗提示，把页面编辑器中的文件删除，再次拖拽，浏览器崩溃

**Comment by duting1993** [comment]
视频小于10M时，拖拽的文件，预览里没有转换成小视频
![image](https://user-images.githubusercontent.com/28430070/33864597-61cfbb36-df28-11e7-897b-0bec3169b509.png)

**Comment by duting1993** [comment]
![oye lh7k deq0 601 95](https://user-images.githubusercontent.com/28430070/33864736-2ce3bff2-df29-11e7-92c5-139c60407aaa.png)
上传的1点多g的文件，弹窗之后，我点×关掉他，页面编辑器里，文字应该不显示
