### ISSUE TITLE
github login error

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#86]
github 登录还是用ｐａｒａｃｒａｆｔ．ｗｉｋｉ
![image](https://cloud.githubusercontent.com/assets/94537/24098687/bf6f168c-0da6-11e7-837b-3e1334bff80d.png)

**Comment by wxaxiaoyao** [comment]
id已替换过来， 用户需先绑定过github(即用户信息存在GitHubID)才能登陆成功， 否则根据githubId查找不到用户信息，不会自动创建用户导致登陆失败
