### ISSUE TITLE
【bug】设置中心-我的动态-组织/关注，当组织有数据时，在查看关注页面会出现这种白屏的情况

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#860]
## The problem
设置中心-我的动态-组织/关注，当组织有数据时，在查看关注页面会出现这种白屏的情况

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  设置中心

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
3.创建新网站
* Details:
1.进入设置中心->我的动态

* Expected Result:
组织无数据时，关注无数据时，页面显示暂无相关内容
组织有数据时，关注无数据时，关注也要显示暂无相关内容
* Actual Result:
1.组织有数据时，查看关注页面会出现白屏的情况
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/28430070/32091905-d8d4579c-bb28-11e7-8ee0-dd7a22786481.png)

**Comment by yuanoook** [comment]
test site http://10.27.2.69:8099/wiki/user_center
