### ISSUE TITLE
编辑个人介绍，字数过长时，展示不合理，请调整

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#865]
## The problem
编辑个人介绍，字数过长时，展示不合理，请调整

## Environment

* OS Info: Window10
* browser Info: chrome 62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model: 个人介绍

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入网站管理-网站设置
2.编辑100字以上，点击保存

* Expected Result:
1.个人主页，个人介绍，不能超出
* Actual Result:
1.展示不合理，个人介绍，字数过多，超出
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/28430070/32093134-d655a458-bb2d-11e7-843b-740bb730e178.png)

**Comment by Sandu1213** [comment]
问题依然存在，请排查。
![image](https://user-images.githubusercontent.com/21214285/32480710-1be29f3a-c3cb-11e7-9052-27af6c482f17.png)
