### ISSUE TITLE
【Bug-大文件】上传文件列表缺少文件类型的图标，请优化

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#868]
## The problem
上传文件列表缺少文件类型的图标，请优化

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入设置中心->服务中心，选择“我的网盘”
2.选择不同类型的文件进行上传操作，类型包含图片，视频，pdf文档，doc文档及应用程序等
3.观察上传列表里的展示情况
* Expected Result:
1.存在文件图标，与需求一致
* Actual Result:
1.不存在文件图标，请优化完善
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/32093090-a9c111ac-bb2d-11e7-8290-da09fac4d25a.png)

**Comment by Tibet0312** [comment]
图片：
![image](https://user-images.githubusercontent.com/25898720/32256113-1930af80-bee8-11e7-849f-57c471ce5d5a.png)
文件：
![image](https://user-images.githubusercontent.com/25898720/32256131-2d93681e-bee8-11e7-96b6-54f0d553148d.png)
音频：
![image](https://user-images.githubusercontent.com/25898720/32256147-44097d7c-bee8-11e7-819e-46197c732800.png)

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/33255627-8953f7d0-d389-11e7-921b-c155ee05c834.png)
![image](https://user-images.githubusercontent.com/18642919/33255634-95fd081e-d389-11e7-8fb5-e1c764394795.png)

**Comment by ZhangKaitlyn** [comment]
测试地址： http://bigfile.dev.keepwork.com/wiki/user_center?userCenterContentType=services&userCenterSubContentType=qiniuPan

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/33298059-35a671a8-d41f-11e7-9bcd-0c875cc6ba19.png)
