### ISSUE TITLE
【Bug-大文件】需要增加“全选”按钮，同时添加批量下载的功能，提高用户体验

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#870]
## The problem
需要增加“全选”按钮，同时添加批量下载的功能，提高用户体验

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
3.网盘里已经存在大量文件
* Details:
1.进入设置中心->服务中心，选择“我的网盘”
2.对大量文件进行批量下载操作
3.对大量文件进行批量删除操作

* Expected Result:
1.批量下载成功
2.有全选按钮，很方便操作
* Actual Result:
1.无批量下载
2.缺少全选按钮，操作极不方便
 

## Attachments (eg:logs/video/screenshot)
暂无

**Comment by LiXizhi** [comment]
@azothli 这块是否需要补充设计

**Comment by ZhangKaitlyn** [comment]
![image](https://user-images.githubusercontent.com/18642919/33259455-eaa99c16-d397-11e7-9b87-c63cadd0b19e.png)

**Comment by ZhangKaitlyn** [comment]
测试环境： http://bigfile.dev.keepwork.com/wiki/user_center?userCenterContentType=services&userCenterSubContentType=qiniuPan

**Comment by Sandu1213** [comment]
还存在问题，请再调整
![image](https://user-images.githubusercontent.com/21214285/33298021-ff09c9b0-d41e-11e7-9ce9-2354f65064ca.png)
