### ISSUE TITLE
【需求】应用中心新加医时空

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#876]
http://www.sktcm.com 

医时空，增加到应用中心 健康分类
![qq 20171027171539](https://user-images.githubusercontent.com/22001356/32096936-85334848-bb3a-11e7-8432-91bd42a1309c.jpg)

**Comment by Sandu1213** [comment]
测试地址：http://bigfile.dev.keepwork.com/wiki/apps##jiankang
测试通过。

![image](https://user-images.githubusercontent.com/21214285/32151642-811bff40-bd59-11e7-9fc0-585a6bad412d.png)
