### ISSUE TITLE
【Bug-大文件】重名判断里缺少更新文件导致重名的判断

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#877]
## The problem
重名判断里缺少更新文件导致重名的判断

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.62
* URL: [keepwork.com](http://keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
3.我的网盘已经存在多个文件
* Details:
1.进入设置中心->服务中心，选择“我的网盘”
2.网盘已经存在文件B，将文件A直接更新为文件B，观察更新结果

* Expected Result:
1.更新时会提示，相同文件已经存在
* Actual Result:
1.文件可以重名，同名文件存了多份

**Comment by duting1993** [comment]
重复问题，该问题#866
