### ISSUE TITLE
一网乾坤开发平台 UI调整

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#881]
## 美化开发平台页面：
- http://keepwork.com/official/open/
- 同时美化下，keepwork上的公司基本_theme, bottom模版

参考腾讯或阿里巴巴的开放平台的UI。 
- https://open.1688.com/
- http://open.qq.com/

## 调整下面URL，加入开发平台入口
![image](https://user-images.githubusercontent.com/94537/32203783-777b0464-be20-11e7-94ff-0774320c38dc.png)

**Comment by Tibet0312** [comment]
页面优化已完成

**Comment by Sandu1213** [comment]
开放平台进入后的链接页面是最新的，地址：http://keepwork.com/official/open/

**Comment by Sandu1213** [comment]
已上线，该issue关闭
