### ISSUE TITLE
画板模块Preview需要能自动缩小

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#883]
画板模块Preview，在手机上需要能自动缩小展示， 而不是只显示一部分，需要滚动。和我们图片的逻辑一致

**Comment by onedou** [comment]
先overflow:scroll先

**Comment by onedou** [comment]
http://fix.diagram.for.mobile.stage.keepwork.com/

**Comment by Sandu1213** [comment]
没有看到效果，请再帮忙确认下
![image](https://user-images.githubusercontent.com/21214285/34200954-ef84523a-e5ad-11e7-9163-7da235e10213.png)

**Comment by onedou** [comment]
不是在编辑器下
是在浏览模式下

**Comment by Sandu1213** [comment]
@onedou 一样的呀，Big，都看不到，你那边可以看到么？

**Comment by onedou** [comment]
http://fix.diagram.for.mobile.stage.keepwork.com/testv2/tttt/index
应该是保存失败了，我这个可以
我把overflow:scroll改成overflow-x: auto了
