### ISSUE TITLE
【需求】keepwork国际化版本

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#911]
圣诞节前上线英语版本

按照浏览器语言，自动显示对应的语言版本
首页增加语言切换功能

先做英文版

**Comment by Tibet0312** [comment]
语言切换：

![image](https://user-images.githubusercontent.com/25898720/32768783-3e589df6-c954-11e7-9fd0-dfd9aa60eeb5.png)


![image](https://user-images.githubusercontent.com/25898720/32768733-0f043db2-c954-11e7-9100-63e982080283.png)
