### ISSUE TITLE
【调整】top条，主logo点击可下拉

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#92]
点击logo即可激活下拉条
![image](https://cloud.githubusercontent.com/assets/22001356/24129136/6c41b9f4-0e1b-11e7-9448-bef7a8782ff5.png)
下拉的小箭头需要强化下视觉，要用户知道有下拉

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/24180595/b3376180-0ef0-11e7-84ca-cfd8b2545b19.png)

另外设计下Logo

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24242101/b3afc1dc-0ff1-11e7-8820-ce9851709aec.png)
已修改
