### ISSUE TITLE
确保生产环境与测试环境分离

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#921]
生产环境与开发测试环境分离是软件研发中的一个基本原则。

目前开发环境和测试环境使用的都是production的Gitlab。考虑到之后会启用自动化测试，对生成环境的影响会越来越大，会有大批量的垃圾数据生成。因此，搭建测试环境的Gitlab需尽快进行。

- [ ] 为测试和开发环境搭建Gitlab @Xuntian

**Comment by Xuntian** [comment]
好的

**Comment by DreamAndDead** [comment]
这个问题需要前端后端协同合作，针对代码对环境做区分

细节可参考
http://keepwork.com/dreamanddead/opsway/keepwork-in-diff-env

**Comment by DreamAndDead** [comment]
@leopoldchen @yuanoook @ZhangKaitlyn @Xuntian @wxaxiaoyao
