### ISSUE TITLE
【需求】_theme和theme mod的切换和编辑需要再设计下，目前对新人难理解。 应该图形化设计一下。

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#939]

**Comment by onedou** [comment]
http://keepwork.com/lixizhi/note/theme_template_design

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34718622-53b80304-f572-11e7-89bb-1c6a0adc1f94.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/34765875-9a83e972-f62d-11e7-83b5-1c6e8fa63a30.png)
![image](https://user-images.githubusercontent.com/21214285/34765900-b38cd7bc-f62d-11e7-92ce-19083e3a1ceb.png)
