### ISSUE TITLE
【bug】编辑别人的网站，如发现没有权限保存，至少在保存时，用红色背景的提示框，提示用户保存失败，请开新窗口

### ISSUE THREAD

**Issue by duting1993** [tatfook/wikicraft#941]
![image](https://user-images.githubusercontent.com/28430070/32640364-5591f99e-c603-11e7-8f5a-c1c1f48b7143.png)
![image](https://user-images.githubusercontent.com/28430070/32640382-6f39e1e0-c603-11e7-8dd9-eb080fee50c3.png)
目前是同一种颜色

**Comment by ZhangKaitlyn** [comment]
测试地址：http://10.27.3.7:8099
