### ISSUE TITLE
【调整】登录，注册输入框提示输入email 电话

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#95]
登录，注册输入框提示输入email 电话

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/24142434/814d0074-0e61-11e7-8c05-bcb533820875.png)
![image](https://cloud.githubusercontent.com/assets/22001356/24142469/9d375334-0e61-11e7-9813-13528375fb45.png)

**Comment by ZhangKaitlyn** [comment]
已修改
