### ISSUE TITLE
【Bug-大文件】上传文件会出现无法上传的情况，请调整

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#953]
## The problem
上传文件会出现卡顿，无法上传的情况，请调整

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.75
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  大文件

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问release.keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.进入页面编辑器，打开大文件上传窗口
2.先上传几个小文件，上传成功后再上传超大文件导致出现“空间不足”的提醒框
3.再上传新的小文件，观察是否可以上传成功

* Expected Result:
1.可以上传成功，文件无丢失，信息正确
* Actual Result:
1.文件无法上传且出现统计时间为负数的情况
 

## Attachments (eg:logs/video/screenshot)
![default](https://user-images.githubusercontent.com/21214285/32647040-6ae3b8ba-c62a-11e7-8d29-640a7204a51c.png)

**Comment by ZhangKaitlyn** [comment]
可能出现该bug的几种情况：

1. 选择更新的文件大小超过可用空间大小
2. 上传的文件（包含一个以上已存在的文件），且去掉已存在文件后大小超过可用空间大小
3. 上传的文件（包含一个以上已存在的文件），选择覆盖上传，大小超过可用空间大小
4. 上传的文件（没有包含已存在的文件），大小超过可用空间大小
