### ISSUE TITLE
关键字过滤后台管理

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#958]
应ICP审核方要求，需有基于后台的关键字增删改查功能。现有逻辑将关键字存储在文件列表里，无法实现相关功能，为一劳永逸的解决此问题，需要将关键词存储迁移到数据库。

@yuanoook 需要完成以下几个部分的工作：
1. 新增数据表
2. 新增API
3. 调整前后端关键词过滤逻辑
4. 添加后台管理 @Xuntian

**Comment by yuanoook** [comment]
改动：
1. 关键词由配置文件转到数据库，新建表 sensitive_words
2. 增加关键词管理后台，支持增删查 http://release.keepwork.com/wiki/js/mod/admin/js/index#?subpage=SensitiveWords 
3. 前端使用数据库里面的关键词数据，数据缓存在内存中，刷新页面更新。
4. 后端使用数据库里面的关键词数据，数据缓存在内存中，更新关键词表的时候自动更新缓存。

**Comment by Sandu1213** [comment]
在release环境验证完毕，数据已从配置文件切换到数据库，数据库控制有效（可正常新增，删除）。
遗留问题：
1,目前的关键字列表不准，存在重复或者错误限制的情况；
2.目前新建站后立即去设置站点名称，关键字过滤无效，设置成功后，再次设置可以正常过滤；
3.没有考虑全文搜索关键字的情况，应该也需要过滤。

----遗留问题后续单独跟进，该功能验证通过
