### ISSUE TITLE
【调整】新建网站完成的页面，提示完整url，提示可以设置cname转发

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#96]
新建网站完成的页面，提示完整url，提示可以设置cname转发

**Comment by azothli** [comment]
网站是两个
http://username-project.keepwork.com
还有http://keepwork.com/user/project

您可以在【网站设置】中添加CNAME转发规则，将您拥有的其他域名定向到该网站。

网站设置，点击新窗口打开对应内容

**Comment by ZhangKaitlyn** [comment]
![image](https://cloud.githubusercontent.com/assets/18642919/24241666/8ca703bc-0ff0-11e7-9599-71213f74a68f.png)
已修改
