### ISSUE TITLE
在线视频播放页面

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/wikicraft#966]
由于目前keepwork使用qiniu的私有视频存储，视频需要带token访问，并且token有效期有时限，导致第三方对接keepwork视频服务时无法直接公开使用视频url。

解决方案：
参考youku，通过iframe嵌入keepwork视频链接，该页面只展示视频播放器。比如视频链接为keepwork.com/videos/my_video_file。

视频播放器的选择可以参考qiniu的建议：
https://developer.qiniu.com/pili/kb/3848/web-player-is-recommended

**Comment by leopoldchen** [comment]
@yuanoook 曹老师那边需要在20号左右使用

**Comment by yuanoook** [comment]
You need the qiniu file_id 
test site: http://stage.keepwork.com/wiki/video_player#?video_id=12

**Comment by yuanoook** [comment]
Support playing video, audio; 
Support using both file_id and file_key to get the source to play.
http://stage.keepwork.com/wiki/file_player#?file_key=o_1bvetgtd04261dd81j2e1ude36qb.mp3

**Comment by Sandu1213** [comment]
video and audio has checked, It's ok.
**video:**
http://stage.keepwork.com/wiki/file_player#?file_id=22
http://stage.keepwork.com/wiki/file_player#?file_key=o_1bvh5hbkd8t814liprr1ujg2eub.mp4
**audio:**
http://stage.keepwork.com/wiki/file_player#?file_id=23
http://stage.keepwork.com/wiki/file_player#?file_key=o_1bvh5qiu61a7b1qa112m5m6ob0co.mp3

**Comment by Sandu1213** [comment]
目前该功能仅限chrome浏览器，firefox和IE暂不支持
