### ISSUE TITLE
【需求】删除网站时，提示用户是否需要删除对应的数据源

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#968]
场景：
       用户已经删除网站A，再次创建网站A时，期望的是一个全新的网站。但目前会显示为删除之前的版本。
因为网站A的数据源没有在gitLab里进行删除。故希望在删除时增加一个提醒给用户，如果选择同时删除数据源则，下次创建为全新的网站；否则，还是显示之前的网站。

**Comment by Sandu1213** [comment]
@azothli 宇哥，先帮忙设计下删除时的样式（默认是不删除数据源的情况？），然后就可以去调整了。

**Comment by Tibet0312** [comment]
默认不勾选：
![image](https://user-images.githubusercontent.com/25898720/32816720-3039d752-c9f5-11e7-9347-ddc93de62ae0.png)

勾选状态：
![image](https://user-images.githubusercontent.com/25898720/32816743-4d43a724-c9f5-11e7-9dd7-d0a93bcfc43f.png)

**Comment by Sandu1213** [comment]
![image](https://user-images.githubusercontent.com/21214285/33642712-1f7e17b6-da76-11e7-8d8c-7348534ddede.png)

**Comment by yuanoook** [comment]
考虑多语言的支持？

**Comment by Sandu1213** [comment]
考虑到多语言支持的场景，样式问题暂不关注。
