### ISSUE TITLE
【需求】top条中，编辑器的按钮一直显示   加一个 	站点管理 	编辑器

### ISSUE THREAD

**Issue by azothli** [tatfook/wikicraft#97]
【需求】top条中，编辑器的按钮一直显示   加一个 	站点管理 	编辑器

**Comment by azothli** [comment]
![image](https://cloud.githubusercontent.com/assets/22001356/24129315/c68d1ae2-0e1c-11e7-81b7-1dc1f49509b3.png)
3联按钮不调整，再下拉中增加一个编辑器的快捷方式

**Comment by ZhangKaitlyn** [comment]
已添加
