### ISSUE TITLE
新建页面自动选择当前网页所在项目

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/wikicraft#98]
![default](https://cloud.githubusercontent.com/assets/94537/24129802/ec17ebe0-0e1f-11e7-9111-122aac14a2b2.png)

新建页面自动选择当前网页所在项目，如果只有一个项目， 默认选择。

**Comment by azothli** [comment]
是的，应该这样 @wxaxiaoyao

**Comment by wxaxiaoyao** [comment]
已改
