### ISSUE TITLE
【Bug-关键字过滤】新增网站成功后立即去设置网站名称，关键字过滤无效

### ISSUE THREAD

**Issue by Sandu1213** [tatfook/wikicraft#987]
## The problem
新增网站成功后立即去设置网站名称，关键字过滤无效

## Environment

* OS Info: Window10
* browser Info: chrome  62.0.3202.75
* URL: [release.keepwork.com](http://release.keepwork.com) 
* Model:  关键字过滤

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，可正常访问keepwork.com页面
2.已存在账号且账号已登录
* Details:
1.新建一个网站，然后进入网站设置页面，对网站名称进行设置
2.输入敏感词，观察是否可以过滤成功

* Expected Result:
1.过滤成功
* Actual Result:
1.过滤失败，第二次编辑时才能过滤成功
 

## Attachments (eg:logs/video/screenshot)

**Comment by ZhangKaitlyn** [comment]
测试地址：http://fix.987.stage.keepwork.com
